(function(g){var window=this;var Wya=function(a,b){return g.Kb(a,b)},$5=function(a,b,c){a.A.set(b,c)},a6=function(a){$5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.D)()).toString(36));
return a},b6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.gn(a.A,b,c)},Xya=function(a,b){var c=[];
g.lk(b,function(d){try{var e=g.jo.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.io(e)&&c.push(d)},a);
return c},Yya=function(a,b){var c=Xya(a,b);
(0,g.y)(c,function(d){g.jo.prototype.remove.call(this,d)},a)},Zya=function(a){if(a.Zc){if(a.Zc.locationOverrideToken)return{locationOverrideToken:a.Zc.locationOverrideToken};
if(null!=a.Zc.latitudeE7&&null!=a.Zc.longitudeE7)return{latitudeE7:a.Zc.latitudeE7,longitudeE7:a.Zc.longitudeE7}}return null},$ya=function(a,b){g.fb(a,b)||a.push(b)},c6=function(a){var b=0,c;
for(c in a)b++;return b},aza=function(a,b){var c=b instanceof g.yc?b:g.Dc(b,/^data:image\//i.test(b));
a.src=g.zc(c)},d6=function(){},bza=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},cza=function(a){if(a.Qd&&"function"==typeof a.Qd)return a.Qd();
if("string"===typeof a)return a.split("");if(g.Na(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Gb(a)},dza=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Na(a)||"string"===typeof a)(0,g.y)(a,b,void 0);else{if(a.Ve&&"function"==typeof a.Ve)var c=a.Ve();else if(a.Qd&&"function"==typeof a.Qd)c=void 0;else if(g.Na(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Hb(a);d=cza(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},eza=function(a,b,c,d){var e=new g.Vm(null,void 0);
a&&g.Wm(e,a);b&&g.Xm(e,b);c&&g.Ym(e,c);d&&(e.u=d);return e},e6=function(a,b){g.Ro[a]=!0;
var c=g.Po();c&&c.publish.apply(c,arguments);g.Ro[a]=!1},f6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Sm;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",fza(this,a.capabilities||""),gza(this,a.experiments||""))},fza=function(a,b){a.capabilities.clear();
(0,g.Ae)(b.split(","),g.Sa(Wya,hza)).forEach(function(c){a.capabilities.add(c)})},gza=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},g6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},h6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},iza=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},jza=function(a){return new g6(a)},kza=function(a){return Array.isArray(a)?(0,g.Ic)(a,jza):[]},i6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},j6=function(a){return Array.isArray(a)?"["+(0,g.Ic)(a,i6).join(",")+"]":"null"},k6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|
0;
return("x"==a?b:b&3|8).toString(16)})},lza=function(a){return(0,g.Ic)(a,function(b){return{key:b.id,
name:b.name}})},l6=function(a,b){return g.cb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},m6=function(a,b){return g.cb(a,function(c){return h6(c,b)})},mza=function(){var a=(0,g.Ws)();
a&&Yya(a,a.o.Ph(!0))},n6=function(){var a=g.Zs("yt-remote-connected-devices")||[];
g.wb(a);return a},nza=function(a){if(g.gb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.Ic)(a,function(d,e){return 0==e?d:d.substring(c.length)})},oza=function(a){g.Ys("yt-remote-connected-devices",a,86400)},p6=function(){if(o6)return o6;
var a=g.Zs("yt-remote-device-id");a||(a=k6(),g.Ys("yt-remote-device-id",a,31536E3));for(var b=n6(),c=1,d=a;g.fb(b,d);)c++,d=a+"#"+c;return o6=d},q6=function(){var a=n6(),b=p6();
g.fb(a,b);g.at()&&g.yb(a,b);a=nza(a);if(g.gb(a))try{g.Cq.remove("remote_sid","/","youtube.com")}catch(c){}else try{g.Dq("remote_sid",a.join(","),-1)}catch(c){}},pza=function(){return g.Zs("yt-remote-session-browser-channel")},qza=function(){return g.Zs("yt-remote-local-screens")||[]},rza=function(){g.Ys("yt-remote-lounge-token-expiration",!0,86400)},sza=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.Ic)(qza(),function(d){return d.loungeToken}),c=(0,g.Ic)(a,function(d){return d.loungeToken});
(0,g.yi)(c,function(d){return!g.fb(b,d)})&&rza();
g.Ys("yt-remote-local-screens",a,31536E3)},tza=function(a,b){g.Ys("yt-remote-session-browser-channel",a);
g.Ys("yt-remote-session-screen-id",b);var c=n6(),d=p6();g.fb(c,d)||c.push(d);oza(c);q6()},r6=function(a){a||(g.$s("yt-remote-session-screen-id"),g.$s("yt-remote-session-video-id"));
q6();a=n6();g.kb(a,p6());oza(a)},uza=function(){if(!s6){var a=g.po();
a&&(s6=new g.co(a))}return s6?!!s6.get("yt-remote-use-staging-server"):!1},vza=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},wza=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},t6=function(a){a.length?xza(a.shift(),function(){t6(a)}):u6()},yza=function(a){return"chrome-extension://"+a+"/cast_sender.js"},xza=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},u6=function(){var a=wza();
a&&a(!1,"No cast extension found")},Aza=function(){if(zza){var a=2,b=wza(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;xza("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",u6,c)}},Bza=function(){Aza();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);t6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},v6=function(a,b,c){g.A.call(this);
this.F=null!=c?(0,g.x)(a,c):a;this.Jd=b;this.C=(0,g.x)(this.KG,this);this.o=!1;this.u=0;this.A=this.Ka=null;this.B=[]},w6=function(a,b,c){g.A.call(this);
this.B=null!=c?a.bind(c):a;this.Jd=b;this.A=null;this.o=!1;this.u=0;this.Ka=null},x6=function(a){a.Ka=g.ag(function(){a.Ka=null;
a.o&&!a.u&&(a.o=!1,x6(a))},a.Jd);
var b=a.A;a.A=null;a.B.apply(null,b)},y6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return bza(a)},z6=function(){},A6=function(){},Cza=function(){},Eza=function(a){return(a=Dza(a))?new ActiveXObject(a):new XMLHttpRequest},Dza=function(a){if(!a.u&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.u=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.u},B6=function(a,b,c,d){this.o=a;
this.A=b;this.I=c;this.G=d||1;this.C=45E3;this.B=new g.A1(this);this.u=new g.$f;this.u.setInterval(250)},Gza=function(a,b,c){a.Rl=1;
a.Sh=a6(b.clone());a.kk=c;a.F=!0;Fza(a,null)},C6=function(a,b,c,d,e){a.Rl=1;
a.Sh=a6(b.clone());a.kk=null;a.F=c;e&&(a.vD=!1);Fza(a,d)},Fza=function(a,b){a.Ml=(0,g.D)();
D6(a);a.Ti=a.Sh.clone();b6(a.Ti,"t",a.G);a.no=0;a.bd=a.o.qt(a.o.Wn()?b:null);0<a.du&&(a.wr=new w6((0,g.x)(a.vE,a,a.bd),a.du));a.B.na(a.bd,"readystatechange",a.zO);var c=a.Dj?g.Rb(a.Dj):{};a.kk?(a.hs="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.bd.send(a.Ti,a.hs,a.kk,c)):(a.hs="GET",a.vD&&!g.pe&&(c.Connection="close"),a.bd.send(a.Ti,a.hs,null,c));a.o.Of(1)},Jza=function(a,b,c){for(var d=!0;!a.lj&&a.no<c.length;){var e=Hza(a,c);
if(e==E6){4==b&&(a.ji=4,F6(15),d=!1);break}else if(e==Iza){a.ji=4;F6(16);d=!1;break}else G6(a,e)}4==b&&0==c.length&&(a.ji=1,F6(17),d=!1);a.Wf=a.Wf&&d;d||(H6(a),I6(a))},Hza=function(a,b){var c=a.no,d=b.indexOf("\n",c);
if(-1==d)return E6;c=Number(b.substring(c,d));if(isNaN(c))return Iza;d+=1;if(d+c>b.length)return E6;var e=b.substr(d,c);a.no=d+c;return e},Lza=function(a,b){a.Ml=(0,g.D)();
D6(a);var c=b?window.location.hostname:"";a.Ti=a.Sh.clone();$5(a.Ti,"DOMAIN",c);$5(a.Ti,"t",a.G);try{a.cg=new ActiveXObject("htmlfile")}catch(n){H6(a);a.ji=7;F6(22);I6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var h=c.charAt(f);if("<"==h)e+="\\x3c";else if(">"==h)e+="\\x3e";else{var l=h;if(l in J6)h=J6[l];else if(l in Kza)h=J6[l]=Kza[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)h=l;else{if(256>m){if(h="\\x",16>m||256<m)h+="0"}else h="\\u",4096>m&&(h+="0");h+=m.toString(16).toUpperCase()}h=
J6[l]=h}e+=h}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.bd(g.bc("b/12014412"),d+"</body></html>");a.cg.open();a.cg.write(g.Xc(c));a.cg.close();a.cg.parentWindow.m=(0,g.x)(a.RN,a);a.cg.parentWindow.d=(0,g.x)(a.zC,a,!0);a.cg.parentWindow.rpcClose=(0,g.x)(a.zC,a,!1);c=a.cg.createElement("DIV");a.cg.parentWindow.document.body.appendChild(c);d=g.Cc(a.Ti.toString());d=g.jd(g.zc(d));d=g.bd(g.bc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.cd(c,d);a.o.Of(1)},D6=function(a){a.Uw=(0,g.D)()+a.C;
Mza(a,a.C)},Mza=function(a,b){if(null!=a.Yl)throw Error("WatchDog timer not null");
a.Yl=K6((0,g.x)(a.ZN,a),b)},L6=function(a){a.Yl&&(g.v.clearTimeout(a.Yl),a.Yl=null)},I6=function(a){a.o.Az()||a.lj||a.o.Jp(a)},H6=function(a){L6(a);
g.Me(a.wr);a.wr=null;a.u.stop();g.Ita(a.B);if(a.bd){var b=a.bd;a.bd=null;b.abort();b.dispose()}a.cg&&(a.cg=null)},G6=function(a,b){try{a.o.rC(a,b),a.o.Of(4)}catch(c){}},Oza=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;Nza(a,b,function(h){h?c(!0):g.v.setTimeout(function(){Oza(a,b,c,d,f)},f)})}},Nza=function(a,b,c){var d=new Image;
d.onload=function(){try{M6(d),c(!0)}catch(e){}};
d.onerror=function(){try{M6(d),c(!1)}catch(e){}};
d.onabort=function(){try{M6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{M6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
aza(d,a)},M6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},Pza=function(a){this.o=a;
this.u=new z6},Qza=function(a){var b=N6(a.o,a.mm,"/mail/images/cleardot.gif");
a6(b);Oza(b.toString(),5E3,(0,g.x)(a.KF,a),3,2E3);a.Of(1)},P6=function(a){var b=a.o.M;
if(null!=b)F6(5),b?(F6(11),O6(a.o,a,!1)):(F6(12),O6(a.o,a,!0));else if(a.qe=new B6(a,void 0,void 0,void 0),a.qe.Dj=a.au,b=a.o,b=N6(b,b.Wn()?a.Om:null,a.cu),F6(5),!g.ne||g.Sd(10))b6(b,"TYPE","xmlhttp"),C6(a.qe,b,!1,a.Om,!1);else{b6(b,"TYPE","html");var c=a.qe;a=!!a.Om;c.Rl=3;c.Sh=a6(b.clone());Lza(c,a)}},Q6=function(a){g.pf.call(this);
this.headers=new g.Sm;this.U=a||null;this.A=!1;this.T=this.o=null;this.ga=this.M="";this.F=0;this.B="";this.C=this.ba=this.I=this.Z=!1;this.G=0;this.N=null;this.ea="";this.R=this.aa=!1},Rza=function(a){return g.ne&&g.Rd(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},Sza=function(a){return"content-type"==a.toLowerCase()},Uza=function(a,b){a.A=!1;
a.o&&(a.C=!0,a.o.abort(),a.C=!1);a.B=b;a.F=5;Tza(a);R6(a)},Tza=function(a){a.Z||(a.Z=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},Wza=function(a){if(a.A&&"undefined"!=typeof g.F1)if(a.T[1]&&4==S6(a)&&2==a.getStatus())T6(a,"Local request error detected and ignored");
else if(a.I&&4==S6(a))g.ag(a.nC,0,a);else if(a.dispatchEvent("readystatechange"),4==S6(a)){T6(a,"Request complete");a.A=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.td(1,String(a.M));if(!f&&g.v.self&&g.v.self.location){var h=g.v.self.location.protocol;f=h.substr(0,h.length-1)}e=!Vza.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.F=6;try{var l=2<S6(a)?a.o.statusText:""}catch(m){l=""}a.B=l+" ["+a.getStatus()+"]";Tza(a)}}finally{R6(a)}}},R6=function(a,b){if(a.o){Xza(a);
var c=a.o,d=a.T[0]?g.Ka:null;a.o=null;a.T=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},Xza=function(a){a.o&&a.R&&(a.o.ontimeout=null);
a.N&&(g.v.clearTimeout(a.N),a.N=null)},S6=function(a){return a.o?a.o.readyState:0},U6=function(a){try{return a.o?a.o.responseText:""}catch(b){return""}},T6=function(a,b){return b+" ["+a.ga+" "+a.M+" "+a.getStatus()+"]"},V6=function(a,b,c){this.o=1;
this.u=[];this.B=[];this.C=new z6;this.I=a||null;this.M=null!=b?b:null;this.F=c||!1},Yza=function(a,b){this.o=a;
this.map=b;this.context=null},Zza=function(a){g.Oe.call(this,"statevent",a)},$za=function(a,b){g.Oe.call(this,"timingevent",a);
this.size=b},aAa=function(a){g.Oe.call(this,"serverreachability",a)},dAa=function(a){bAa(a);
if(3==a.o){var b=a.vn++,c=a.qp.clone();$5(c,"SID",a.A);$5(c,"RID",b);$5(c,"TYPE","terminate");W6(a,c);b=new B6(a,a.A,b,void 0);b.Rl=2;b.Sh=a6(c.clone());aza(new Image,b.Sh.toString());b.Ml=(0,g.D)();D6(b)}cAa(a)},eAa=function(a){a.iG(1,0);
a.qp=N6(a,null,a.Zt);X6(a)},bAa=function(a){a.Vh&&(a.Vh.abort(),a.Vh=null);
a.Bc&&(a.Bc.cancel(),a.Bc=null);a.Vg&&(g.v.clearTimeout(a.Vg),a.Vg=null);Y6(a);a.fe&&(a.fe.cancel(),a.fe=null);a.ai&&(g.v.clearTimeout(a.ai),a.ai=null)},fAa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new Yza(a.AK++,b));2!=a.o&&3!=a.o||X6(a)},X6=function(a){a.fe||a.ai||(a.ai=K6((0,g.x)(a.yC,a),0),a.Sk=0)},hAa=function(a,b){if(1==a.o){if(!b){a.vn=Math.floor(1E5*Math.random());
var c=a.vn++,d=new B6(a,"",c,void 0);d.Dj=null;var e=Z6(a),f=a.qp.clone();$5(f,"RID",c);$5(f,"CVER","1");W6(a,f);Gza(d,f,e);a.fe=d;a.o=2}}else 3==a.o&&(b?gAa(a,b):0==a.u.length||a.fe||gAa(a))},gAa=function(a,b){if(b)if(6<a.mj){a.u=a.B.concat(a.u);
a.B.length=0;var c=a.vn-1;var d=Z6(a)}else c=b.I,d=b.kk;else c=a.vn++,d=Z6(a);var e=a.qp.clone();$5(e,"SID",a.A);$5(e,"RID",c);$5(e,"AID",a.pl);W6(a,e);c=new B6(a,a.A,c,a.Sk+1);c.Dj=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.fe=c;Gza(c,e,d)},W6=function(a,b){if(a.Gd){var c=a.Gd.Yy();
c&&g.Ab(c,function(d,e){$5(b,e,d)})}},Z6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.mj&&0<b){var d=a.u[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.u[e].o,h=a.u[e].map;f=6>=a.mj?e:f-d;try{g.Ab(h,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.B=a.B.concat(a.u.splice(0,b));
return c.join("&")},iAa=function(a){a.Bc||a.Vg||(a.G=1,a.Vg=K6((0,g.x)(a.xC,a),0),a.Ek=0)},$6=function(a){if(a.Bc||a.Vg||3<=a.Ek)return!1;
a.G++;a.Vg=K6((0,g.x)(a.xC,a),jAa(a,a.Ek));a.Ek++;return!0},O6=function(a,b,c){a.ds=c;
a.ng=b.oh;a.F||eAa(a)},Y6=function(a){null!=a.rj&&(g.v.clearTimeout(a.rj),a.rj=null)},jAa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},a7=function(a,b){if(2==b||9==b){var c=null;
a.Gd&&(c=null);var d=(0,g.x)(a.kP,a);c||(c=new g.Vm("//www.google.com/images/cleardot.gif"),a6(c));Nza(c.toString(),1E4,d)}else F6(2);kAa(a,b)},kAa=function(a,b){a.o=0;
a.Gd&&a.Gd.ly(b);cAa(a);bAa(a)},cAa=function(a){a.o=0;
a.ng=-1;if(a.Gd)if(0==a.B.length&&0==a.u.length)a.Gd.Ys();else{g.ob(a.B);var b=g.ob(a.u);a.B.length=0;a.u.length=0;a.Gd.Ys(b)}},N6=function(a,b,c){var d=g.cn(c);
if(""!=d.o)b&&g.Xm(d,b+"."+d.o),g.Ym(d,d.B);else{var e=window.location;d=eza(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Em&&g.Ab(a.Em,function(f,h){$5(d,h,f)});
$5(d,"VER",a.mj);W6(a,d);return d},K6=function(a,b){if(!g.Oa(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},F6=function(a){b7.dispatchEvent(new Zza(b7,a))},lAa=function(){},mAa=function(){this.o=[];
this.u=[]},nAa=function(a,b){this.action=a;
this.params=b||{}},c7=function(a,b){g.A.call(this);
this.o=new g.H(this.KN,0,this);g.C(this,this.o);this.Jd=5E3;this.u=0;if("function"===typeof a)b&&(a=(0,g.x)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.A=a},d7=function(a,b,c){this.N=a;
this.F=b;this.A=new g.bo;this.u=new c7(this.NO,this);this.o=null;this.Mb=!1;this.C=null;this.M="";this.I=this.B=0;this.G=[];this.R=c||!1},oAa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.ds,sessionId:a.o.A,arrayId:a.o.pl}},pAa=function(a,b){a.I=b||0;
a.u.stop();a.o&&(3==a.o.o&&hAa(a.o),dAa(a.o));a.I=0},e7=function(a){return!!a.o&&3==a.o.o},qAa=function(a,b){(a.F.loungeIdToken=b)||a.u.stop()},f7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.td(4,a))||"";b&&(this.port=":"+b);this.domain=g.ud(a)||"";a=g.Pc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.vc(a,"10.0")&&(this.u=!1))},g7=function(a,b){var c=a.o;
a.u&&(c="https://"+a.domain+a.port+a.o);return g.Ed(c+b,{})},h7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Sa(a.B,d,!0),onError:g.Sa(a.A,e),Ke:g.Sa(a.C,e)};c&&(a.Db=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.wq(b,a)},uAa=function(){var a=rAa;
sAa();i7.push(a);tAa(i7)},j7=function(a,b){sAa();
var c=i7,d=vAa(a,String(b));g.gb(c)?wAa(d):(tAa(c),(0,g.y)(c,function(e){e(d)}))},sAa=function(){i7||(i7=g.Ja("yt.mdx.remote.debug.handlers_")||[],g.Ha("yt.mdx.remote.debug.handlers_",i7,void 0))},wAa=function(a){var b=(k7+1)%50;
k7=b;l7[b]=a;m7||(m7=49==b)},tAa=function(a){var b=l7;
if(b[0]){var c=k7,d=m7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.y)(a,function(f){f(e)})}while(d!=c);
l7=Array(50);k7=-1;m7=!1}},vAa=function(a,b){var c=((0,g.D)()-xAa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},n7=function(a){g.N.call(this);
this.F=a;this.screens=[]},yAa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.screens.push(b);return!0},zAa=function(a,b){var c=a.screens.length!=b.length;
a.screens=(0,g.Ae)(a.screens,function(f){return!!l6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=yAa(a,b[d])||c;return c},AAa=function(a,b){var c=a.screens.length;
a.screens=(0,g.Ae)(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},o7=function(a,b,c,d){g.N.call(this);
this.F=a;this.B=b;this.C=c;this.A=d;this.u=0;this.o=null;this.Ka=NaN},q7=function(a){n7.call(this,"LocalScreenService");
this.u=a;this.o=NaN;p7(this);this.info("Initializing with "+j6(this.screens))},BAa=function(a){if(a.screens.length){var b=(0,g.Ic)(a.screens,function(d){return d.id}),c=g7(a.u,"/pairing/get_lounge_token_batch");
h7(a.u,c,{screen_ids:b.join(",")},(0,g.x)(a.UG,a),(0,g.x)(a.TG,a))}},p7=function(a){var b=kza(qza());
b=(0,g.Ae)(b,function(c){return!c.uuid});
return zAa(a,b)},r7=function(a,b){sza((0,g.Ic)(a.screens,iza));
b&&rza()},t7=function(a,b){g.N.call(this);
this.F=b;var c=g.Zs("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,h=e.length;f<h;++f){var l=e[f].id;d[l]=g.fb(c,l)}this.o=d;this.C=a;this.A=this.B=NaN;this.u=null;s7("Initialized with "+g.Nk(this.o))},CAa=function(a,b,c){var d=g7(a.C,"/pairing/get_screen_availability");
h7(a.C,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},u7=function(a,b){a:if(c6(b)!=c6(a.o))var c=!1;
else{c=g.Hb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(s7("Updated online screens: "+g.Nk(a.o)),a.o=b,a.S("screenChange"));DAa(a)},v7=function(a){isNaN(a.A)||g.Oo(a.A);
a.A=g.Mo((0,g.x)(a.Sv,a),0<a.B&&a.B<(0,g.D)()?2E4:1E4)},s7=function(a){j7("OnlineScreenService",a)},EAa=function(a){var b={};
(0,g.y)(a.F(),function(c){c.token?b[c.token]=c.id:this.oc("Requesting availability of screen w/o lounge token.")});
return b},DAa=function(a){a=g.Hb(g.Bb(a.o,function(b){return b}));
g.wb(a);a.length?g.Ys("yt-remote-online-screen-ids",a.join(","),60):g.$s("yt-remote-online-screen-ids")},w7=function(a){n7.call(this,"ScreenService");
this.C=a;this.o=this.u=null;this.A=[];this.B={};FAa(this)},HAa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var h=a.Ee();if(h=(c?m6(h,c):null)||m6(h,b)){h.uuid=b;var l=x7(a,h);CAa(a.o,l,function(m){e(m?l:null)})}else c?GAa(a,c,(0,g.x)(function(m){var n=x7(this,new g6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));CAa(this.o,n,function(q){e(q?n:null)})},a),f):e(null)},IAa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},GAa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Db:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){var l=h&&h.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.wq(g7(a.C,"/pairing/get_lounge_token_batch"),e)},JAa=function(a){a.screens=a.u.Ee();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+j6(a.screens))},FAa=function(a){y7(a);
a.u=new q7(a.C);a.u.subscribe("screenChange",(0,g.x)(a.bH,a));JAa(a);a.A=kza(g.Zs("yt-remote-automatic-screen-cache")||[]);y7(a);a.info("Initializing automatic screens: "+j6(a.A));a.o=new t7(a.C,(0,g.x)(a.Ee,a,!0));a.o.subscribe("screenChange",(0,g.x)(function(){this.S("onlineScreenChange")},a))},x7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=m6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.Ys("yt-remote-automatic-screen-cache",(0,g.Ic)(a.A,iza)));y7(a);a.B[b.uuid]=b.id;g.Ys("yt-remote-device-id-map",a.B,31536E3);return b},y7=function(a){a.B=g.Zs("yt-remote-device-id-map")||{}},z7=function(a,b,c){g.N.call(this);
this.T=c;this.M=a;this.o=b;this.I=null},A7=function(a,b){j7(a.T,b)},B7=function(a,b){z7.call(this,a,b,"CastSession");
this.u=null;this.A=0;this.C=(0,g.x)(this.OP,this);this.B=(0,g.x)(this.gO,this);this.A=g.Mo((0,g.x)(function(){KAa(this,null)},this),12E4)},LAa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Nk(void 0));
var b={type:"getMdxSessionStatus"};a.u?a.u.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ka,(0,g.x)(function(){A7(this,"Failed to send message: getMdxSessionStatus.")},a)):A7(a,"Sending yt message without session: "+g.Nk(b))},KAa=function(a,b){g.Oo(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.getScreen()||a.getScreen().id!=b){var c=(0,g.x)(a.ir,a),d=(0,g.x)(a.Je,a);a.sz(b,c,d,5)}}else a.Je(Error("Waiting for session status timed out."))},C7=function(a,b,c){z7.call(this,a,b,"DialSession");
this.A=this.G=null;this.N="";this.U=c;this.B=null;this.F=g.Ka;this.C=NaN;this.R=(0,g.x)(this.RP,this);this.u=g.Ka},MAa=function(a){a.u=a.M.BE(a.N,a.o.label,a.o.friendlyName,(0,g.x)(function(b){this.u=g.Ka;
this.ir(b)},a),(0,g.x)(function(b){this.u=g.Ka;
this.Je(b)},a))},NAa=function(a){var b={};
b.pairingCode=a.N;b.theme=a.U;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}uza()&&(b.env_useStageMdx=1);return g.Cd(b)},D7=function(a,b){z7.call(this,a,b,"ManualSession");
this.u=g.Mo((0,g.x)(this.ql,this,null),150)},E7=function(a,b,c,d){g.N.call(this);
this.u=a;this.G=b||"233637DE";this.F=c||"cl";this.I=d||!1;this.o=null;this.C=!1;this.A=[];this.B=(0,g.x)(this.ZM,this)},OAa=function(a,b){return b?g.cb(a.A,function(c){return h6(b,c.label)},a):null},F7=function(a){j7("Controller",a)},rAa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},G7=function(a){return a.C||!!a.A.length||!!a.o},H7=function(a,b,c){b!=a.o&&(g.Me(a.o),(a.o=b)?(c?a.S("yt-remote-cast2-receiver-resumed",b.o):a.S("yt-remote-cast2-receiver-selected",
b.o),b.subscribe("sessionScreen",(0,g.x)(a.wC,a,b)),b.getScreen()?a.S("yt-remote-cast2-session-change",b.getScreen()):c&&a.o.ql(null)):a.S("yt-remote-cast2-session-change",null))},PAa=function(a){var b=a.u.AE(),c=a.o&&a.o.o;
a=(0,g.Ic)(b,function(d){c&&h6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=OAa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},VAa=function(a,b,c,d,e,f,h){QAa()?RAa(b,e,f,h)&&(J7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?SAa(a,c):(window.__onGCastApiAvailable=function(l,m){l?SAa(a,c):(K7("Failed to load cast API: "+m),L7(!1),J7(!1),g.$s("yt-remote-cast-available"),g.$s("yt-remote-cast-receiver"),TAa(),c(!1))},d?g.Yo("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?Bza():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?u6():(Aza(),t6(UAa.map(yza))))):I7("Cannot initialize because not running Chrome")},TAa=function(){I7("dispose");
var a=M7();a&&a.dispose();g.Ha("yt.mdx.remote.cloudview.instance_",null,void 0);WAa(!1);g.Uo(N7);N7.length=0},O7=function(){return!!g.Zs("yt-remote-cast-installed")},XAa=function(){var a=g.Zs("yt-remote-cast-receiver");
return a?a.friendlyName:null},YAa=function(){I7("clearCurrentReceiver");
g.$s("yt-remote-cast-receiver")},ZAa=function(){return O7()?M7()?M7().getCastSession():(K7("getCastSelector: Cast is not initialized."),null):(K7("getCastSelector: Cast API is not installed!"),null)},Q7=function(){O7()?M7()?P7()?(I7("Requesting cast selector."),M7().requestSession()):(I7("Wait for cast API to be ready to request the session."),N7.push(g.To("yt-remote-cast2-api-ready",Q7))):K7("requestCastSelector: Cast is not initialized."):K7("requestCastSelector: Cast API is not installed!")},R7=
function(a,b){P7()?M7().setConnectedScreenStatus(a,b):K7("setConnectedScreenStatus called before ready.")},QAa=function(){var a=0<=g.Pc.search(/ (CrMo|Chrome|CriOS)\//);
return g.Qw||a},$Aa=function(a,b){M7().init(a,b)},RAa=function(a,b,c,d){var e=!1;
M7()||(a=new E7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.Ys("yt-remote-cast-available",f);e6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){I7("onReceiverSelected: "+f.friendlyName);
g.Ys("yt-remote-cast-receiver",f);e6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){I7("onReceiverResumed: "+f.friendlyName);
g.Ys("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){I7("onSessionChange: "+i6(f));
f||g.$s("yt-remote-cast-receiver");e6("yt-remote-cast2-session-change",f)}),g.Ha("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
I7("cloudview.createSingleton_: "+e);return e},M7=function(){return g.Ja("yt.mdx.remote.cloudview.instance_")},SAa=function(a,b){L7(!0);
J7(!1);$Aa(a,function(c){c?(WAa(!0),g.Vo("yt-remote-cast2-api-ready")):(K7("Failed to initialize cast API."),L7(!1),g.$s("yt-remote-cast-available"),g.$s("yt-remote-cast-receiver"),TAa());b(c)})},I7=function(a){j7("cloudview",a)},K7=function(a){j7("cloudview",a)},L7=function(a){I7("setCastInstalled_ "+a);
g.Ys("yt-remote-cast-installed",a)},P7=function(){return!!g.Ja("yt.mdx.remote.cloudview.apiReady_")},WAa=function(a){I7("setApiReady_ "+a);
g.Ha("yt.mdx.remote.cloudview.apiReady_",a,void 0)},J7=function(a){g.Ha("yt.mdx.remote.cloudview.initializing_",a,void 0)},S7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.F=this.G=0;this.o=null;this.hasNext=this.og=!1;this.M=this.I=this.u=this.C=0;this.B=NaN;this.A=!1;this.reset(a)},T7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.og=!1;a.hasNext=!1;a.G=0;a.F=(0,g.D)();a.C=0;a.u=0;a.I=0;a.M=0;a.B=NaN;a.A=!1},U7=function(a){return a.qb()?((0,g.D)()-a.F)/1E3:0},V7=function(a,b){a.G=b;
a.F=(0,g.D)()},W7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.D)()-a.F)/1E3+a.G;
case -1E3:return 0}return a.G},X7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&T7(a)},Y7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Sb(a.o);b.hasPrevious=a.og;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.F;b.seekableStart=a.C;b.seekableEnd=a.u;b.duration=a.I;b.loadedTime=a.M;b.liveIngestionTime=a.B;return b},$7=function(a,b){g.N.call(this);
this.o=0;this.B=a;this.F=[];this.C=new mAa;this.A=this.u=null;this.M=(0,g.x)(this.hL,this);this.G=(0,g.x)(this.yn,this);this.I=(0,g.x)(this.gL,this);this.N=(0,g.x)(this.qL,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Xw,this),aBa(this))):c=3;0!=c&&(b?this.Xw(c):g.Mo((0,g.x)(function(){this.Xw(c)},this),0));
var d=ZAa();d&&Z7(this,d);this.subscribe("yt-remote-cast2-session-change",this.N)},a8=function(a){return new S7(a.B.getPlayerContextData())},aBa=function(a){(0,g.y)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.F.push(this.B.subscribe(b,g.Sa(this.WM,b),this))},a)},bBa=function(a){(0,g.y)(a.F,function(b){this.B.unsubscribeByKey(b)},a);
a.F.length=0},b8=function(a,b){var c=a.C;
50>c.o.length+c.u.length&&a.C.u.push(b)},d8=function(a,b,c){var d=a8(a);
V7(d,c);-1E3!=d.playerState&&(d.playerState=b);c8(a,d)},e8=function(a,b,c){a.B.sendMessage(b,c)},c8=function(a,b){bBa(a);
a.B.setPlayerContextData(Y7(b));aBa(a)},Z7=function(a,b){a.A&&(a.A.removeUpdateListener(a.M),a.A.removeMediaListener(a.G),a.yn(null));
a.A=b;a.A&&(j7("CP","Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.M),a.A.addMediaListener(a.G),a.A.media.length&&a.yn(a.A.media[0]))},cBa=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=a8(a);b.contentId!=d.videoId&&j7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;V7(d,a.u.getEstimatedTime());c8(a,d)}else j7("CP","No cast media video. Ignoring state update.")},f8=function(a,b,c){return(0,g.x)(function(d){this.oc("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.oc("Retrying "+b+" using MDx browser channel."),e8(this,b,c))},a)},g8=function(a,b,c){g.N.call(this);
this.C=NaN;this.R=!1;this.I=this.G=this.M=this.N=NaN;this.T=[];this.B=this.F=this.A=this.fb=this.o=null;this.Z=a;this.T.push(g.ip(window,"beforeunload",(0,g.x)(this.MG,this)));this.u=[];this.fb=new S7;this.U=b.id;this.o=dBa(this,c);this.o.subscribe("handlerOpened",this.lL,this);this.o.subscribe("handlerClosed",this.iL,this);this.o.subscribe("handlerError",this.jL,this);this.o.subscribe("handlerMessage",this.kL,this);qAa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var d=this.fb.videoId;
g.at()&&g.Ys("yt-remote-session-video-id",d)},this)},h8=function(a){j7("conn",a)},dBa=function(a,b){return new d7(g7(a.Z,"/bc"),b)},i8=function(a,b){a.S("proxyStateChange",b)},eBa=function(a){a.C=g.Mo((0,g.x)(function(){h8("Connecting timeout");
this.Nk(1)},a),2E4)},j8=function(a){g.Oo(a.C);
a.C=NaN},k8=function(a){g.Oo(a.N);
a.N=NaN},fBa=function(a){l8(a);
a.M=g.Mo((0,g.x)(function(){m8(this,"getNowPlaying")},a),2E4)},l8=function(a){g.Oo(a.M);
a.M=NaN},hBa=function(a,b){b&&(j8(a),k8(a));
b==(e7(a.o)&&isNaN(a.C))?b&&(i8(a,1),m8(a,"getSubtitlesTrack")):b?(a.qz()&&a.fb.reset(),i8(a,1),m8(a,"getNowPlaying"),gBa(a)):a.Nk(1)},iBa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.fb.videoId&&(g.Ob(b.params)?a.fb.o=null:a.fb.o=b.params,a.S("remotePlayerChange"))},jBa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.fb.listId=b.params.listId||a.fb.listId;X7(a.fb,c,d);a.S("remoteQueueChange")},lBa=function(a,b){b.params=b.params||{};
jBa(a,b);kBa(a,b);a.S("autoplayDismissed")},kBa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
V7(a.fb,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.fb.playerState&&(c=-1E3);a.fb.playerState=c;c=Number(b.params.loadedTime);a.fb.M=isNaN(c)?0:c;c=Number(b.params.duration);a.fb.I=isNaN(c)?0:c;c=a.fb;var d=Number(b.params.liveIngestionTime);c.B=d;c.A=isNaN(d)?!1:!0;c=a.fb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.u=isNaN(e)?0:e;1==a.fb.playerState?fBa(a):l8(a);a.S("remotePlayerChange")},mBa=function(a,b){if(-1E3!=
a.fb.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.fb.playerState=c;c=parseInt(b.params.currentTime,10);V7(a.fb,isNaN(c)?0:c);a.S("remotePlayerChange")}},nBa=function(a,b){var c="true"==b.params.muted;
a.fb.volume=parseInt(b.params.volume,10);a.fb.muted=c;a.S("remotePlayerChange")},oBa=function(a,b){a.F=b.params.videoId;
a.S("nowAutoplaying",parseInt(b.params.timeout,10))},pBa=function(a,b){var c="true"==b.params.hasNext;
a.fb.og="true"==b.params.hasPrevious;a.fb.hasNext=c;a.S("previousNextChange")},gBa=function(a){g.Oo(a.I);
a.I=g.Mo((0,g.x)(a.Nk,a,1),864E5)},m8=function(a,b,c){c?h8("Sending: action="+b+", params="+g.Nk(c)):h8("Sending: action="+b);
a.o.sendMessage(b,c)},n8=function(a){n7.call(this,"ScreenServiceProxy");
this.Id=a;this.o=[];this.o.push(this.Id.$_s("screenChange",(0,g.x)(this.MP,this)));this.o.push(this.Id.$_s("onlineScreenChange",(0,g.x)(this.zM,this)))},uBa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.K("MDX_CONFIG")||b;mza();q6();o8||(o8=new f7(b?b.loungeApiHost:void 0),uza()&&(o8.o="/api/loungedev"));p8||(p8=g.Ja("yt.mdx.remote.deferredProxies_")||[],g.Ha("yt.mdx.remote.deferredProxies_",p8,void 0));qBa();var c=q8();if(!c){var d=new w7(o8);g.Ha("yt.mdx.remote.screenService_",d,void 0);c=q8();var e=!1,f=void 0,h=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,h=b.theme,l=!!b.disableDial);VAa(a,d,function(m){m?r8()&&R7(r8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){e6("yt-remote-receiver-availability-change")})},e,f,h,l)}b&&!g.Ja("yt.mdx.remote.initialized_")&&(g.Ha("yt.mdx.remote.initialized_",!0,void 0),s8("Initializing: "+g.Nk(b)),t8.push(g.To("yt-remote-cast2-availability-change",function(){e6("yt-remote-receiver-availability-change")})),t8.push(g.To("yt-remote-cast2-receiver-selected",function(){u8(null);
e6("yt-remote-auto-connect","cast-selector-receiver")})),t8.push(g.To("yt-remote-cast2-receiver-resumed",function(){e6("yt-remote-receiver-resumed","cast-selector-receiver")})),t8.push(g.To("yt-remote-cast2-session-change",rBa)),t8.push(g.To("yt-remote-connection-change",function(m){m?R7(r8(),"YouTube TV"):v8()||(R7(null,null),YAa())})),a=w8(),b.isAuto&&(a.id+="#dial"),g.Co("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(h=b.theme)&&(a.theme=h),s8(" -- with channel params: "+
g.Nk(a)),sBa(a),c.start(),r8()||tBa())},wBa=function(){var a=vBa();
O7()&&g.Zs("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},vBa=function(){var a=q8().Id.$_gos();
var b=x8();b&&y8()&&(l6(a,b)||a.push(b));return lza(a)},z8=function(){var a=xBa();
!a&&O7()&&XAa()&&(a={key:"cast-selector-receiver",name:XAa()});return a},xBa=function(){var a=vBa(),b=x8();
b||(b=v8());return g.cb(a,function(c){return b&&h6(b,c.key)?!0:!1})},x8=function(){var a=r8();
if(!a)return null;var b=q8().Ee();return m6(b,a)},rBa=function(a){s8("remote.onCastSessionChange_: "+i6(a));
if(a){var b=x8();b&&b.id==a.id?R7(b.id,"YouTube TV"):(b&&A8(),B8(a,1))}else y8()&&A8()},A8=function(){P7()?M7().stopSession():K7("stopSession called before API ready.");
var a=y8();a&&(a.disconnect(1),C8(null))},D8=function(){var a=y8();
return!!a&&3!=a.getProxyState()},s8=function(a){j7("remote",a)},q8=function(){if(!E8){var a=g.Ja("yt.mdx.remote.screenService_");
E8=a?new n8(a):null}return E8},r8=function(){return g.Ja("yt.mdx.remote.currentScreenId_")},yBa=function(a){g.Ha("yt.mdx.remote.currentScreenId_",a,void 0)},zBa=function(){return g.Ja("yt.mdx.remote.connectData_")},u8=function(a){g.Ha("yt.mdx.remote.connectData_",a,void 0)},y8=function(){return g.Ja("yt.mdx.remote.connection_")},C8=function(a){var b=y8();
u8(null);a||yBa("");g.Ha("yt.mdx.remote.connection_",a,void 0);p8&&((0,g.y)(p8,function(c){c(a)}),p8.length=0);
b&&!a?e6("yt-remote-connection-change",!1):!b&&a&&e6("yt-remote-connection-change",!0)},v8=function(){var a=g.at();
if(!a)return null;var b=q8();if(!b)return null;b=b.Ee();return m6(b,a)},B8=function(a,b){r8();
x8()&&x8();if(F8)G8=a;else{yBa(a.id);var c=new g8(o8,a,w8());c.connect(b,zBa());c.subscribe("beforeDisconnect",function(d){e6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){y8()&&(y8(),C8(null))});
C8(c)}},tBa=function(){var a=v8();
a?(s8("Resume connection to: "+i6(a)),B8(a,0)):(r6(),YAa(),s8("Skipping connecting because no session screen found."))},qBa=function(){var a=w8();
if(g.Ob(a)){a=p6();var b=g.Zs("yt-remote-session-name")||"",c=g.Zs("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ha("yt.mdx.remote.channelParams_",a,void 0)}},w8=function(){return g.Ja("yt.mdx.remote.channelParams_")||{}},sBa=function(a){a?(g.Ys("yt-remote-session-app",a.app),g.Ys("yt-remote-session-name",a.name)):(g.$s("yt-remote-session-app"),g.$s("yt-remote-session-name"));
g.Ha("yt.mdx.remote.channelParams_",a,void 0)},H8=function(a,b,c){g.A.call(this);
var d=this;this.module=a;this.H=b;this.Ya=c;this.events=new g.cs(this);this.M=this.events.L(this.H,"onVolumeChange",this.XB);this.B=!1;this.suggestion=null;this.C=new g.cH(64);this.o=new g.H(this.FD,500,this);this.u=new g.H(this.GD,1E3,this);this.G=new v6(this.sP,0,this);this.A={};this.I=new g.H(this.lE,1E3,this);this.F=new w6(this.seekTo,1E3,this);this.N=g.Ka;g.C(this,this.events);this.events.L(b,"onCaptionsTrackListChanged",this.ZL);this.events.L(b,"captionschanged",this.fL);this.events.L(b,"captionssettingschanged",
this.ID);this.events.L(b,"videoplayerreset",this.jr);this.events.L(b,"mdxautoplaycancel",function(){d.Ya.Hy()});
a=this.Ya;a.ia();a.subscribe("proxyStateChange",this.qC,this);a.subscribe("remotePlayerChange",this.En,this);a.subscribe("remoteQueueChange",this.jr,this);a.subscribe("previousNextChange",this.mC,this);a.subscribe("nowAutoplaying",this.iC,this);a.subscribe("autoplayDismissed",this.IB,this);g.C(this,this.o);g.C(this,this.u);g.C(this,this.G);g.C(this,this.I);g.C(this,this.F);this.ID();this.jr();this.En()},ABa=function(a){a.Vb(0);
a.o.stop();a.Nc(new g.cH(64))},J8=function(a,b){if(I8(a)&&!a.B){var c=null;
b&&(c={style:a.H.getSubtitlesUserSettings()},g.Ub(c,b));a.Ya.yE(a.H.getVideoData(1).videoId,c);a.A=a8(a.Ya).o}},K8=function(a,b){var c=a.H.getPlaylist();
if(c){var d=c.index;var e=c.listId.toString()}c=a.H.getVideoData(1);a.Ya.playVideo(c.videoId,b,d,e,c.playerParams,c.Ef,Zya(c));a.Nc(new g.cH(1))},BBa=function(a,b){if(b){var c=a.H.getOption("captions","tracklist",{Rz:1});
c&&c.length?(a.H.setOption("captions","track",b),a.B=!1):(a.H.loadModule("captions"),a.B=!0)}else a.H.setOption("captions","track",{})},I8=function(a){return a8(a.Ya).videoId===a.H.getVideoData(1).videoId},L8=function(){g.U.call(this,{D:"div",
J:"ytp-mdx-manual-pairing-popup-dialog",P:{role:"dialog"},K:[{D:"div",J:"ytp-mdx-manual-pairing-popup-dialog-inner-content",K:[{D:"div",J:"ytp-mdx-manual-pairing-popup-title",W:"Connecting to your TV on web using a code will be going away soon"},{D:"div",J:"ytp-mdx-manual-pairing-popup-buttons",K:[{D:"button",Y:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],W:"Learn more"},{D:"button",Y:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],W:"OK"}]}]}]});this.o=new g.cO(this,250);this.learnMoreButton=
this.da("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.da("ytp-mdx-manual-pairing-popup-ok");g.C(this,this.o);this.L(this.learnMoreButton,"click",this.u);this.L(this.okButton,"click",this.A)},M8=function(){g.U.call(this,{D:"div",
J:"ytp-mdx-popup-dialog",P:{role:"dialog"},K:[{D:"div",J:"ytp-mdx-popup-dialog-inner-content",K:[{D:"div",J:"ytp-mdx-popup-title",W:"You're signed out"},{D:"div",J:"ytp-mdx-popup-description",W:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{D:"div",J:"ytp-mdx-privacy-popup-buttons",K:[{D:"button",Y:["ytp-button","ytp-mdx-privacy-popup-cancel"],W:"Cancel"},{D:"button",Y:["ytp-button","ytp-mdx-privacy-popup-confirm"],
W:"Confirm"}]}]}]});this.o=new g.cO(this,250);this.cancelButton=this.da("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.da("ytp-mdx-privacy-popup-confirm");g.C(this,this.o);this.L(this.cancelButton,"click",this.u);this.L(this.confirmButton,"click",this.A)},N8=function(a){g.U.call(this,{D:"div",
J:"ytp-remote",K:[{D:"div",J:"ytp-remote-display-status",K:[{D:"div",J:"ytp-remote-display-status-icon",K:[g.jM()]},{D:"div",J:"ytp-remote-display-status-text",W:"{{statustext}}"}]}]});this.api=a;this.o=new g.cO(this,250);g.C(this,this.o);this.L(a,"presentingplayerstatechange",this.u);CBa(this,g.hM(a))},CBa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
c=g.T(b,128)?g.KL("Error on $RECEIVER_NAME",c):b.qb()||g.T(b,4)?g.KL("Playing on $RECEIVER_NAME",c):g.KL("Connected to $RECEIVER_NAME",c);a.ma("statustext",c);a.o.show()}else a.o.hide()},O8=function(a,b){g.wR.call(this,"Play on",0,a,b);
this.H=a;this.Si={};this.L(a,"onMdxReceiversChange",this.B);this.L(a,"presentingplayerstatechange",this.B);this.B()},P8=function(a){g.IN.call(this,a);
this.Jf={key:k6(),name:"This computer"};this.Ae=null;this.subscriptions=[];this.Ev=this.Ya=null;this.Si=[this.Jf];this.Xh=this.Jf;this.Rb=new g.cH(64);this.iA=0;this.jd=-1;this.sl=null;this.Fn=this.kq=!1;this.jk=this.Il=null;if(!g.Iy(this.player.O())){a=this.player;var b=g.VM(a);b&&(b=b.Aj())&&(b=new O8(a,b),g.C(this,b));b=new N8(a);g.C(this,b);g.uN(a,b.element,4);this.Il=new M8;g.C(this,this.Il);g.uN(a,this.Il.element,4);g.P(this.player.O().experiments,"pair_servlet_deprecation_warning_enabled")&&
(this.sl=new L8,g.C(this,this.sl),g.uN(a,this.sl.element,4));this.Fn=!!v8();this.kq=!!g.Zs("yt-remote-manual-pairing-warning-shown")}},Q8=function(a){a.jk&&(a.player.removeEventListener("presentingplayerstatechange",a.jk),a.jk=null)},DBa=function(a,b,c){a.Rb=c;
a.player.S("presentingplayerstatechange",new g.lH(c,b))},EBa=function(a,b,c){var d=!1;
1===b?d=!a.Fn:2===b&&(d=!a.kq);d&&g.nH(c,8)&&(a.player.pauseVideo(),Q8(a))},R8=function(a,b){if(b.key!==a.Xh.key)if(b.key===a.Jf.key)A8();
else{if(a.sl&&!a.kq&&b!==a.Jf&&"cast-selector-receiver"!==b.key&&g.Ry(a.player.O()))FBa(a);else{var c;(c=!g.P(a.player.O().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.K("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.K("SESSION_INDEX")&&!g.K("LOGGED_IN")))||a.Fn||!a.Il);(c?0:g.Ry(a.player.O())||g.Vy(a.player.O()))&&GBa(a)}a.Xh=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.P(a.player.O().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.getLength();l++)h[l]=f.Ca(l).videoId}else h=[e];f=a.player.getCurrentTime(1);d={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Ef,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=Zya(c))&&(d.locationInfo=c);c=d}s8("Connecting to: "+g.Nk(b));"cast-selector-receiver"==b.key?(u8(c||null),c=
c||null,P7()?M7().setLaunchParams(c):K7("setLaunchParams called before ready.")):!c&&D8()&&r8()==b.key?e6("yt-remote-connection-change",!0):(A8(),u8(c||null),c=q8().Ee(),(c=m6(c,b.key))&&B8(c,1))}},GBa=function(a){g.hM(a.player).qb()?a.player.pauseVideo():(a.jk=function(b){EBa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.jk));
a.Il&&a.Il.Wb();y8()||(F8=!0)},FBa=function(a){g.hM(a.player).qb()?a.player.pauseVideo():(a.jk=function(b){EBa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.jk));
a.sl&&a.sl.Wb();y8()||(F8=!0)},Kza={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},J6={"'":"\\'"},HBa={},hza={tQ:"atp",mT:"ska",XS:"que",lS:"mus",lT:"sus",sR:"dsp",eT:"seq"},s6,o6="",zza=vza("loadCastFramework")||vza("loadCastApplicationFramework"),UAa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Ua(v6,g.A);g.k=v6.prototype;g.k.JG=function(a){this.B=arguments;this.o=!1;this.Ka?this.A=(0,g.D)()+this.Jd:this.Ka=g.ag(this.C,this.Jd)};
g.k.stop=function(){this.Ka&&(g.v.clearTimeout(this.Ka),this.Ka=null);this.A=null;this.o=!1;this.B=[]};
g.k.pause=function(){++this.u};
g.k.resume=function(){this.u&&(--this.u,!this.u&&this.o&&(this.o=!1,this.F.apply(null,this.B)))};
g.k.X=function(){this.stop();v6.sc.X.call(this)};
g.k.KG=function(){this.A?(this.Ka=g.ag(this.C,this.A-(0,g.D)()),this.A=null):(this.Ka=null,this.u?this.o=!0:(this.o=!1,this.F.apply(null,this.B)))};g.t(w6,g.A);g.k=w6.prototype;g.k.wA=function(a){this.A=arguments;this.Ka||this.u?this.o=!0:x6(this)};
g.k.stop=function(){this.Ka&&(g.v.clearTimeout(this.Ka),this.Ka=null,this.o=!1,this.A=null)};
g.k.pause=function(){this.u++};
g.k.resume=function(){this.u--;this.u||!this.o||this.Ka||(this.o=!1,x6(this))};
g.k.X=function(){g.A.prototype.X.call(this);this.stop()};z6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
z6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};A6.prototype.o=null;A6.prototype.getOptions=function(){var a;(a=this.o)||(a={},Dza(this)&&(a[0]=!0,a[1]=!0),a=this.o=a);return a};var S8;g.Ua(Cza,A6);S8=new Cza;g.k=B6.prototype;g.k.Dj=null;g.k.Wf=!1;g.k.Yl=null;g.k.Uw=null;g.k.Ml=null;g.k.Rl=null;g.k.Sh=null;g.k.Ti=null;g.k.kk=null;g.k.bd=null;g.k.no=0;g.k.cg=null;g.k.hs=null;g.k.ji=null;g.k.Pm=-1;g.k.vD=!0;g.k.lj=!1;g.k.du=0;g.k.wr=null;var Iza={},E6={};g.k=B6.prototype;g.k.setTimeout=function(a){this.C=a};
g.k.zO=function(a){a=a.target;var b=this.wr;b&&3==S6(a)?b.wA():this.vE(a)};
g.k.vE=function(a){try{if(a==this.bd)a:{var b=S6(this.bd),c=this.bd.F,d=this.bd.getStatus();if(g.ne&&!g.Sd(10)||g.pe&&!g.Rd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Ch&&!U6(this.bd))break a;this.lj||4!=b||7==c||(8==c||0>=d?this.o.Of(3):this.o.Of(2));L6(this);var e=this.bd.getStatus();this.Pm=e;var f=U6(this.bd);(this.Wf=200==e)?(4==b&&H6(this),this.F?(Jza(this,b,f),g.Ch&&this.Wf&&3==b&&(this.B.na(this.u,"tick",this.tO),this.u.start())):G6(this,f),this.Wf&&!this.lj&&(4==b?this.o.Jp(this):(this.Wf=
!1,D6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.ji=3,F6(13)):(this.ji=0,F6(14)),H6(this),I6(this))}}catch(h){this.bd&&U6(this.bd)}finally{}};
g.k.tO=function(){var a=S6(this.bd),b=U6(this.bd);this.no<b.length&&(L6(this),Jza(this,a,b),this.Wf&&4!=a&&D6(this))};
g.k.RN=function(a){K6((0,g.x)(this.QN,this,a),0)};
g.k.QN=function(a){this.lj||(L6(this),G6(this,a),D6(this))};
g.k.zC=function(a){K6((0,g.x)(this.PN,this,a),0)};
g.k.PN=function(a){this.lj||(H6(this),this.Wf=a,this.o.Jp(this),this.o.Of(4))};
g.k.cancel=function(){this.lj=!0;H6(this)};
g.k.ZN=function(){this.Yl=null;var a=(0,g.D)();0<=a-this.Uw?(2!=this.Rl&&this.o.Of(3),H6(this),this.ji=2,F6(18),I6(this)):Mza(this,this.Uw-a)};
g.k.getLastError=function(){return this.ji};g.k=Pza.prototype;g.k.au=null;g.k.qe=null;g.k.xr=!1;g.k.Bz=null;g.k.mp=null;g.k.Eu=null;g.k.cu=null;g.k.Xe=null;g.k.oh=-1;g.k.Om=null;g.k.mm=null;g.k.connect=function(a){this.cu=a;a=N6(this.o,null,this.cu);F6(3);this.Bz=(0,g.D)();var b=this.o.I;null!=b?(this.Om=b[0],(this.mm=b[1])?(this.Xe=1,Qza(this)):(this.Xe=2,P6(this))):(b6(a,"MODE","init"),this.qe=new B6(this,void 0,void 0,void 0),this.qe.Dj=this.au,C6(this.qe,a,!1,null,!0),this.Xe=0)};
g.k.KF=function(a){if(a)this.Xe=2,P6(this);else{F6(4);var b=this.o;b.ng=b.Vh.oh;a7(b,9)}a&&this.Of(2)};
g.k.qt=function(a){return this.o.qt(a)};
g.k.abort=function(){this.qe&&(this.qe.cancel(),this.qe=null);this.oh=-1};
g.k.Az=function(){return!1};
g.k.rC=function(a,b){this.oh=a.Pm;if(0==this.Xe)if(b){try{var c=this.u.parse(b)}catch(d){c=this.o;c.ng=this.oh;a7(c,2);return}this.Om=c[0];this.mm=c[1]}else c=this.o,c.ng=this.oh,a7(c,2);else if(2==this.Xe)if(this.xr)F6(7),this.Eu=(0,g.D)();else if("11111"==b){if(F6(6),this.xr=!0,this.mp=(0,g.D)(),c=this.mp-this.Bz,!g.ne||g.Sd(10)||500>c)this.oh=200,this.qe.cancel(),F6(12),O6(this.o,this,!0)}else F6(8),this.mp=this.Eu=(0,g.D)(),this.xr=!1};
g.k.Jp=function(){this.oh=this.qe.Pm;if(this.qe.Wf)0==this.Xe?this.mm?(this.Xe=1,Qza(this)):(this.Xe=2,P6(this)):2==this.Xe&&((!g.ne||g.Sd(10)?!this.xr:200>this.Eu-this.mp)?(F6(11),O6(this.o,this,!1)):(F6(12),O6(this.o,this,!0)));else{0==this.Xe?F6(9):2==this.Xe&&F6(10);var a=this.o;this.qe.getLastError();a.ng=this.oh;a7(a,2)}};
g.k.Wn=function(){return this.o.Wn()};
g.k.isActive=function(){return this.o.isActive()};
g.k.Of=function(a){this.o.Of(a)};g.Ua(Q6,g.pf);var Vza=/^https?$/i,IBa=["POST","PUT"];g.k=Q6.prototype;
g.k.send=function(a,b,c,d){if(this.o)throw Error("[goog.net.XhrIo] Object is active with another request="+this.M+"; newUri="+a);b=b?b.toUpperCase():"GET";this.M=a;this.B="";this.F=0;this.ga=b;this.Z=!1;this.A=!0;this.o=this.U?Eza(this.U):Eza(S8);this.T=this.U?this.U.getOptions():S8.getOptions();this.o.onreadystatechange=(0,g.x)(this.nC,this);try{d6(T6(this,"Opening Xhr")),this.ba=!0,this.o.open(b,String(a),!0),this.ba=!1}catch(f){d6(T6(this,"Error opening Xhr: "+f.message));Uza(this,f);return}a=
c||"";var e=this.headers.clone();d&&dza(d,function(f,h){e.set(h,f)});
d=g.cb(e.Ve(),Sza);c=g.v.FormData&&a instanceof g.v.FormData;!g.fb(IBa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,h){this.o.setRequestHeader(h,f)},this);
this.ea&&(this.o.responseType=this.ea);"withCredentials"in this.o&&this.o.withCredentials!==this.aa&&(this.o.withCredentials=this.aa);try{Xza(this),0<this.G&&(this.R=Rza(this.o),d6(T6(this,"Will abort after "+this.G+"ms if incomplete, xhr2 "+this.R)),this.R?(this.o.timeout=this.G,this.o.ontimeout=(0,g.x)(this.Cz,this)):this.N=g.ag(this.Cz,this.G,this)),d6(T6(this,"Sending request")),this.I=!0,this.o.send(a),this.I=!1}catch(f){d6(T6(this,"Send error: "+f.message)),Uza(this,f)}};
g.k.Cz=function(){"undefined"!=typeof g.F1&&this.o&&(this.B="Timed out after "+this.G+"ms, aborting",this.F=8,T6(this,this.B),this.dispatchEvent("timeout"),this.abort(8))};
g.k.abort=function(a){this.o&&this.A&&(T6(this,"Aborting"),this.A=!1,this.C=!0,this.o.abort(),this.C=!1,this.F=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),R6(this))};
g.k.X=function(){this.o&&(this.A&&(this.A=!1,this.C=!0,this.o.abort(),this.C=!1),R6(this,!0));Q6.sc.X.call(this)};
g.k.nC=function(){this.ia()||(this.ba||this.I||this.C?Wza(this):this.YM())};
g.k.YM=function(){Wza(this)};
g.k.isActive=function(){return!!this.o};
g.k.getStatus=function(){try{return 2<S6(this)?this.o.status:-1}catch(a){return-1}};
g.k.getLastError=function(){return"string"===typeof this.B?this.B:String(this.B)};g.k=V6.prototype;g.k.Em=null;g.k.fe=null;g.k.Bc=null;g.k.Zt=null;g.k.qp=null;g.k.Zx=null;g.k.Ip=null;g.k.vn=0;g.k.AK=0;g.k.Gd=null;g.k.ai=null;g.k.Vg=null;g.k.rj=null;g.k.Vh=null;g.k.ds=null;g.k.pl=-1;g.k.hA=-1;g.k.ng=-1;g.k.Sk=0;g.k.Ek=0;g.k.mj=8;var b7=new g.pf;g.Ua(Zza,g.Oe);g.Ua($za,g.Oe);g.Ua(aAa,g.Oe);g.k=V6.prototype;g.k.connect=function(a,b,c,d,e){F6(0);this.Zt=b;this.Em=c||{};d&&void 0!==e&&(this.Em.OSID=d,this.Em.OAID=e);this.F?(K6((0,g.x)(this.sy,this,a),100),eAa(this)):this.sy(a)};
g.k.sy=function(a){this.Vh=new Pza(this);this.Vh.au=null;this.Vh.u=this.C;this.Vh.connect(a)};
g.k.Az=function(){return 0==this.o};
g.k.yC=function(a){this.ai=null;hAa(this,a)};
g.k.xC=function(){this.Vg=null;this.Bc=new B6(this,this.A,"rpc",this.G);this.Bc.Dj=null;this.Bc.du=0;var a=this.Zx.clone();$5(a,"RID","rpc");$5(a,"SID",this.A);$5(a,"CI",this.ds?"0":"1");$5(a,"AID",this.pl);W6(this,a);if(!g.ne||g.Sd(10))$5(a,"TYPE","xmlhttp"),C6(this.Bc,a,!0,this.Ip,!1);else{$5(a,"TYPE","html");var b=this.Bc,c=!!this.Ip;b.Rl=3;b.Sh=a6(a.clone());Lza(b,c)}};
g.k.rC=function(a,b){if(0!=this.o&&(this.Bc==a||this.fe==a))if(this.ng=a.Pm,this.fe==a&&3==this.o)if(7<this.mj){try{var c=this.C.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.Vg){if(this.Bc)if(this.Bc.Ml+3E3<this.fe.Ml)Y6(this),this.Bc.cancel(),this.Bc=null;else break a;$6(this);F6(19)}}else this.hA=c[1],0<this.hA-this.pl&&37500>c[2]&&this.ds&&0==this.Ek&&!this.rj&&(this.rj=K6((0,g.x)(this.bL,this),6E3));else a7(this,11)}else b!=HBa.RQ.o&&a7(this,11);else if(this.Bc==
a&&Y6(this),!g.kc(b)){c=this.C.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.pl=e[0];e=e[1];2==this.o?"c"==e[0]?(this.A=e[1],this.Ip=e[2],e=e[3],null!=e?this.mj=e:this.mj=6,this.o=3,this.Gd&&this.Gd.ny(),this.Zx=N6(this,this.Wn()?this.Ip:null,this.Zt),iAa(this)):"stop"==e[0]&&a7(this,7):3==this.o&&("stop"==e[0]?a7(this,7):"noop"!=e[0]&&this.Gd&&this.Gd.my(e),this.Ek=0)}}};
g.k.bL=function(){null!=this.rj&&(this.rj=null,this.Bc.cancel(),this.Bc=null,$6(this),F6(20))};
g.k.Jp=function(a){if(this.Bc==a){Y6(this);this.Bc=null;var b=2}else if(this.fe==a)this.fe=null,b=1;else return;this.ng=a.Pm;if(0!=this.o)if(a.Wf)1==b?(b=(0,g.D)()-a.Ml,b7.dispatchEvent(new $za(b7,a.kk?a.kk.length:0,b,this.Sk)),X6(this),this.B.length=0):iAa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.ng)){if(d=1==b)this.fe||this.ai||1==this.o||2<=this.Sk?d=!1:(this.ai=K6((0,g.x)(this.yC,this,a),jAa(this,this.Sk)),this.Sk++,d=!0);d=!(d||2==b&&$6(this))}if(d)switch(c){case 1:a7(this,
5);break;case 4:a7(this,10);break;case 3:a7(this,6);break;case 7:a7(this,12);break;default:a7(this,2)}}};
g.k.iG=function(a){if(!g.fb(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.k.kP=function(a){a?F6(2):(F6(1),kAa(this,8))};
g.k.qt=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new Q6;a.aa=!1;return a};
g.k.isActive=function(){return!!this.Gd&&this.Gd.isActive(this)};
g.k.Of=function(a){b7.dispatchEvent(new aAa(b7,a))};
g.k.Wn=function(){return!(!g.ne||g.Sd(10))};
g.k=lAa.prototype;g.k.ny=function(){};
g.k.my=function(){};
g.k.ly=function(){};
g.k.Ys=function(){};
g.k.Yy=function(){return{}};
g.k.isActive=function(){return!0};g.k=mAa.prototype;g.k.isEmpty=function(){return g.gb(this.o)&&g.gb(this.u)};
g.k.clear=function(){this.o=[];this.u=[]};
g.k.contains=function(a){return g.fb(this.o,a)||g.fb(this.u,a)};
g.k.remove=function(a){var b=this.o;var c=(0,g.Nta)(b,a);0<=c?(g.jb(b,c),b=!0):b=!1;return b||g.kb(this.u,a)};
g.k.Qd=function(){for(var a=[],b=this.o.length-1;0<=b;--b)a.push(this.o[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Ua(c7,g.A);g.k=c7.prototype;g.k.KN=function(){this.Jd=Math.min(3E5,2*this.Jd);this.A();this.u&&this.start()};
g.k.start=function(){var a=this.Jd+15E3*Math.random();this.o.eb(a);this.u=(0,g.D)()+a};
g.k.stop=function(){this.o.stop();this.u=0};
g.k.isActive=function(){return this.o.isActive()};
g.k.reset=function(){this.o.stop();this.Jd=5E3};g.Ua(d7,lAa);g.k=d7.prototype;g.k.subscribe=function(a,b,c){return this.A.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.A.unsubscribe(a,b,c)};
g.k.Ii=function(a){return this.A.Ej(a)};
g.k.S=function(a,b){return this.A.S.apply(this.A,arguments)};
g.k.dispose=function(){this.Mb||(this.Mb=!0,g.Me(this.A),pAa(this),g.Me(this.u),this.u=null)};
g.k.ia=function(){return this.Mb};
g.k.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.M="";this.u.stop();this.C=a||null;this.B=b||0;a=this.N+"/test";b=this.N+"/bind";var d=new V6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.R),e=this.o;e&&(e.Gd=null);d.Gd=this;this.o=d;e?this.o.connect(a,b,this.F,e.A,e.pl):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.k.sendMessage=function(a,b){var c={_sc:a};b&&g.Ub(c,b);this.u.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):e7(this)&&fAa(this.o,c)};
g.k.ny=function(){this.u.reset();this.C=null;this.B=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)fAa(this.o,a[b])}this.S("handlerOpened")};
g.k.ly=function(a){var b=2==a&&401==this.o.ng;4==a||b||this.u.start();this.S("handlerError",a)};
g.k.Ys=function(a){if(!this.u.isActive())this.S("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.k.Yy=function(){var a={v:2};this.M&&(a.gsessionid=this.M);0!=this.B&&(a.ui=""+this.B);0!=this.I&&(a.ui=""+this.I);this.C&&g.Ub(a,this.C);return a};
g.k.my=function(a){"S"==a[0]?this.M=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),dAa(this.o)):this.S("handlerMessage",new nAa(a[0],a[1]))};
g.k.NO=function(){this.u.isActive();var a=this.o,b=0;a.Bc&&b++;a.fe&&b++;0==b&&this.connect(this.C,this.B)};f7.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
f7.prototype.A=function(a,b){a(Error("Request error: "+b.status))};
f7.prototype.C=function(a){a(Error("request timed out"))};var xAa=(0,g.D)(),i7=null,l7=Array(50),k7=-1,m7=!1;g.Ua(n7,g.N);n7.prototype.Ee=function(){return this.screens};
n7.prototype.contains=function(a){return!!l6(this.screens,a)};
n7.prototype.get=function(a){return a?m6(this.screens,a):null};
n7.prototype.info=function(a){j7(this.F,a)};g.t(o7,g.N);g.k=o7.prototype;g.k.start=function(){!this.o&&isNaN(this.Ka)&&this.zE()};
g.k.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Ka)||(g.Oo(this.Ka),this.Ka=NaN)};
g.k.X=function(){this.stop();g.N.prototype.X.call(this)};
g.k.zE=function(){this.Ka=NaN;this.o=g.wq(g7(this.F,"/pairing/get_screen"),{method:"POST",Db:{pairing_code:this.B},timeout:5E3,onSuccess:(0,g.x)(this.KP,this),onError:(0,g.x)(this.JP,this),Ke:(0,g.x)(this.LP,this)})};
g.k.KP=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.C;c.name=this.A;this.S("pairingComplete",new g6(c))};
g.k.JP=function(a){this.o=null;a.status&&404==a.status?this.u>=JBa.length?this.S("pairingFailed",Error("DIAL polling timed out")):(a=JBa[this.u],this.Ka=g.Mo((0,g.x)(this.zE,this),a),this.u++):this.S("pairingFailed",Error("Server error "+a.status))};
g.k.LP=function(){this.o=null;this.S("pairingFailed",Error("Server not responding"))};
var JBa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ua(q7,n7);g.k=q7.prototype;g.k.start=function(){p7(this)&&this.S("screenChange");!g.Zs("yt-remote-lounge-token-expiration")&&BAa(this);g.Oo(this.o);this.o=g.Mo((0,g.x)(this.start,this),1E4)};
g.k.add=function(a,b){p7(this);yAa(this,a);r7(this,!1);this.S("screenChange");b(a);a.token||BAa(this)};
g.k.remove=function(a,b){var c=p7(this);AAa(this,a)&&(r7(this,!1),c=!0);b(a);c&&this.S("screenChange")};
g.k.Yr=function(a,b,c,d){var e=p7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,r7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.S("screenChange")};
g.k.X=function(){g.Oo(this.o);q7.sc.X.call(this)};
g.k.UG=function(a){p7(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}r7(this,!b);b&&j7(this.F,"Missed "+b+" lounge tokens.")};
g.k.TG=function(a){j7(this.F,"Requesting lounge tokens failed: "+a)};g.t(t7,g.N);g.k=t7.prototype;g.k.start=function(){var a=parseInt(g.Zs("yt-remote-fast-check-period")||"0",10);(this.B=(0,g.D)()-144E5<a?0:a)?v7(this):(this.B=(0,g.D)()+3E5,g.Ys("yt-remote-fast-check-period",this.B),this.Sv())};
g.k.isEmpty=function(){return g.Ob(this.o)};
g.k.update=function(){s7("Updating availability on schedule.");var a=this.F(),b=g.Bb(this.o,function(c,d){return c&&!!m6(a,d)},this);
u7(this,b)};
g.k.X=function(){g.Oo(this.A);this.A=NaN;this.u&&(this.u.abort(),this.u=null);g.N.prototype.X.call(this)};
g.k.Sv=function(){g.Oo(this.A);this.A=NaN;this.u&&this.u.abort();var a=EAa(this);if(c6(a)){var b=g7(this.C,"/pairing/get_screen_availability");this.u=h7(this.C,b,{lounge_token:g.Hb(a).join(",")},(0,g.x)(this.uN,this,a),(0,g.x)(this.tN,this))}else u7(this,{}),v7(this)};
g.k.uN=function(a,b){this.u=null;var c=g.Hb(EAa(this));if(g.xb(c,g.Hb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;u7(this,d);v7(this)}else this.oc("Changing Screen set during request."),this.Sv()};
g.k.tN=function(a){this.oc("Screen availability failed: "+a);this.u=null;v7(this)};
g.k.oc=function(a){j7("OnlineScreenService",a)};g.Ua(w7,n7);g.k=w7.prototype;g.k.start=function(){this.u.start();this.o.start();this.screens.length&&(this.S("screenChange"),this.o.isEmpty()||this.S("onlineScreenChange"))};
g.k.add=function(a,b,c){this.u.add(a,b,c)};
g.k.remove=function(a,b,c){this.u.remove(a,b,c);this.o.update()};
g.k.Yr=function(a,b,c,d){this.u.contains(a)?this.u.Yr(a,b,c,d):(a="Updating name of unknown screen: "+a.name,j7(this.F,a),d(Error(a)))};
g.k.Ee=function(a){return a?this.screens:g.nb(this.screens,(0,g.Ae)(this.A,function(b){return!this.contains(b)},this))};
g.k.AE=function(){return(0,g.Ae)(this.Ee(!0),function(a){return!!this.o.o[a.id]},this)};
g.k.BE=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new o7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(h){g.Me(f);d(x7(this,h))},this));
f.subscribe("pairingFailed",function(h){g.Me(f);e(h)});
f.start();return(0,g.x)(f.stop,f)};
g.k.NP=function(a,b,c,d){g.wq(g7(this.C,"/pairing/get_screen"),{method:"POST",Db:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var h=new g6(f.screen||{});if(!h.name||IAa(this,h.name)){a:{var l=h.name;for(var m=2,n=b(l,m);IAa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}h.name=l}c(x7(this,h))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
Ke:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.k.X=function(){g.Me(this.u);g.Me(this.o);w7.sc.X.call(this)};
g.k.bH=function(){JAa(this);this.S("screenChange");this.o.update()};
w7.prototype.dispose=w7.prototype.dispose;g.Ua(z7,g.N);g.k=z7.prototype;g.k.getScreen=function(){return this.I};
g.k.ir=function(a){this.I=a;this.S("sessionScreen",this.I)};
g.k.Je=function(a){this.ia()||(a&&A7(this,""+a),this.I=null,this.S("sessionScreen",null))};
g.k.info=function(a){j7(this.T,a)};
g.k.DE=function(){return null};
g.k.dw=function(a){var b=this.o;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){A7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.X=function(){this.dw("");z7.sc.X.call(this)};g.t(B7,z7);g.k=B7.prototype;g.k.cw=function(a){if(this.u){if(this.u==a)return;A7(this,"Overriding cast sesison with new session object");this.u.removeUpdateListener(this.C);this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.u=a;this.u.addUpdateListener(this.C);this.u.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);LAa(this)};
g.k.ql=function(a){this.info("launchWithParams no-op for Cast: "+g.Nk(a))};
g.k.stop=function(){this.u?this.u.stop((0,g.x)(function(){this.Je()},this),(0,g.x)(function(){this.Je(Error("Failed to stop receiver app."))},this)):this.Je(Error("Stopping cast device witout session."))};
g.k.dw=function(){};
g.k.X=function(){this.info("disposeInternal");g.Oo(this.A);this.A=0;this.u&&(this.u.removeUpdateListener(this.C),this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.u=null;z7.prototype.X.call(this)};
g.k.gO=function(a,b){if(!this.ia())if(b){var c=y6(b);if(g.Pa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Nk(c));switch(d){case "mdxSessionStatus":KAa(this,c.screenId);break;default:A7(this,"Unknown youtube message: "+d)}}else A7(this,"Unable to parse message.")}else A7(this,"No data in message.")};
g.k.sz=function(a,b,c,d){HAa(this.M,this.o.label,a,this.o.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(A7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Mo((0,g.x)(this.sz,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.DE=function(){return this.u};
g.k.OP=function(a){this.ia()||a||(A7(this,"Cast session died."),this.Je())};g.t(C7,z7);g.k=C7.prototype;g.k.cw=function(a){this.A=a;this.A.addUpdateListener(this.R)};
g.k.ql=function(a){this.B=a;this.F()};
g.k.stop=function(){this.u();this.u=g.Ka;g.Oo(this.C);this.A?this.A.stop((0,g.x)(this.Je,this,null),(0,g.x)(this.Je,this,"Failed to stop DIAL device.")):this.Je()};
g.k.X=function(){this.u();this.u=g.Ka;g.Oo(this.C);this.A&&this.A.removeUpdateListener(this.R);this.A=null;z7.prototype.X.call(this)};
g.k.RP=function(a){this.ia()||a||(A7(this,"DIAL session died."),this.u(),this.u=g.Ka,this.Je())};
g.k.ou=function(a){this.N=k6();if(this.B){var b=new chrome.cast.DialLaunchResponse(!0,NAa(this));a(b);MAa(this)}else this.F=(0,g.x)(function(){g.Oo(this.C);this.F=g.Ka;this.C=NaN;var c=new chrome.cast.DialLaunchResponse(!0,NAa(this));a(c);MAa(this)},this),this.C=g.Mo((0,g.x)(function(){this.F()},this),100)};
g.k.sH=function(a,b,c){HAa(this.M,this.G.receiver.label,a,this.o.friendlyName,(0,g.x)(function(d){d&&d.token?(this.ir(d),b(new chrome.cast.DialLaunchResponse(!1))):this.ou(b,c)},this),(0,g.x)(function(d){A7(this,"Failed to get DIAL screen: "+d);
this.ou(b,c)},this))};g.t(D7,z7);D7.prototype.stop=function(){this.Je()};
D7.prototype.cw=function(){};
D7.prototype.ql=function(){g.Oo(this.u);this.u=NaN;var a=m6(this.M.Ee(),this.o.label);a?this.ir(a):this.Je(Error("No such screen"))};
D7.prototype.X=function(){g.Oo(this.u);this.u=NaN;z7.prototype.X.call(this)};g.t(E7,g.N);g.k=E7.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.G);this.I||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.dN,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.uC,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.xL,this);chrome.cast.initialize(c,(0,g.x)(function(){this.ia()||
(chrome.cast.addReceiverActionListener(this.B),uAa(),this.u.subscribe("onlineScreenChange",(0,g.x)(this.CE,this)),this.A=PAa(this),chrome.cast.setCustomReceivers(this.A,g.Ka,(0,g.x)(function(h){this.oc("Failed to set initial custom receivers: "+g.Nk(h))},this)),this.S("yt-remote-cast2-availability-change",G7(this)),b(!0))},this),(0,g.x)(function(h){this.oc("Failed to initialize API: "+g.Nk(h));
b(!1)},this))};
g.k.UO=function(a,b){F7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.getScreen();if(!a||c&&c.id!=a)F7("Unsetting old screen status: "+this.o.o.friendlyName),H7(this,null)}if(a&&b){if(!this.o){c=m6(this.u.Ee(),a);if(!c){F7("setConnectedScreenStatus: Unknown screen.");return}var d=OAa(this,c);d||(F7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.A.push(d),chrome.cast.setCustomReceivers(this.A,
g.Ka,(0,g.x)(function(e){this.oc("Failed to set initial custom receivers: "+g.Nk(e))},this)));
F7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);H7(this,new D7(this.u,d),!0)}this.o.dw(b)}else F7("setConnectedScreenStatus: no screen.")};
g.k.VO=function(a){this.ia()?this.oc("Setting connection data on disposed cast v2"):this.o?this.o.ql(a):this.oc("Setting connection data without a session")};
g.k.QP=function(){this.ia()?this.oc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),H7(this,null)):F7("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.uC,this),(0,g.x)(this.xN,this))};
g.k.X=function(){this.u.unsubscribe("onlineScreenChange",(0,g.x)(this.CE,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.B);var a=rAa,b=g.Ja("yt.mdx.remote.debug.handlers_");g.kb(b||[],a);g.Me(this.o);g.N.prototype.X.call(this)};
g.k.oc=function(a){j7("Controller",a)};
g.k.wC=function(a,b){this.o==a&&(b||H7(this,null),this.S("yt-remote-cast2-session-change",b))};
g.k.ZM=function(a,b){if(!this.ia())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),F7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.o.label!=a.label)F7("onReceiverAction_: Stopping active receiver: "+this.o.o.friendlyName),this.o.stop();else{F7("onReceiverAction_: Casting to active receiver.");this.o.getScreen()&&this.S("yt-remote-cast2-session-change",this.o.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:H7(this,
new D7(this.u,a));break;case chrome.cast.ReceiverType.DIAL:H7(this,new C7(this.u,a,this.F));break;case chrome.cast.ReceiverType.CAST:H7(this,new B7(this.u,a));break;default:this.oc("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.o.label==a.label?this.o.stop():this.oc("Stopping receiver w/o session: "+a.friendlyName)}else this.oc("onReceiverAction_ called without receiver.")};
g.k.xL=function(a){if(this.ia())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.oc("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.o:null;if(!c||c.label!=b.label)return this.oc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.getScreen())return F7("Reselecting dial screen."),
this.S("yt-remote-cast2-session-change",this.o.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.oc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);H7(this,new C7(this.u,b,this.F))}b=this.o;b.G=a;return b.G.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.sH,b,(b.G.extraData||{}).screenId||null)):new Promise((0,g.x)(b.ou,b))};
g.k.uC=function(a){if(!this.ia()){F7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)F7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),H7(this,new B7(this.u,b),!0);else{this.oc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.o,d=m6(this.u.Ee(),c.label);d&&h6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(F7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Me(this.o),this.o=new B7(this.u,b),this.o.subscribe("sessionScreen",(0,g.x)(this.wC,this,this.o)),this.o.ql(null));this.o.cw(a)}}};
g.k.PP=function(){return this.o?this.o.DE():null};
g.k.xN=function(a){this.ia()||(this.oc("Failed to estabilish a session: "+g.Nk(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&H7(this,null))};
g.k.dN=function(a){F7("Receiver availability updated: "+a);if(!this.ia()){var b=G7(this);this.C=a==chrome.cast.ReceiverAvailability.AVAILABLE;G7(this)!=b&&this.S("yt-remote-cast2-availability-change",G7(this))}};
g.k.CE=function(){this.ia()||(this.A=PAa(this),F7("Updating custom receivers: "+g.Nk(this.A)),chrome.cast.setCustomReceivers(this.A,g.Ka,(0,g.x)(function(){this.oc("Failed to set custom receivers.")},this)),this.S("yt-remote-cast2-availability-change",G7(this)))};
E7.prototype.setLaunchParams=E7.prototype.VO;E7.prototype.setConnectedScreenStatus=E7.prototype.UO;E7.prototype.stopSession=E7.prototype.QP;E7.prototype.getCastSession=E7.prototype.PP;E7.prototype.requestSession=E7.prototype.requestSession;E7.prototype.init=E7.prototype.init;E7.prototype.dispose=E7.prototype.dispose;var N7=[];g.k=S7.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";T7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.og=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.F=a.playerTimeAt,this.C=a.seekableStart,this.u=a.seekableEnd,this.I=a.duration,this.M=a.loadedTime,this.B=a.liveIngestionTime,this.A=!isNaN(this.B))};
g.k.qb=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.getDuration=function(){return this.A?this.I+U7(this):this.I};
g.k.clone=function(){return new S7(Y7(this))};g.t($7,g.N);g.k=$7.prototype;g.k.play=function(){1==this.o?(this.u?this.u.play(null,g.Ka,f8(this,"play")):e8(this,"play"),d8(this,1,W7(a8(this))),this.S("remotePlayerChange")):b8(this,this.play)};
g.k.pause=function(){1==this.o?(this.u?this.u.pause(null,g.Ka,f8(this,"pause")):e8(this,"pause"),d8(this,2,W7(a8(this))),this.S("remotePlayerChange")):b8(this,this.pause)};
g.k.seekTo=function(a){if(1==this.o){if(this.u){var b=a8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.qb()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.Ka,f8(this,"seekTo",{newTime:a}))}else e8(this,"seekTo",{newTime:a});d8(this,3,a);this.S("remotePlayerChange")}else b8(this,g.Sa(this.seekTo,a))};
g.k.stop=function(){if(1==this.o){this.u?this.u.stop(null,g.Ka,f8(this,"stopVideo")):e8(this,"stopVideo");var a=a8(this);a.index=-1;a.videoId="";T7(a);c8(this,a);this.S("remotePlayerChange")}else b8(this,this.stop)};
g.k.setVolume=function(a,b){if(1==this.o){var c=a8(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.x)(function(){j7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.oc("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.x)(function(){j7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.oc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);e8(this,"setVolume",e)}c.muted=b;c.volume=a;c8(this,c)}else b8(this,g.Sa(this.setVolume,a,b))};
g.k.yE=function(a,b){if(1==this.o){var c=a8(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Nk(b.style),g.Ub(d,c.o));e8(this,"setSubtitlesTrack",d);c8(this,c)}else b8(this,g.Sa(this.yE,a,b))};
g.k.setAudioTrack=function(a,b){if(1==this.o){var c=b.getLanguageInfo().getId();e8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=a8(this);d.audioTrackId=c;c8(this,d)}else b8(this,g.Sa(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){var l=a8(this);c=c||0;var m={videoId:a,currentIndex:c};X7(l,a,c);void 0!==b&&(V7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=h&&(m.locationInfo=g.Nk(h));e8(this,"setPlaylist",m);d||c8(this,l)};
g.k.sr=function(a,b){if(1==this.o){if(a&&b){var c=a8(this);X7(c,a,b);c8(this,c)}e8(this,"previous")}else b8(this,g.Sa(this.sr,a,b))};
g.k.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=a8(this);X7(c,a,b);c8(this,c)}e8(this,"next")}else b8(this,g.Sa(this.nextVideo,a,b))};
g.k.Hy=function(){1==this.o?e8(this,"dismissAutoplay"):b8(this,this.Hy)};
g.k.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.S("proxyStateChange",a,this.o)}g.N.prototype.dispose.call(this)};
g.k.X=function(){bBa(this);this.B=null;this.C.clear();Z7(this,null);g.N.prototype.X.call(this)};
g.k.Xw=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.S("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)b=a=this.C,g.gb(b.o)&&(b.o=b.u,b.o.reverse(),b.u=[]),a.o.pop().apply(this);else 3==a&&this.dispose()}};
g.k.WM=function(a,b){this.S(a,b)};
g.k.hL=function(a){if(!a)this.yn(null),Z7(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=a8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)j7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,c8(this,b)}};
g.k.yn=function(a){j7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.I);if(this.u=a)this.u.addUpdateListener(this.I),cBa(this),this.S("remotePlayerChange")};
g.k.gL=function(a){a?(cBa(this),this.S("remotePlayerChange")):this.yn(null)};
g.k.zw=function(){e8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.qL=function(){var a=ZAa();a&&Z7(this,a)};
g.k.oc=function(a){j7("CP",a)};g.t(g8,g.N);g.k=g8.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,h=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==h&&(l.currentIndex=h);c&&(this.fb.listId=c);this.fb.videoId=d;this.fb.index=h||0;this.fb.state=3;V7(this.fb,m);this.B="UNSUPPORTED";h8("Connecting with setPlaylist and params: "+g.Nk(l));this.o.connect({method:"setPlaylist",
params:g.Nk(l)},a,pza())}else h8("Connecting without params"),this.o.connect({},a,pza());eBa(this)};
g.k.dispose=function(){this.ia()||(this.S("beforeDispose"),i8(this,3));g.N.prototype.dispose.call(this)};
g.k.X=function(){j8(this);l8(this);k8(this);g.Oo(this.G);this.G=NaN;g.Oo(this.I);this.I=NaN;this.A=null;g.jp(this.T);this.T.length=0;this.o.dispose();g.N.prototype.X.call(this);this.B=this.F=this.u=this.fb=this.o=null};
g.k.MG=function(){this.Nk(2)};
g.k.lL=function(){h8("Channel opened");this.R&&(this.R=!1,k8(this),this.N=g.Mo((0,g.x)(function(){h8("Timing out waiting for a screen.");this.Nk(1)},this),15E3));
tza(oAa(this.o),this.U)};
g.k.iL=function(){h8("Channel closed");isNaN(this.C)?r6(!0):r6();this.dispose()};
g.k.jL=function(a){r6();isNaN(this.Km())?(h8("Channel error: "+a+" without reconnection"),this.dispose()):(this.R=!0,h8("Channel error: "+a+" with reconnection in "+this.Km()+" ms"),i8(this,2))};
g.k.kL=function(a){a.params?h8("Received: action="+a.action+", params="+g.Nk(a.params)):h8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=y6(a.params.devices);this.u=(0,g.Ic)(a,function(c){return new f6(c)});
a=!!g.cb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
hBa(this,a);break;case "loungeScreenDisconnected":g.lb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
hBa(this,!1);break;case "remoteConnected":var b=new f6(y6(a.params.device));g.cb(this.u,function(c){return b?c.id==b.id:!1})||$ya(this.u,b);
break;case "remoteDisconnected":b=new f6(y6(a.params.device));g.lb(this.u,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":jBa(this,a);break;case "nowPlaying":lBa(this,a);break;case "onStateChange":kBa(this,a);break;case "onAdStateChange":mBa(this,a);break;case "onVolumeChanged":nBa(this,a);break;case "onSubtitlesTrackChanged":iBa(this,a);break;case "nowAutoplaying":oBa(this,a);break;case "autoplayDismissed":this.S("autoplayDismissed");break;case "autoplayUpNext":this.F=a.params.videoId||null;this.S("autoplayUpNext",this.F);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.S("autoplayModeChange",this.B);"DISABLED"==this.B&&this.S("autoplayDismissed");break;case "onHasPreviousNextChanged":pBa(this,a);break;case "requestAssistedSignIn":this.S("assistedSignInRequested",a.params.authCode);break;default:h8("Unrecognized action: "+a.action)}};
g.k.JO=function(){if(this.A){var a=this.A;this.A=null;this.fb.videoId!=a&&m8(this,"getNowPlaying")}};
g.k.DG=function(){var a=3;this.ia()||(a=0,isNaN(this.Km())?e7(this.o)&&isNaN(this.C)&&(a=1):a=2);return a};
g.k.Nk=function(a){h8("Disconnecting with "+a);j8(this);this.S("beforeDisconnect",a);1==a&&r6();pAa(this.o,a);this.dispose()};
g.k.BG=function(){var a=this.fb;this.A&&(a=this.fb.clone(),X7(a,this.A,a.index));return Y7(a)};
g.k.WO=function(a){var b=new S7(a);b.videoId&&b.videoId!=this.fb.videoId&&(this.A=b.videoId,g.Oo(this.G),this.G=g.Mo((0,g.x)(this.JO,this),5E3));var c=[];this.fb.listId==b.listId&&this.fb.videoId==b.videoId&&this.fb.index==b.index||c.push("remoteQueueChange");this.fb.playerState==b.playerState&&this.fb.volume==b.volume&&this.fb.muted==b.muted&&W7(this.fb)==W7(b)&&g.Nk(this.fb.o)==g.Nk(b.o)||c.push("remotePlayerChange");this.fb.reset(a);(0,g.y)(c,function(d){this.S(d)},this)};
g.k.qz=function(){var a=this.o.F.id,b=g.cb(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.Km=function(){var a=this.o;return a.u.isActive()?a.u.u-(0,g.D)():NaN};
g.k.qG=function(){return this.B||"UNSUPPORTED"};
g.k.rG=function(){return this.F||""};
g.k.IP=function(){if(!isNaN(this.Km())){var a=this.o.u;g.An(a.o);a.start()}};
g.k.RO=function(a,b){m8(this,a,b);gBa(this)};
g8.prototype.subscribe=g8.prototype.subscribe;g8.prototype.unsubscribeByKey=g8.prototype.Ii;g8.prototype.getProxyState=g8.prototype.DG;g8.prototype.disconnect=g8.prototype.Nk;g8.prototype.getPlayerContextData=g8.prototype.BG;g8.prototype.setPlayerContextData=g8.prototype.WO;g8.prototype.getOtherConnectedRemoteId=g8.prototype.qz;g8.prototype.getReconnectTimeout=g8.prototype.Km;g8.prototype.getAutoplayMode=g8.prototype.qG;g8.prototype.getAutoplayVideoId=g8.prototype.rG;g8.prototype.reconnect=g8.prototype.IP;
g8.prototype.sendMessage=g8.prototype.RO;g.t(n8,n7);g.k=n8.prototype;g.k.Ee=function(a){return this.Id.$_gs(a)};
g.k.contains=function(a){return!!this.Id.$_c(a)};
g.k.get=function(a){return this.Id.$_g(a)};
g.k.start=function(){this.Id.$_st()};
g.k.add=function(a,b,c){this.Id.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Id.$_r(a,b,c)};
g.k.Yr=function(a,b,c,d){this.Id.$_un(a,b,c,d)};
g.k.X=function(){for(var a=0,b=this.o.length;a<b;++a)this.Id.$_ubk(this.o[a]);this.o.length=0;this.Id=null;n7.prototype.X.call(this)};
g.k.MP=function(){this.S("screenChange")};
g.k.zM=function(){this.S("onlineScreenChange")};
w7.prototype.$_st=w7.prototype.start;w7.prototype.$_gspc=w7.prototype.NP;w7.prototype.$_gsppc=w7.prototype.BE;w7.prototype.$_c=w7.prototype.contains;w7.prototype.$_g=w7.prototype.get;w7.prototype.$_a=w7.prototype.add;w7.prototype.$_un=w7.prototype.Yr;w7.prototype.$_r=w7.prototype.remove;w7.prototype.$_gs=w7.prototype.Ee;w7.prototype.$_gos=w7.prototype.AE;w7.prototype.$_s=w7.prototype.subscribe;w7.prototype.$_ubk=w7.prototype.Ii;var G8=null,F8=!1,o8=null,p8=null,E8=null,t8=[];g.t(H8,g.A);g.k=H8.prototype;g.k.X=function(){g.A.prototype.X.call(this);this.o.stop();this.u.stop();this.G.stop();this.N();var a=this.Ya;a.unsubscribe("proxyStateChange",this.qC,this);a.unsubscribe("remotePlayerChange",this.En,this);a.unsubscribe("remoteQueueChange",this.jr,this);a.unsubscribe("previousNextChange",this.mC,this);a.unsubscribe("nowAutoplaying",this.iC,this);a.unsubscribe("autoplayDismissed",this.IB,this);this.Ya=this.module=null};
g.k.NA=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.Ya.o)if(I8(this)){if(!a8(this.Ya).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":a8(this.Ya).qb()?this.Ya.pause():this.Ya.play();break;case "control_play":this.Ya.play();break;case "control_pause":this.Ya.pause();break;case "control_seek":this.F.wA(c[0],c[1]);break;case "control_subtitles_set_track":J8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.H.getCurrentTime();K8(this,0===c?void 0:c);break;case "control_seek":K8(this,c[0]);break;case "control_subtitles_set_track":J8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.fL=function(a){this.G.JG(a)};
g.k.sP=function(a){this.NA("control_subtitles_set_track",g.Ob(a)?null:a)};
g.k.ID=function(){var a=this.H.getOption("captions","track");g.Ob(a)||J8(this,a)};
g.k.Vb=function(a){this.module.Vb(a,this.H.getVideoData().lengthSeconds)};
g.k.XB=function(a){if(I8(this)){this.Ya.unsubscribe("remotePlayerChange",this.En,this);var b=Math.round(a.volume);a=!!a.muted;var c=a8(this.Ya);if(b!==c.volume||a!==c.muted)this.Ya.setVolume(b,a),this.I.start();this.Ya.subscribe("remotePlayerChange",this.En,this)}};
g.k.ZL=function(){g.Ob(this.A)||BBa(this,this.A);this.B=!1};
g.k.qC=function(a,b){this.u.stop();2===b&&this.GD()};
g.k.En=function(){if(I8(this)){this.o.stop();var a=a8(this.Ya);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.module.jd=1;break;case 1082:case 1083:this.module.jd=0;break;default:this.module.jd=-1}switch(a.playerState){case 1081:case 1:this.Nc(new g.cH(8));this.FD();break;case 1085:case 3:this.Nc(new g.cH(9));break;case 1083:case 0:this.Nc(new g.cH(2));this.F.stop();this.Vb(this.H.getVideoData().lengthSeconds);break;case 1084:this.Nc(new g.cH(4));break;case 2:this.Nc(new g.cH(4));
this.Vb(W7(a));break;case -1:this.Nc(new g.cH(64));break;case -1E3:this.Nc(new g.cH(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=a8(this.Ya).o;var b=this.A;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.A=a,BBa(this,a));a=a8(this.Ya);-1===a.volume||Math.round(this.H.getVolume())===a.volume&&this.H.isMuted()===a.muted||this.I.isActive()||this.lE()}else ABa(this)};
g.k.mC=function(){this.H.S("mdxpreviousnextchange")};
g.k.jr=function(){I8(this)||ABa(this)};
g.k.iC=function(a){isNaN(a)||this.H.S("mdxnowautoplaying",a)};
g.k.IB=function(){this.H.S("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){I8(this)&&this.Ya.setAudioTrack(this.H.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===a8(this.Ya).playerState?K8(this,a):b&&this.Ya.seekTo(a)};
g.k.lE=function(){if(I8(this)){var a=a8(this.Ya);this.events.nb(this.M);a.muted?this.H.mute():this.H.unMute();this.H.setVolume(a.volume);this.M=this.events.L(this.H,"onVolumeChange",this.XB)}};
g.k.FD=function(){this.o.stop();if(!this.Ya.ia()){var a=a8(this.Ya);a.qb()&&this.Nc(new g.cH(8));this.Vb(W7(a));this.o.start()}};
g.k.GD=function(){this.u.stop();this.o.stop();var a=this.Ya.B.getReconnectTimeout();2==this.Ya.o&&!isNaN(a)&&this.u.start()};
g.k.Nc=function(a){this.u.stop();var b=this.C;if(!g.hH(b,a)){var c=g.T(a,2);c!==g.T(this.C,2)&&g.LT(this.H.app,c);this.C=a;DBa(this.module,b,a)}};g.t(L8,g.U);L8.prototype.Wb=function(){this.o.show()};
L8.prototype.Ra=function(){this.o.hide()};
L8.prototype.u=function(){g.jO("https://support.google.com/youtube/answer/7640706")};
L8.prototype.A=function(){e6("mdx-manual-pairing-popup-ok");this.Ra()};g.t(M8,g.U);M8.prototype.Wb=function(){this.o.show()};
M8.prototype.Ra=function(){this.o.hide()};
M8.prototype.u=function(){e6("mdx-privacy-popup-cancel");this.Ra()};
M8.prototype.A=function(){e6("mdx-privacy-popup-confirm");this.Ra()};g.t(N8,g.U);N8.prototype.u=function(a){CBa(this,a.state)};g.t(O8,g.wR);O8.prototype.B=function(){var a=this.H.getOption("remote","receivers");a&&1<a.length&&!this.H.getOption("remote","quickCast")?(this.Si=g.zb(a,this.o,this),g.yR(this,(0,g.Ic)(a,this.o)),a=this.H.getOption("remote","currentReceiver"),this.Kb(this.o(a)),this.enable(!0)):this.enable(!1)};
O8.prototype.o=function(a){return a.key};
O8.prototype.Mf=function(a){return"cast-selector-receiver"===a?"Cast...":this.Si[a].name};
O8.prototype.td=function(a){g.wR.prototype.td.call(this,a);this.H.setOption("remote","currentReceiver",this.Si[a]);this.Ma.Ra()};g.t(P8,g.IN);g.k=P8.prototype;
g.k.create=function(){uBa(g.yy(this.player.O()));this.subscriptions.push(g.To("yt-remote-before-disconnect",this.dL,this));this.subscriptions.push(g.To("yt-remote-connection-change",this.eN,this));this.subscriptions.push(g.To("yt-remote-receiver-availability-change",this.oC,this));this.subscriptions.push(g.To("yt-remote-auto-connect",this.cN,this));this.subscriptions.push(g.To("yt-remote-receiver-resumed",this.bN,this));this.subscriptions.push(g.To("mdx-privacy-popup-confirm",this.xO,this));this.subscriptions.push(g.To("mdx-privacy-popup-cancel",
this.wO,this));this.subscriptions.push(g.To("mdx-manual-pairing-popup-ok",this.MH,this));this.oC()};
g.k.load=function(){this.player.cancelPlayback();g.IN.prototype.load.call(this);this.Ae=new H8(this,this.player,this.Ya);var a=(a=zBa())?a.currentTime:0;var b=D8()?new $7(y8(),void 0):null;0==a&&b&&(a=W7(a8(b)));0!==a&&this.Vb(a);DBa(this,this.Rb,this.Rb);g.ST(this.player.app,6)};
g.k.unload=function(){this.player.S("mdxautoplaycanceled");this.Xh=this.Jf;g.Ne(this.Ae,this.Ya);this.Ya=this.Ae=null;g.IN.prototype.unload.call(this);g.ST(this.player.app,5);Q8(this)};
g.k.X=function(){g.Uo(this.subscriptions);g.IN.prototype.X.call(this)};
g.k.Cg=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.Ae.NA.apply(this.Ae,[a].concat(g.la(c)))};
g.k.getAdState=function(){return this.jd};
g.k.FG=function(){return this.loaded?this.Ae.suggestion:null};
g.k.og=function(){return this.Ya?a8(this.Ya).og:!1};
g.k.hasNext=function(){return this.Ya?a8(this.Ya).hasNext:!1};
g.k.Vb=function(a,b){this.iA=a||0;this.player.S("progresssync",a,b)};
g.k.getCurrentTime=function(){return this.iA};
g.k.getProgressState=function(){var a=a8(this.Ya),b=this.player.getVideoData();return{allowSeeking:g.P(this.player.O().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.hd():!a.isAdPlaying()&&this.player.hd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.A?a.B+U7(a):a.B,isAtLiveHead:1>=(a.A?a.u+U7(a):a.u)-this.getCurrentTime(),loaded:a.M,seekableEnd:a.A?a.u+U7(a):a.u,seekableStart:0<a.C?a.C+
U7(a):a.C}};
g.k.nextVideo=function(){this.Ya&&this.Ya.nextVideo()};
g.k.sr=function(){this.Ya&&this.Ya.sr()};
g.k.dL=function(a){1===a&&(this.Ev=this.Ya?a8(this.Ya):null)};
g.k.eN=function(){var a=D8()?new $7(y8(),void 0):null;if(a){var b=this.Xh;this.loaded&&this.unload();this.Ya=a;this.Ev=null;b.key!==this.Jf.key&&(this.Xh=b,this.load())}else g.Me(this.Ya),this.Ya=null,this.loaded&&(this.unload(),(a=this.Ev)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,W7(a)));this.player.S("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.oC=function(){this.Si=[this.Jf].concat(wBa());var a=z8()||this.Jf;R8(this,a);this.player.ra("onMdxReceiversChange")};
g.k.cN=function(){var a=z8();R8(this,a)};
g.k.bN=function(){this.Xh=z8()};
g.k.xO=function(){this.Fn=!0;Q8(this);F8=!1;G8&&B8(G8,1);G8=null};
g.k.wO=function(){this.Fn=!1;Q8(this);R8(this,this.Jf);this.Xh=this.Jf;F8=!1;G8=null;this.player.playVideo()};
g.k.MH=function(){this.kq=!0;Q8(this);g.Ys("yt-remote-manual-pairing-warning-shown",!0,2592E3);F8=!1;G8&&B8(G8,1);G8=null};
g.k.cd=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Si;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?Q7():R8(this,b)),this.loaded?this.Xh:this.Jf;case "quickCast":return 2===this.Si.length&&"cast-selector-receiver"===this.Si[1].key?(b&&Q7(),!0):!1}};
g.k.zw=function(){this.Ya.zw()};
g.k.Vf=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.TN.remote=P8;})(_yt_player);
