(function(g){var window=this;var cAa=function(a,b){return g.Ob(a,b)},$5=function(a,b,c){a.A.set(b,c)},a6=function(a){$5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.E)()).toString(36));
return a},b6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.ln(a.A,b,c)},dAa=function(a,b){var c=[];
g.qk(b,function(d){try{var e=g.ko.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.jo(e)&&c.push(d)},a);
return c},eAa=function(a,b){var c=dAa(a,b);
(0,g.y)(c,function(d){g.ko.prototype.remove.call(this,d)},a)},fAa=function(a){if(a.fd){if(a.fd.locationOverrideToken)return{locationOverrideToken:a.fd.locationOverrideToken};
if(null!=a.fd.latitudeE7&&null!=a.fd.longitudeE7)return{latitudeE7:a.fd.latitudeE7,longitudeE7:a.fd.longitudeE7}}return null},gAa=function(a,b){g.fb(a,b)||a.push(b)},c6=function(a){var b=0,c;
for(c in a)b++;return b},hAa=function(a,b){var c=b instanceof g.Ac?b:g.Gc(b,/^data:image\//i.test(b));
a.src=g.Bc(c)},d6=function(){},iAa=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},jAa=function(a){if(a.Yd&&"function"==typeof a.Yd)return a.Yd();
if("string"===typeof a)return a.split("");if(g.Na(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Kb(a)},kAa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Na(a)||"string"===typeof a)(0,g.y)(a,b,void 0);else{if(a.hf&&"function"==typeof a.hf)var c=a.hf();else if(a.Yd&&"function"==typeof a.Yd)c=void 0;else if(g.Na(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Lb(a);d=jAa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},lAa=function(a,b,c,d){var e=new g.Zm(null,void 0);
a&&g.$m(e,a);b&&g.an(e,b);c&&g.bn(e,c);d&&(e.u=d);return e},e6=function(a,b){g.Ro[a]=!0;
var c=g.Po();c&&c.publish.apply(c,arguments);g.Ro[a]=!1},f6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Wm;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",mAa(this,a.capabilities||""),nAa(this,a.experiments||""))},mAa=function(a,b){a.capabilities.clear();
(0,g.De)(b.split(","),g.Sa(cAa,oAa)).forEach(function(c){a.capabilities.add(c)})},nAa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},g6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},h6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},pAa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},qAa=function(a){return new g6(a)},rAa=function(a){return Array.isArray(a)?(0,g.Lc)(a,qAa):[]},i6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},j6=function(a){return Array.isArray(a)?"["+(0,g.Lc)(a,i6).join(",")+"]":"null"},k6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|
0;
return("x"==a?b:b&3|8).toString(16)})},sAa=function(a){return(0,g.Lc)(a,function(b){return{key:b.id,
name:b.name}})},l6=function(a,b){return g.cb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},m6=function(a,b){return g.cb(a,function(c){return h6(c,b)})},tAa=function(){var a=(0,g.dt)();
a&&eAa(a,a.o.Xh(!0))},n6=function(){var a=g.gt("yt-remote-connected-devices")||[];
g.yb(a);return a},uAa=function(a){if(g.gb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.Lc)(a,function(d,e){return 0==e?d:d.substring(c.length)})},vAa=function(a){g.ft("yt-remote-connected-devices",a,86400)},p6=function(){if(o6)return o6;
var a=g.gt("yt-remote-device-id");a||(a=k6(),g.ft("yt-remote-device-id",a,31536E3));for(var b=n6(),c=1,d=a;g.fb(b,d);)c++,d=a+"#"+c;return o6=d},q6=function(){var a=n6(),b=p6();
g.fb(a,b);g.it()&&g.Ab(a,b);a=uAa(a);if(g.gb(a))try{g.Cq.remove("remote_sid","/","youtube.com")}catch(c){}else try{g.Dq("remote_sid",a.join(","),-1)}catch(c){}},wAa=function(){return g.gt("yt-remote-session-browser-channel")},xAa=function(){return g.gt("yt-remote-local-screens")||[]},yAa=function(){g.ft("yt-remote-lounge-token-expiration",!0,86400)},zAa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.Lc)(xAa(),function(d){return d.loungeToken}),c=(0,g.Lc)(a,function(d){return d.loungeToken});
(0,g.Di)(c,function(d){return!g.fb(b,d)})&&yAa();
g.ft("yt-remote-local-screens",a,31536E3)},AAa=function(a,b){g.ft("yt-remote-session-browser-channel",a);
g.ft("yt-remote-session-screen-id",b);var c=n6(),d=p6();g.fb(c,d)||c.push(d);vAa(c);q6()},r6=function(a){a||(g.ht("yt-remote-session-screen-id"),g.ht("yt-remote-session-video-id"));
q6();a=n6();g.kb(a,p6());vAa(a)},BAa=function(){if(!s6){var a=g.qo();
a&&(s6=new g.ao(a))}return s6?!!s6.get("yt-remote-use-staging-server"):!1},CAa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},DAa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},t6=function(a){a.length?EAa(a.shift(),function(){t6(a)}):u6()},FAa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},EAa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},u6=function(){var a=DAa();
a&&a(!1,"No cast extension found")},HAa=function(){if(GAa){var a=2,b=DAa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;EAa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",u6,c)}},IAa=function(){HAa();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);t6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},v6=function(a,b,c){g.A.call(this);
this.F=null!=c?(0,g.x)(a,c):a;this.Od=b;this.C=(0,g.x)(this.PG,this);this.o=!1;this.u=0;this.A=this.Ka=null;this.B=[]},w6=function(a,b,c){g.A.call(this);
this.B=null!=c?a.bind(c):a;this.Od=b;this.A=null;this.o=!1;this.u=0;this.Ka=null},x6=function(a){a.Ka=g.cg(function(){a.Ka=null;
a.o&&!a.u&&(a.o=!1,x6(a))},a.Od);
var b=a.A;a.A=null;a.B.apply(null,b)},y6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return iAa(a)},z6=function(){},A6=function(){},JAa=function(){},LAa=function(a){return(a=KAa(a))?new ActiveXObject(a):new XMLHttpRequest},KAa=function(a){if(!a.u&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.u=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.u},B6=function(a,b,c,d){this.o=a;
this.A=b;this.I=c;this.G=d||1;this.C=45E3;this.B=new g.y1(this);this.u=new g.bg;this.u.setInterval(250)},NAa=function(a,b,c){a.Tl=1;
a.ai=a6(b.clone());a.jk=c;a.F=!0;MAa(a,null)},C6=function(a,b,c,d,e){a.Tl=1;
a.ai=a6(b.clone());a.jk=null;a.F=c;e&&(a.yD=!1);MAa(a,d)},MAa=function(a,b){a.Ol=(0,g.E)();
D6(a);a.Ui=a.ai.clone();b6(a.Ui,"t",a.G);a.xo=0;a.gd=a.o.At(a.o.ho()?b:null);0<a.iu&&(a.Cr=new w6((0,g.x)(a.xE,a,a.gd),a.iu));a.B.ma(a.gd,"readystatechange",a.xO);var c=a.Dj?g.Ub(a.Dj):{};a.jk?(a.ws="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.gd.send(a.Ui,a.ws,a.jk,c)):(a.ws="GET",a.yD&&!g.re&&(c.Connection="close"),a.gd.send(a.Ui,a.ws,null,c));a.o.Vf(1)},QAa=function(a,b,c){for(var d=!0;!a.kj&&a.xo<c.length;){var e=OAa(a,c);
if(e==E6){4==b&&(a.ri=4,F6(15),d=!1);break}else if(e==PAa){a.ri=4;F6(16);d=!1;break}else G6(a,e)}4==b&&0==c.length&&(a.ri=1,F6(17),d=!1);a.eg=a.eg&&d;d||(H6(a),I6(a))},OAa=function(a,b){var c=a.xo,d=b.indexOf("\n",c);
if(-1==d)return E6;c=Number(b.substring(c,d));if(isNaN(c))return PAa;d+=1;if(d+c>b.length)return E6;var e=b.substr(d,c);a.xo=d+c;return e},SAa=function(a,b){a.Ol=(0,g.E)();
D6(a);var c=b?window.location.hostname:"";a.Ui=a.ai.clone();$5(a.Ui,"DOMAIN",c);$5(a.Ui,"t",a.G);try{a.kg=new ActiveXObject("htmlfile")}catch(n){H6(a);a.ri=7;F6(22);I6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var h=c.charAt(f);if("<"==h)e+="\\x3c";else if(">"==h)e+="\\x3e";else{var l=h;if(l in J6)h=J6[l];else if(l in RAa)h=J6[l]=RAa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)h=l;else{if(256>m){if(h="\\x",16>m||256<m)h+="0"}else h="\\u",4096>m&&(h+="0");h+=m.toString(16).toUpperCase()}h=
J6[l]=h}e+=h}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.cd(g.ec("b/12014412"),d+"</body></html>");a.kg.open();a.kg.write(g.Yc(c));a.kg.close();a.kg.parentWindow.m=(0,g.x)(a.LN,a);a.kg.parentWindow.d=(0,g.x)(a.CC,a,!0);a.kg.parentWindow.rpcClose=(0,g.x)(a.CC,a,!1);c=a.kg.createElement("DIV");a.kg.parentWindow.document.body.appendChild(c);d=g.Fc(a.Ui.toString());d=g.kd(g.Bc(d));d=g.cd(g.ec("b/12014412"),'<iframe src="'+d+'"></iframe>');g.dd(c,d);a.o.Vf(1)},D6=function(a){a.bx=(0,g.E)()+a.C;
TAa(a,a.C)},TAa=function(a,b){if(null!=a.cm)throw Error("WatchDog timer not null");
a.cm=K6((0,g.x)(a.UN,a),b)},L6=function(a){a.cm&&(g.v.clearTimeout(a.cm),a.cm=null)},I6=function(a){a.o.Ez()||a.kj||a.o.Yp(a)},H6=function(a){L6(a);
g.Pe(a.Cr);a.Cr=null;a.u.stop();g.Gua(a.B);if(a.gd){var b=a.gd;a.gd=null;b.abort();b.dispose()}a.kg&&(a.kg=null)},G6=function(a,b){try{a.o.tC(a,b),a.o.Vf(4)}catch(c){}},VAa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;UAa(a,b,function(h){h?c(!0):g.v.setTimeout(function(){VAa(a,b,c,d,f)},f)})}},UAa=function(a,b,c){var d=new Image;
d.onload=function(){try{M6(d),c(!0)}catch(e){}};
d.onerror=function(){try{M6(d),c(!1)}catch(e){}};
d.onabort=function(){try{M6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{M6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
hAa(d,a)},M6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},WAa=function(a){this.o=a;
this.u=new z6},XAa=function(a){var b=N6(a.o,a.om,"/mail/images/cleardot.gif");
a6(b);VAa(b.toString(),5E3,(0,g.x)(a.MF,a),3,2E3);a.Vf(1)},P6=function(a){var b=a.o.M;
if(null!=b)F6(5),b?(F6(11),O6(a.o,a,!1)):(F6(12),O6(a.o,a,!0));else if(a.Be=new B6(a,void 0,void 0,void 0),a.Be.Dj=a.gu,b=a.o,b=N6(b,b.ho()?a.Sm:null,a.hu),F6(5),!g.pe||g.Ud(10))b6(b,"TYPE","xmlhttp"),C6(a.Be,b,!1,a.Sm,!1);else{b6(b,"TYPE","html");var c=a.Be;a=!!a.Sm;c.Tl=3;c.ai=a6(b.clone());SAa(c,a)}},Q6=function(a){g.rf.call(this);
this.headers=new g.Wm;this.T=a||null;this.A=!1;this.U=this.o=null;this.fa=this.M="";this.F=0;this.B="";this.C=this.aa=this.I=this.Y=!1;this.G=0;this.N=null;this.ga="";this.R=this.Z=!1},YAa=function(a){return g.pe&&g.Td(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},ZAa=function(a){return"content-type"==a.toLowerCase()},aBa=function(a,b){a.A=!1;
a.o&&(a.C=!0,a.o.abort(),a.C=!1);a.B=b;a.F=5;$Aa(a);R6(a)},$Aa=function(a){a.Y||(a.Y=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},cBa=function(a){if(a.A&&"undefined"!=typeof g.D1)if(a.U[1]&&4==S6(a)&&2==a.getStatus())T6(a,"Local request error detected and ignored");
else if(a.I&&4==S6(a))g.cg(a.pC,0,a);else if(a.dispatchEvent("readystatechange"),4==S6(a)){T6(a,"Request complete");a.A=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.ud(1,String(a.M));if(!f&&g.v.self&&g.v.self.location){var h=g.v.self.location.protocol;f=h.substr(0,h.length-1)}e=!bBa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.F=6;try{var l=2<S6(a)?a.o.statusText:""}catch(m){l=""}a.B=l+" ["+a.getStatus()+"]";$Aa(a)}}finally{R6(a)}}},R6=function(a,b){if(a.o){dBa(a);
var c=a.o,d=a.U[0]?g.Ka:null;a.o=null;a.U=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},dBa=function(a){a.o&&a.R&&(a.o.ontimeout=null);
a.N&&(g.v.clearTimeout(a.N),a.N=null)},S6=function(a){return a.o?a.o.readyState:0},U6=function(a){try{return a.o?a.o.responseText:""}catch(b){return""}},T6=function(a,b){return b+" ["+a.fa+" "+a.M+" "+a.getStatus()+"]"},V6=function(a,b,c){this.o=1;
this.u=[];this.B=[];this.C=new z6;this.I=a||null;this.M=null!=b?b:null;this.F=c||!1},eBa=function(a,b){this.o=a;
this.map=b;this.context=null},fBa=function(a){g.Re.call(this,"statevent",a)},gBa=function(a,b){g.Re.call(this,"timingevent",a);
this.size=b},hBa=function(a){g.Re.call(this,"serverreachability",a)},kBa=function(a){iBa(a);
if(3==a.o){var b=a.Bn++,c=a.Hp.clone();$5(c,"SID",a.A);$5(c,"RID",b);$5(c,"TYPE","terminate");W6(a,c);b=new B6(a,a.A,b,void 0);b.Tl=2;b.ai=a6(c.clone());hAa(new Image,b.ai.toString());b.Ol=(0,g.E)();D6(b)}jBa(a)},lBa=function(a){a.nG(1,0);
a.Hp=N6(a,null,a.fu);X6(a)},iBa=function(a){a.di&&(a.di.abort(),a.di=null);
a.Ec&&(a.Ec.cancel(),a.Ec=null);a.bh&&(g.v.clearTimeout(a.bh),a.bh=null);Y6(a);a.oe&&(a.oe.cancel(),a.oe=null);a.ii&&(g.v.clearTimeout(a.ii),a.ii=null)},mBa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new eBa(a.wK++,b));2!=a.o&&3!=a.o||X6(a)},X6=function(a){a.oe||a.ii||(a.ii=K6((0,g.x)(a.BC,a),0),a.Rk=0)},oBa=function(a,b){if(1==a.o){if(!b){a.Bn=Math.floor(1E5*Math.random());
var c=a.Bn++,d=new B6(a,"",c,void 0);d.Dj=a.Yk;var e=Z6(a),f=a.Hp.clone();$5(f,"RID",c);$5(f,"CVER","1");W6(a,f);NAa(d,f,e);a.oe=d;a.o=2}}else 3==a.o&&(b?nBa(a,b):0==a.u.length||a.oe||nBa(a))},nBa=function(a,b){if(b)if(6<a.lj){a.u=a.B.concat(a.u);
a.B.length=0;var c=a.Bn-1;var d=Z6(a)}else c=b.I,d=b.jk;else c=a.Bn++,d=Z6(a);var e=a.Hp.clone();$5(e,"SID",a.A);$5(e,"RID",c);$5(e,"AID",a.pl);W6(a,e);c=new B6(a,a.A,c,a.Rk+1);c.Dj=a.Yk;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.oe=c;NAa(c,e,d)},W6=function(a,b){if(a.Ld){var c=a.Ld.cz();
c&&g.Cb(c,function(d,e){$5(b,e,d)})}},Z6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.lj&&0<b){var d=a.u[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.u[e].o,h=a.u[e].map;f=6>=a.lj?e:f-d;try{g.Cb(h,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.B=a.B.concat(a.u.splice(0,b));
return c.join("&")},pBa=function(a){a.Ec||a.bh||(a.G=1,a.bh=K6((0,g.x)(a.AC,a),0),a.Dk=0)},$6=function(a){if(a.Ec||a.bh||3<=a.Dk)return!1;
a.G++;a.bh=K6((0,g.x)(a.AC,a),qBa(a,a.Dk));a.Dk++;return!0},O6=function(a,b,c){a.ts=c;
a.vg=b.sh;a.F||lBa(a)},Y6=function(a){null!=a.pj&&(g.v.clearTimeout(a.pj),a.pj=null)},qBa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},a7=function(a,b){if(2==b||9==b){var c=null;
a.Ld&&(c=null);var d=(0,g.x)(a.gP,a);c||(c=new g.Zm("//www.google.com/images/cleardot.gif"),a6(c));UAa(c.toString(),1E4,d)}else F6(2);rBa(a,b)},rBa=function(a,b){a.o=0;
a.Ld&&a.Ld.ry(b);jBa(a);iBa(a)},jBa=function(a){a.o=0;
a.vg=-1;if(a.Ld)if(0==a.B.length&&0==a.u.length)a.Ld.jt();else{g.ob(a.B);var b=g.ob(a.u);a.B.length=0;a.u.length=0;a.Ld.jt(b)}},N6=function(a,b,c){var d=g.gn(c);
if(""!=d.o)b&&g.an(d,b+"."+d.o),g.bn(d,d.B);else{var e=window.location;d=lAa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Hm&&g.Cb(a.Hm,function(f,h){$5(d,h,f)});
$5(d,"VER",a.lj);W6(a,d);return d},K6=function(a,b){if(!g.Oa(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},F6=function(a){b7.dispatchEvent(new fBa(b7,a))},sBa=function(){},tBa=function(){this.o=[];
this.u=[]},uBa=function(a,b){this.action=a;
this.params=b||{}},c7=function(a,b){g.A.call(this);
this.o=new g.G(this.EN,0,this);g.C(this,this.o);this.Od=5E3;this.u=0;if("function"===typeof a)b&&(a=(0,g.x)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.A=a},d7=function(a,b,c,d){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
this.N=a;this.F=b;this.A=new g.$n;this.u=new c7(this.LO,this);this.o=null;this.Tc=!1;this.C=null;this.M="";this.I=this.B=0;this.G=[];this.U=c;this.R=d},vBa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.ts,sessionId:a.o.A,arrayId:a.o.pl}},wBa=function(a,b){a.I=b||0;
a.u.stop();e7(a);a.o&&(3==a.o.o&&oBa(a.o),kBa(a.o));a.I=0},f7=function(a){return!!a.o&&3==a.o.o},e7=function(a){if(a.o){var b=a.R(),c=a.o.Yk||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.o.Yk=c}},xBa=function(a,b){(a.F.loungeIdToken=b)||a.u.stop()},g7=function(a){this.scheme="https";
this.port=this.domain="";this.o="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.ud(4,a))||"";b&&(this.port=":"+b);this.domain=g.vd(a)||"";a=g.Rc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.xc(a,"10.0")&&(this.u=!1))},h7=function(a,b){var c=a.o;
a.u&&(c=a.scheme+"://"+a.domain+a.port+a.o);return g.Fd(c+b,{})},i7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Sa(a.B,d,!0),onError:g.Sa(a.A,e),Te:g.Sa(a.C,e)};c&&(a.Cb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.wq(b,a)},BBa=function(){var a=yBa;
zBa();j7.push(a);ABa(j7)},k7=function(a,b){zBa();
var c=j7,d=CBa(a,String(b));g.gb(c)?DBa(d):(ABa(c),(0,g.y)(c,function(e){e(d)}))},zBa=function(){j7||(j7=g.Ja("yt.mdx.remote.debug.handlers_")||[],g.Ha("yt.mdx.remote.debug.handlers_",j7,void 0))},DBa=function(a){var b=(l7+1)%50;
l7=b;m7[b]=a;n7||(n7=49==b)},ABa=function(a){var b=m7;
if(b[0]){var c=l7,d=n7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.y)(a,function(f){f(e)})}while(d!=c);
m7=Array(50);l7=-1;n7=!1}},CBa=function(a,b){var c=((0,g.E)()-EBa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},o7=function(a){g.O.call(this);
this.F=a;this.screens=[]},FBa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.screens.push(b);return!0},GBa=function(a,b){var c=a.screens.length!=b.length;
a.screens=(0,g.De)(a.screens,function(f){return!!l6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=FBa(a,b[d])||c;return c},HBa=function(a,b){var c=a.screens.length;
a.screens=(0,g.De)(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},p7=function(a,b,c,d){g.O.call(this);
this.F=a;this.C=b;this.A=c;this.B=d;this.u=0;this.o=null;this.Ka=NaN},r7=function(a){o7.call(this,"LocalScreenService");
this.u=a;this.o=NaN;q7(this);this.info("Initializing with "+j6(this.screens))},IBa=function(a){if(a.screens.length){var b=(0,g.Lc)(a.screens,function(d){return d.id}),c=h7(a.u,"/pairing/get_lounge_token_batch");
i7(a.u,c,{screen_ids:b.join(",")},(0,g.x)(a.aH,a),(0,g.x)(a.ZG,a))}},q7=function(a){var b=rAa(xAa());
b=(0,g.De)(b,function(c){return!c.uuid});
return GBa(a,b)},s7=function(a,b){zAa((0,g.Lc)(a.screens,pAa));
b&&yAa()},u7=function(a,b){g.O.call(this);
this.F=b;var c=g.gt("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,h=e.length;f<h;++f){var l=e[f].id;d[l]=g.fb(c,l)}this.o=d;this.C=a;this.A=this.B=NaN;this.u=null;t7("Initialized with "+g.Sk(this.o))},JBa=function(a,b,c){var d=h7(a.C,"/pairing/get_screen_availability");
i7(a.C,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},v7=function(a,b){a:if(c6(b)!=c6(a.o))var c=!1;
else{c=g.Lb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(t7("Updated online screens: "+g.Sk(a.o)),a.o=b,a.S("screenChange"));KBa(a)},w7=function(a){isNaN(a.A)||g.Oo(a.A);
a.A=g.Mo((0,g.x)(a.Zv,a),0<a.B&&a.B<(0,g.E)()?2E4:1E4)},t7=function(a){k7("OnlineScreenService",a)},LBa=function(a){var b={};
(0,g.y)(a.F(),function(c){c.token?b[c.token]=c.id:this.pc("Requesting availability of screen w/o lounge token.")});
return b},KBa=function(a){a=g.Lb(g.Db(a.o,function(b){return b}));
g.yb(a);a.length?g.ft("yt-remote-online-screen-ids",a.join(","),60):g.ht("yt-remote-online-screen-ids")},x7=function(a){o7.call(this,"ScreenService");
this.C=a;this.o=this.u=null;this.A=[];this.B={};MBa(this)},OBa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var h=a.Ne();if(h=(c?m6(h,c):null)||m6(h,b)){h.uuid=b;var l=y7(a,h);JBa(a.o,l,function(m){e(m?l:null)})}else c?NBa(a,c,(0,g.x)(function(m){var n=y7(this,new g6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));JBa(this.o,n,function(q){e(q?n:null)})},a),f):e(null)},PBa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},NBa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Cb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){var l=h&&h.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.wq(h7(a.C,"/pairing/get_lounge_token_batch"),e)},QBa=function(a){a.screens=a.u.Ne();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+j6(a.screens))},MBa=function(a){z7(a);
a.u=new r7(a.C);a.u.subscribe("screenChange",(0,g.x)(a.hH,a));QBa(a);a.A=rAa(g.gt("yt-remote-automatic-screen-cache")||[]);z7(a);a.info("Initializing automatic screens: "+j6(a.A));a.o=new u7(a.C,(0,g.x)(a.Ne,a,!0));a.o.subscribe("screenChange",(0,g.x)(function(){this.S("onlineScreenChange")},a))},y7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=m6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.ft("yt-remote-automatic-screen-cache",(0,g.Lc)(a.A,pAa)));z7(a);a.B[b.uuid]=b.id;g.ft("yt-remote-device-id-map",a.B,31536E3);return b},z7=function(a){a.B=g.gt("yt-remote-device-id-map")||{}},A7=function(a,b,c){g.O.call(this);
this.U=c;this.M=a;this.o=b;this.I=null},B7=function(a,b){k7(a.U,b)},C7=function(a,b){A7.call(this,a,b,"CastSession");
this.u=null;this.A=0;this.C=(0,g.x)(this.MP,this);this.B=(0,g.x)(this.dO,this);this.A=g.Mo((0,g.x)(function(){RBa(this,null)},this),12E4)},SBa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Sk(void 0));
var b={type:"getMdxSessionStatus"};a.u?a.u.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ka,(0,g.x)(function(){B7(this,"Failed to send message: getMdxSessionStatus.")},a)):B7(a,"Sending yt message without session: "+g.Sk(b))},RBa=function(a,b){g.Oo(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.getScreen()||a.getScreen().id!=b){var c=(0,g.x)(a.sr,a),d=(0,g.x)(a.Se,a);a.xz(b,c,d,5)}}else a.Se(Error("Waiting for session status timed out."))},D7=function(a,b,c){A7.call(this,a,b,"DialSession");
this.A=this.G=null;this.N="";this.T=c;this.B=null;this.F=g.Ka;this.C=NaN;this.R=(0,g.x)(this.PP,this);this.u=g.Ka},TBa=function(a){a.u=a.M.EE(a.N,a.o.label,a.o.friendlyName,(0,g.x)(function(b){this.u=g.Ka;
this.sr(b)},a),(0,g.x)(function(b){this.u=g.Ka;
this.Se(b)},a))},UBa=function(a){var b={};
b.pairingCode=a.N;b.theme=a.T;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}BAa()&&(b.env_useStageMdx=1);return g.Dd(b)},E7=function(a,b){A7.call(this,a,b,"ManualSession");
this.u=g.Mo((0,g.x)(this.ql,this,null),150)},F7=function(a,b,c,d){g.O.call(this);
this.u=a;this.G=b||"233637DE";this.F=c||"cl";this.I=d||!1;this.o=null;this.C=!1;this.A=[];this.B=(0,g.x)(this.TM,this)},VBa=function(a,b){return b?g.cb(a.A,function(c){return h6(b,c.label)},a):null},G7=function(a){k7("Controller",a)},yBa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},H7=function(a){return a.C||!!a.A.length||!!a.o},I7=function(a,b,c){b!=a.o&&(g.Pe(a.o),(a.o=b)?(c?a.S("yt-remote-cast2-receiver-resumed",b.o):a.S("yt-remote-cast2-receiver-selected",
b.o),b.subscribe("sessionScreen",(0,g.x)(a.yC,a,b)),b.getScreen()?a.S("yt-remote-cast2-session-change",b.getScreen()):c&&a.o.ql(null)):a.S("yt-remote-cast2-session-change",null))},WBa=function(a){var b=a.u.DE(),c=a.o&&a.o.o;
a=(0,g.Lc)(b,function(d){c&&h6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=VBa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},bCa=function(a,b,c,d,e,f,h){XBa()?YBa(b,e,f,h)&&(K7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?ZBa(a,c):(window.__onGCastApiAvailable=function(l,m){l?ZBa(a,c):(L7("Failed to load cast API: "+m),M7(!1),K7(!1),g.ht("yt-remote-cast-available"),g.ht("yt-remote-cast-receiver"),$Ba(),c(!1))},d?g.Yo("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?IAa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?u6():(HAa(),t6(aCa.map(FAa))))):J7("Cannot initialize because not running Chrome")},$Ba=function(){J7("dispose");
var a=N7();a&&a.dispose();g.Ha("yt.mdx.remote.cloudview.instance_",null,void 0);cCa(!1);g.Uo(O7);O7.length=0},P7=function(){return!!g.gt("yt-remote-cast-installed")},dCa=function(){var a=g.gt("yt-remote-cast-receiver");
return a?a.friendlyName:null},eCa=function(){J7("clearCurrentReceiver");
g.ht("yt-remote-cast-receiver")},fCa=function(){return P7()?N7()?N7().getCastSession():(L7("getCastSelector: Cast is not initialized."),null):(L7("getCastSelector: Cast API is not installed!"),null)},R7=function(){P7()?N7()?Q7()?(J7("Requesting cast selector."),N7().requestSession()):(J7("Wait for cast API to be ready to request the session."),O7.push(g.To("yt-remote-cast2-api-ready",R7))):L7("requestCastSelector: Cast is not initialized."):L7("requestCastSelector: Cast API is not installed!")},S7=
function(a,b){Q7()?N7().setConnectedScreenStatus(a,b):L7("setConnectedScreenStatus called before ready.")},XBa=function(){var a=0<=g.Rc.search(/ (CrMo|Chrome|CriOS)\//);
return g.Yw||a},gCa=function(a,b){N7().init(a,b)},YBa=function(a,b,c,d){var e=!1;
N7()||(a=new F7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.ft("yt-remote-cast-available",f);e6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){J7("onReceiverSelected: "+f.friendlyName);
g.ft("yt-remote-cast-receiver",f);e6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){J7("onReceiverResumed: "+f.friendlyName);
g.ft("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){J7("onSessionChange: "+i6(f));
f||g.ht("yt-remote-cast-receiver");e6("yt-remote-cast2-session-change",f)}),g.Ha("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
J7("cloudview.createSingleton_: "+e);return e},N7=function(){return g.Ja("yt.mdx.remote.cloudview.instance_")},ZBa=function(a,b){M7(!0);
K7(!1);gCa(a,function(c){c?(cCa(!0),g.Vo("yt-remote-cast2-api-ready")):(L7("Failed to initialize cast API."),M7(!1),g.ht("yt-remote-cast-available"),g.ht("yt-remote-cast-receiver"),$Ba());b(c)})},J7=function(a){k7("cloudview",a)},L7=function(a){k7("cloudview",a)},M7=function(a){J7("setCastInstalled_ "+a);
g.ft("yt-remote-cast-installed",a)},Q7=function(){return!!g.Ja("yt.mdx.remote.cloudview.apiReady_")},cCa=function(a){J7("setApiReady_ "+a);
g.Ha("yt.mdx.remote.cloudview.apiReady_",a,void 0)},K7=function(a){g.Ha("yt.mdx.remote.cloudview.initializing_",a,void 0)},T7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.F=this.G=0;this.o=null;this.hasNext=this.wg=!1;this.M=this.I=this.u=this.C=0;this.B=NaN;this.A=!1;this.reset(a)},U7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.wg=!1;a.hasNext=!1;a.G=0;a.F=(0,g.E)();a.C=0;a.u=0;a.I=0;a.M=0;a.B=NaN;a.A=!1},V7=function(a){return a.sb()?((0,g.E)()-a.F)/1E3:0},W7=function(a,b){a.G=b;
a.F=(0,g.E)()},X7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.E)()-a.F)/1E3+a.G;
case -1E3:return 0}return a.G},Y7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&U7(a)},Z7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Vb(a.o);b.hasPrevious=a.wg;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.F;b.seekableStart=a.C;b.seekableEnd=a.u;b.duration=a.I;b.loadedTime=a.M;b.liveIngestionTime=a.B;return b},a8=function(a,b){g.O.call(this);
this.o=0;this.B=a;this.F=[];this.C=new tBa;this.A=this.u=null;this.M=(0,g.x)(this.cL,this);this.G=(0,g.x)(this.Fn,this);this.I=(0,g.x)(this.bL,this);this.N=(0,g.x)(this.kL,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.fx,this),hCa(this))):c=3;0!=c&&(b?this.fx(c):g.Mo((0,g.x)(function(){this.fx(c)},this),0));
var d=fCa();d&&$7(this,d);this.subscribe("yt-remote-cast2-session-change",this.N)},b8=function(a){return new T7(a.B.getPlayerContextData())},hCa=function(a){(0,g.y)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.F.push(this.B.subscribe(b,g.Sa(this.QM,b),this))},a)},iCa=function(a){(0,g.y)(a.F,function(b){this.B.unsubscribeByKey(b)},a);
a.F.length=0},c8=function(a,b){var c=a.C;
50>c.o.length+c.u.length&&a.C.u.push(b)},e8=function(a,b,c){var d=b8(a);
W7(d,c);-1E3!=d.playerState&&(d.playerState=b);d8(a,d)},f8=function(a,b,c){a.B.sendMessage(b,c)},d8=function(a,b){iCa(a);
a.B.setPlayerContextData(Z7(b));hCa(a)},$7=function(a,b){a.A&&(a.A.removeUpdateListener(a.M),a.A.removeMediaListener(a.G),a.Fn(null));
a.A=b;a.A&&(k7("CP","Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.M),a.A.addMediaListener(a.G),a.A.media.length&&a.Fn(a.A.media[0]))},jCa=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=b8(a);b.contentId!=d.videoId&&k7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;W7(d,a.u.getEstimatedTime());d8(a,d)}else k7("CP","No cast media video. Ignoring state update.")},g8=function(a,b,c){return(0,g.x)(function(d){this.pc("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.pc("Retrying "+b+" using MDx browser channel."),f8(this,b,c))},a)},h8=function(a,b,c){g.O.call(this);
this.C=NaN;this.R=!1;this.I=this.G=this.M=this.N=NaN;this.U=[];this.B=this.F=this.A=this.ib=this.o=null;this.Y=a;this.U.push(g.ip(window,"beforeunload",(0,g.x)(this.TG,this)));this.u=[];this.ib=new T7;this.T=b.id;this.o=kCa(this,c);this.o.subscribe("handlerOpened",this.gL,this);this.o.subscribe("handlerClosed",this.dL,this);this.o.subscribe("handlerError",this.eL,this);this.o.subscribe("handlerMessage",this.fL,this);xBa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var d=this.ib.videoId;
g.it()&&g.ft("yt-remote-session-video-id",d)},this)},i8=function(a){k7("conn",a)},kCa=function(a,b){return new d7(h7(a.Y,"/bc"),b,!1,function(){return a.AE()})},j8=function(a,b){a.S("proxyStateChange",b)},lCa=function(a){a.C=g.Mo((0,g.x)(function(){i8("Connecting timeout");
this.Mk(1)},a),2E4)},k8=function(a){g.Oo(a.C);
a.C=NaN},l8=function(a){g.Oo(a.N);
a.N=NaN},mCa=function(a){m8(a);
a.M=g.Mo((0,g.x)(function(){n8(this,"getNowPlaying")},a),2E4)},m8=function(a){g.Oo(a.M);
a.M=NaN},oCa=function(a,b){b&&(k8(a),l8(a));
b==(f7(a.o)&&isNaN(a.C))?b&&(j8(a,1),n8(a,"getSubtitlesTrack")):b?(a.vz()&&a.ib.reset(),j8(a,1),n8(a,"getNowPlaying"),nCa(a)):a.Mk(1)},pCa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.ib.videoId&&(g.Rb(b.params)?a.ib.o=null:a.ib.o=b.params,a.S("remotePlayerChange"))},qCa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.ib.listId=b.params.listId||a.ib.listId;Y7(a.ib,c,d);a.S("remoteQueueChange")},sCa=function(a,b){b.params=b.params||{};
qCa(a,b);rCa(a,b);a.S("autoplayDismissed")},rCa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
W7(a.ib,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.ib.playerState&&(c=-1E3);a.ib.playerState=c;c=Number(b.params.loadedTime);a.ib.M=isNaN(c)?0:c;c=Number(b.params.duration);a.ib.I=isNaN(c)?0:c;c=a.ib;var d=Number(b.params.liveIngestionTime);c.B=d;c.A=isNaN(d)?!1:!0;c=a.ib;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.u=isNaN(e)?0:e;1==a.ib.playerState?mCa(a):m8(a);a.S("remotePlayerChange")},tCa=function(a,b){if(-1E3!=
a.ib.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.ib.playerState=c;c=parseInt(b.params.currentTime,10);W7(a.ib,isNaN(c)?0:c);a.S("remotePlayerChange")}},uCa=function(a,b){var c="true"==b.params.muted;
a.ib.volume=parseInt(b.params.volume,10);a.ib.muted=c;a.S("remotePlayerChange")},vCa=function(a,b){a.F=b.params.videoId;
a.S("nowAutoplaying",parseInt(b.params.timeout,10))},wCa=function(a,b){var c="true"==b.params.hasNext;
a.ib.wg="true"==b.params.hasPrevious;a.ib.hasNext=c;a.S("previousNextChange")},nCa=function(a){g.Oo(a.I);
a.I=g.Mo((0,g.x)(a.Mk,a,1),864E5)},n8=function(a,b,c){c?i8("Sending: action="+b+", params="+g.Sk(c)):i8("Sending: action="+b);
a.o.sendMessage(b,c)},o8=function(a){o7.call(this,"ScreenServiceProxy");
this.Nd=a;this.o=[];this.o.push(this.Nd.$_s("screenChange",(0,g.x)(this.KP,this)));this.o.push(this.Nd.$_s("onlineScreenChange",(0,g.x)(this.tM,this)))},BCa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.L("MDX_CONFIG")||b;tAa();q6();p8||(p8=new g7(b?b.loungeApiHost:void 0),BAa()&&(p8.o="/api/loungedev"));q8||(q8=g.Ja("yt.mdx.remote.deferredProxies_")||[],g.Ha("yt.mdx.remote.deferredProxies_",q8,void 0));xCa();var c=r8();if(!c){var d=new x7(p8);g.Ha("yt.mdx.remote.screenService_",d,void 0);c=r8();var e=!1,f=void 0,h=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,h=b.theme,l=!!b.disableDial);bCa(a,d,function(m){m?s8()&&S7(s8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){e6("yt-remote-receiver-availability-change")})},e,f,h,l)}b&&!g.Ja("yt.mdx.remote.initialized_")&&(g.Ha("yt.mdx.remote.initialized_",!0,void 0),t8("Initializing: "+g.Sk(b)),u8.push(g.To("yt-remote-cast2-availability-change",function(){e6("yt-remote-receiver-availability-change")})),u8.push(g.To("yt-remote-cast2-receiver-selected",function(){v8(null);
e6("yt-remote-auto-connect","cast-selector-receiver")})),u8.push(g.To("yt-remote-cast2-receiver-resumed",function(){e6("yt-remote-receiver-resumed","cast-selector-receiver")})),u8.push(g.To("yt-remote-cast2-session-change",yCa)),u8.push(g.To("yt-remote-connection-change",function(m){m?S7(s8(),"YouTube TV"):w8()||(S7(null,null),eCa())})),a=x8(),b.isAuto&&(a.id+="#dial"),g.Co("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(h=b.theme)&&(a.theme=h),t8(" -- with channel params: "+
g.Sk(a)),zCa(a),c.start(),s8()||ACa())},DCa=function(){var a=CCa();
P7()&&g.gt("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},CCa=function(){var a=r8().Nd.$_gos();
var b=y8();b&&z8()&&(l6(a,b)||a.push(b));return sAa(a)},A8=function(){var a=ECa();
!a&&P7()&&dCa()&&(a={key:"cast-selector-receiver",name:dCa()});return a},ECa=function(){var a=CCa(),b=y8();
b||(b=w8());return g.cb(a,function(c){return b&&h6(b,c.key)?!0:!1})},y8=function(){var a=s8();
if(!a)return null;var b=r8().Ne();return m6(b,a)},yCa=function(a){t8("remote.onCastSessionChange_: "+i6(a));
if(a){var b=y8();b&&b.id==a.id?S7(b.id,"YouTube TV"):(b&&B8(),C8(a,1))}else z8()&&B8()},B8=function(){Q7()?N7().stopSession():L7("stopSession called before API ready.");
var a=z8();a&&(a.disconnect(1),D8(null))},E8=function(){var a=z8();
return!!a&&3!=a.getProxyState()},t8=function(a){k7("remote",a)},r8=function(){if(!F8){var a=g.Ja("yt.mdx.remote.screenService_");
F8=a?new o8(a):null}return F8},s8=function(){return g.Ja("yt.mdx.remote.currentScreenId_")},FCa=function(a){g.Ha("yt.mdx.remote.currentScreenId_",a,void 0)},GCa=function(){return g.Ja("yt.mdx.remote.connectData_")},v8=function(a){g.Ha("yt.mdx.remote.connectData_",a,void 0)},z8=function(){return g.Ja("yt.mdx.remote.connection_")},D8=function(a){var b=z8();
v8(null);a||FCa("");g.Ha("yt.mdx.remote.connection_",a,void 0);q8&&((0,g.y)(q8,function(c){c(a)}),q8.length=0);
b&&!a?e6("yt-remote-connection-change",!1):!b&&a&&e6("yt-remote-connection-change",!0)},w8=function(){var a=g.it();
if(!a)return null;var b=r8();if(!b)return null;b=b.Ne();return m6(b,a)},C8=function(a,b){s8();
y8()&&y8();if(G8)H8=a;else{FCa(a.id);var c=new h8(p8,a,x8());c.connect(b,GCa());c.subscribe("beforeDisconnect",function(d){e6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){z8()&&(z8(),D8(null))});
D8(c)}},ACa=function(){var a=w8();
a?(t8("Resume connection to: "+i6(a)),C8(a,0)):(r6(),eCa(),t8("Skipping connecting because no session screen found."))},xCa=function(){var a=x8();
if(g.Rb(a)){a=p6();var b=g.gt("yt-remote-session-name")||"",c=g.gt("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ha("yt.mdx.remote.channelParams_",a,void 0)}},x8=function(){return g.Ja("yt.mdx.remote.channelParams_")||{}},zCa=function(a){a?(g.ft("yt-remote-session-app",a.app),g.ft("yt-remote-session-name",a.name)):(g.ht("yt-remote-session-app"),g.ht("yt-remote-session-name"));
g.Ha("yt.mdx.remote.channelParams_",a,void 0)},I8=function(a,b,c){g.A.call(this);
var d=this;this.module=a;this.H=b;this.ab=c;this.events=new g.js(this);this.M=this.events.L(this.H,"onVolumeChange",this.aC);this.B=!1;this.suggestion=null;this.C=new g.fG(64);this.o=new g.G(this.ID,500,this);this.u=new g.G(this.JD,1E3,this);this.G=new v6(this.qP,0,this);this.A={};this.I=new g.G(this.nE,1E3,this);this.F=new w6(this.seekTo,1E3,this);this.N=g.Ka;g.C(this,this.events);this.events.L(b,"onCaptionsTrackListChanged",this.UL);this.events.L(b,"captionschanged",this.aL);this.events.L(b,"captionssettingschanged",
this.MD);this.events.L(b,"videoplayerreset",this.tr);this.events.L(b,"mdxautoplaycancel",function(){d.ab.My()});
a=this.ab;a.ha();a.subscribe("proxyStateChange",this.sC,this);a.subscribe("remotePlayerChange",this.Mn,this);a.subscribe("remoteQueueChange",this.tr,this);a.subscribe("previousNextChange",this.oC,this);a.subscribe("nowAutoplaying",this.kC,this);a.subscribe("autoplayDismissed",this.KB,this);g.C(this,this.o);g.C(this,this.u);g.C(this,this.G);g.C(this,this.I);g.C(this,this.F);this.MD();this.tr();this.Mn()},HCa=function(a){a.Xb(0);
a.o.stop();a.Qc(new g.fG(64))},K8=function(a,b){if(J8(a)&&!a.B){var c=null;
b&&(c={style:a.H.getSubtitlesUserSettings()},g.Xb(c,b));a.ab.BE(a.H.getVideoData(1).videoId,c);a.A=b8(a.ab).o}},L8=function(a,b){var c=a.H.getPlaylist();
if(c){var d=c.index;var e=c.listId.toString()}c=a.H.getVideoData(1);a.ab.playVideo(c.videoId,b,d,e,c.playerParams,c.mf,fAa(c));a.Qc(new g.fG(1))},ICa=function(a,b){if(b){var c=a.H.getOption("captions","tracklist",{Vz:1});
c&&c.length?(a.H.setOption("captions","track",b),a.B=!1):(a.H.loadModule("captions"),a.B=!0)}else a.H.setOption("captions","track",{})},J8=function(a){return b8(a.ab).videoId===a.H.getVideoData(1).videoId},M8=function(){g.U.call(this,{D:"div",
J:"ytp-mdx-manual-pairing-popup-dialog",P:{role:"dialog"},K:[{D:"div",J:"ytp-mdx-manual-pairing-popup-dialog-inner-content",K:[{D:"div",J:"ytp-mdx-manual-pairing-popup-title",V:"Connecting to your TV on web using a code will be going away soon"},{D:"div",J:"ytp-mdx-manual-pairing-popup-buttons",K:[{D:"button",W:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],V:"Learn more"},{D:"button",W:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],V:"OK"}]}]}]});this.o=new g.oO(this,250);this.learnMoreButton=
this.ca("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.ca("ytp-mdx-manual-pairing-popup-ok");g.C(this,this.o);this.L(this.learnMoreButton,"click",this.u);this.L(this.okButton,"click",this.A)},N8=function(){g.U.call(this,{D:"div",
J:"ytp-mdx-popup-dialog",P:{role:"dialog"},K:[{D:"div",J:"ytp-mdx-popup-dialog-inner-content",K:[{D:"div",J:"ytp-mdx-popup-title",V:"You're signed out"},{D:"div",J:"ytp-mdx-popup-description",V:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{D:"div",J:"ytp-mdx-privacy-popup-buttons",K:[{D:"button",W:["ytp-button","ytp-mdx-privacy-popup-cancel"],V:"Cancel"},{D:"button",W:["ytp-button","ytp-mdx-privacy-popup-confirm"],
V:"Confirm"}]}]}]});this.o=new g.oO(this,250);this.cancelButton=this.ca("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.ca("ytp-mdx-privacy-popup-confirm");g.C(this,this.o);this.L(this.cancelButton,"click",this.u);this.L(this.confirmButton,"click",this.A)},O8=function(a){g.U.call(this,{D:"div",
J:"ytp-remote",K:[{D:"div",J:"ytp-remote-display-status",K:[{D:"div",J:"ytp-remote-display-status-icon",K:[g.rM()]},{D:"div",J:"ytp-remote-display-status-text",V:"{{statustext}}"}]}]});this.api=a;this.o=new g.oO(this,250);g.C(this,this.o);this.L(a,"presentingplayerstatechange",this.u);JCa(this,g.pM(a))},JCa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
c=g.T(b,128)?g.SL("Error on $RECEIVER_NAME",c):b.sb()||g.T(b,4)?g.SL("Playing on $RECEIVER_NAME",c):g.SL("Connected to $RECEIVER_NAME",c);a.la("statustext",c);a.o.show()}else a.o.hide()},P8=function(a,b){g.JR.call(this,"Play on",0,a,b);
this.H=a;this.Ti={};this.L(a,"onMdxReceiversChange",this.B);this.L(a,"presentingplayerstatechange",this.B);this.B()},Q8=function(a){g.UN.call(this,a);
this.Qf={key:k6(),name:"This computer"};this.og=null;this.subscriptions=[];this.Mv=this.ab=null;this.Ti=[this.Qf];this.gi=this.Qf;this.Tb=new g.fG(64);this.nA=0;this.md=-1;this.sl=null;this.Nn=this.Bq=!1;this.ik=this.Kl=null;if(!g.Fy(this.player.O())){a=this.player;var b=g.gN(a);b&&(b=b.Aj())&&(b=new P8(a,b),g.C(this,b));b=new O8(a);g.C(this,b);g.GN(a,b.element,4);this.Kl=new N8;g.C(this,this.Kl);g.GN(a,this.Kl.element,4);g.Q(this.player.O().experiments,"pair_servlet_deprecation_warning_enabled")&&
(this.sl=new M8,g.C(this,this.sl),g.GN(a,this.sl.element,4));this.Nn=!!w8();this.Bq=!!g.gt("yt-remote-manual-pairing-warning-shown")}},R8=function(a){a.ik&&(a.player.removeEventListener("presentingplayerstatechange",a.ik),a.ik=null)},KCa=function(a,b,c){a.Tb=c;
a.player.S("presentingplayerstatechange",new g.oG(c,b))},LCa=function(a,b,c){var d=!1;
1===b?d=!a.Nn:2===b&&(d=!a.Bq);d&&g.qG(c,8)&&(a.player.pauseVideo(),R8(a))},S8=function(a,b){if(b.key!==a.gi.key)if(b.key===a.Qf.key)B8();
else{if(a.sl&&!a.Bq&&b!==a.Qf&&"cast-selector-receiver"!==b.key&&g.Oy(a.player.O()))MCa(a);else{var c;(c=!g.Q(a.player.O().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.L("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.L("SESSION_INDEX")&&!g.L("LOGGED_IN")))||a.Nn||!a.Kl);(c?0:g.Oy(a.player.O())||g.Sy(a.player.O()))&&NCa(a)}a.gi=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.Q(a.player.O().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.getLength();l++)h[l]=f.Aa(l).videoId}else h=[e];f=a.player.getCurrentTime(1);d={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.mf,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=fAa(c))&&(d.locationInfo=c);c=d}t8("Connecting to: "+g.Sk(b));"cast-selector-receiver"==b.key?(v8(c||null),c=
c||null,Q7()?N7().setLaunchParams(c):L7("setLaunchParams called before ready.")):!c&&E8()&&s8()==b.key?e6("yt-remote-connection-change",!0):(B8(),v8(c||null),c=r8().Ne(),(c=m6(c,b.key))&&C8(c,1))}},NCa=function(a){g.pM(a.player).sb()?a.player.pauseVideo():(a.ik=function(b){LCa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.ik));
a.Kl&&a.Kl.Yb();z8()||(G8=!0)},MCa=function(a){g.pM(a.player).sb()?a.player.pauseVideo():(a.ik=function(b){LCa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.ik));
a.sl&&a.sl.Yb();z8()||(G8=!0)},RAa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},J6={"'":"\\'"},OCa={},oAa={rQ:"atp",kT:"ska",VS:"que",iS:"mus",jT:"sus",qR:"dsp",cT:"seq"},s6,o6="",GAa=CAa("loadCastFramework")||CAa("loadCastApplicationFramework"),aCa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Ua(v6,g.A);g.k=v6.prototype;g.k.OG=function(a){this.B=arguments;this.o=!1;this.Ka?this.A=(0,g.E)()+this.Od:this.Ka=g.cg(this.C,this.Od)};
g.k.stop=function(){this.Ka&&(g.v.clearTimeout(this.Ka),this.Ka=null);this.A=null;this.o=!1;this.B=[]};
g.k.pause=function(){++this.u};
g.k.resume=function(){this.u&&(--this.u,!this.u&&this.o&&(this.o=!1,this.F.apply(null,this.B)))};
g.k.X=function(){this.stop();v6.tc.X.call(this)};
g.k.PG=function(){this.A?(this.Ka=g.cg(this.C,this.A-(0,g.E)()),this.A=null):(this.Ka=null,this.u?this.o=!0:(this.o=!1,this.F.apply(null,this.B)))};g.t(w6,g.A);g.k=w6.prototype;g.k.BA=function(a){this.A=arguments;this.Ka||this.u?this.o=!0:x6(this)};
g.k.stop=function(){this.Ka&&(g.v.clearTimeout(this.Ka),this.Ka=null,this.o=!1,this.A=null)};
g.k.pause=function(){this.u++};
g.k.resume=function(){this.u--;this.u||!this.o||this.Ka||(this.o=!1,x6(this))};
g.k.X=function(){g.A.prototype.X.call(this);this.stop()};z6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
z6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};A6.prototype.o=null;A6.prototype.getOptions=function(){var a;(a=this.o)||(a={},KAa(this)&&(a[0]=!0,a[1]=!0),a=this.o=a);return a};var T8;g.Ua(JAa,A6);T8=new JAa;g.k=B6.prototype;g.k.Dj=null;g.k.eg=!1;g.k.cm=null;g.k.bx=null;g.k.Ol=null;g.k.Tl=null;g.k.ai=null;g.k.Ui=null;g.k.jk=null;g.k.gd=null;g.k.xo=0;g.k.kg=null;g.k.ws=null;g.k.ri=null;g.k.Tm=-1;g.k.yD=!0;g.k.kj=!1;g.k.iu=0;g.k.Cr=null;var PAa={},E6={};g.k=B6.prototype;g.k.setTimeout=function(a){this.C=a};
g.k.xO=function(a){a=a.target;var b=this.Cr;b&&3==S6(a)?b.BA():this.xE(a)};
g.k.xE=function(a){try{if(a==this.gd)a:{var b=S6(this.gd),c=this.gd.F,d=this.gd.getStatus();if(g.pe&&!g.Ud(10)||g.re&&!g.Td("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Hh&&!U6(this.gd))break a;this.kj||4!=b||7==c||(8==c||0>=d?this.o.Vf(3):this.o.Vf(2));L6(this);var e=this.gd.getStatus();this.Tm=e;var f=U6(this.gd);(this.eg=200==e)?(4==b&&H6(this),this.F?(QAa(this,b,f),g.Hh&&this.eg&&3==b&&(this.B.ma(this.u,"tick",this.rO),this.u.start())):G6(this,f),this.eg&&!this.kj&&(4==b?this.o.Yp(this):(this.eg=
!1,D6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.ri=3,F6(13)):(this.ri=0,F6(14)),H6(this),I6(this))}}catch(h){this.gd&&U6(this.gd)}finally{}};
g.k.rO=function(){var a=S6(this.gd),b=U6(this.gd);this.xo<b.length&&(L6(this),QAa(this,a,b),this.eg&&4!=a&&D6(this))};
g.k.LN=function(a){K6((0,g.x)(this.KN,this,a),0)};
g.k.KN=function(a){this.kj||(L6(this),G6(this,a),D6(this))};
g.k.CC=function(a){K6((0,g.x)(this.JN,this,a),0)};
g.k.JN=function(a){this.kj||(H6(this),this.eg=a,this.o.Yp(this),this.o.Vf(4))};
g.k.cancel=function(){this.kj=!0;H6(this)};
g.k.UN=function(){this.cm=null;var a=(0,g.E)();0<=a-this.bx?(2!=this.Tl&&this.o.Vf(3),H6(this),this.ri=2,F6(18),I6(this)):TAa(this,this.bx-a)};
g.k.getLastError=function(){return this.ri};g.k=WAa.prototype;g.k.gu=null;g.k.Be=null;g.k.Dr=!1;g.k.Fz=null;g.k.Ep=null;g.k.Ju=null;g.k.hu=null;g.k.kf=null;g.k.sh=-1;g.k.Sm=null;g.k.om=null;g.k.connect=function(a){this.hu=a;a=N6(this.o,null,this.hu);F6(3);this.Fz=(0,g.E)();var b=this.o.I;null!=b?(this.Sm=b[0],(this.om=b[1])?(this.kf=1,XAa(this)):(this.kf=2,P6(this))):(b6(a,"MODE","init"),this.Be=new B6(this,void 0,void 0,void 0),this.Be.Dj=this.gu,C6(this.Be,a,!1,null,!0),this.kf=0)};
g.k.MF=function(a){if(a)this.kf=2,P6(this);else{F6(4);var b=this.o;b.vg=b.di.sh;a7(b,9)}a&&this.Vf(2)};
g.k.At=function(a){return this.o.At(a)};
g.k.abort=function(){this.Be&&(this.Be.cancel(),this.Be=null);this.sh=-1};
g.k.Ez=function(){return!1};
g.k.tC=function(a,b){this.sh=a.Tm;if(0==this.kf)if(b){try{var c=this.u.parse(b)}catch(d){c=this.o;c.vg=this.sh;a7(c,2);return}this.Sm=c[0];this.om=c[1]}else c=this.o,c.vg=this.sh,a7(c,2);else if(2==this.kf)if(this.Dr)F6(7),this.Ju=(0,g.E)();else if("11111"==b){if(F6(6),this.Dr=!0,this.Ep=(0,g.E)(),c=this.Ep-this.Fz,!g.pe||g.Ud(10)||500>c)this.sh=200,this.Be.cancel(),F6(12),O6(this.o,this,!0)}else F6(8),this.Ep=this.Ju=(0,g.E)(),this.Dr=!1};
g.k.Yp=function(){this.sh=this.Be.Tm;if(this.Be.eg)0==this.kf?this.om?(this.kf=1,XAa(this)):(this.kf=2,P6(this)):2==this.kf&&((!g.pe||g.Ud(10)?!this.Dr:200>this.Ju-this.Ep)?(F6(11),O6(this.o,this,!1)):(F6(12),O6(this.o,this,!0)));else{0==this.kf?F6(9):2==this.kf&&F6(10);var a=this.o;this.Be.getLastError();a.vg=this.sh;a7(a,2)}};
g.k.ho=function(){return this.o.ho()};
g.k.isActive=function(){return this.o.isActive()};
g.k.Vf=function(a){this.o.Vf(a)};g.Ua(Q6,g.rf);var bBa=/^https?$/i,PCa=["POST","PUT"];g.k=Q6.prototype;
g.k.send=function(a,b,c,d){if(this.o)throw Error("[goog.net.XhrIo] Object is active with another request="+this.M+"; newUri="+a);b=b?b.toUpperCase():"GET";this.M=a;this.B="";this.F=0;this.fa=b;this.Y=!1;this.A=!0;this.o=this.T?LAa(this.T):LAa(T8);this.U=this.T?this.T.getOptions():T8.getOptions();this.o.onreadystatechange=(0,g.x)(this.pC,this);try{d6(T6(this,"Opening Xhr")),this.aa=!0,this.o.open(b,String(a),!0),this.aa=!1}catch(f){d6(T6(this,"Error opening Xhr: "+f.message));aBa(this,f);return}a=
c||"";var e=this.headers.clone();d&&kAa(d,function(f,h){e.set(h,f)});
d=g.cb(e.hf(),ZAa);c=g.v.FormData&&a instanceof g.v.FormData;!g.fb(PCa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,h){this.o.setRequestHeader(h,f)},this);
this.ga&&(this.o.responseType=this.ga);"withCredentials"in this.o&&this.o.withCredentials!==this.Z&&(this.o.withCredentials=this.Z);try{dBa(this),0<this.G&&(this.R=YAa(this.o),d6(T6(this,"Will abort after "+this.G+"ms if incomplete, xhr2 "+this.R)),this.R?(this.o.timeout=this.G,this.o.ontimeout=(0,g.x)(this.Gz,this)):this.N=g.cg(this.Gz,this.G,this)),d6(T6(this,"Sending request")),this.I=!0,this.o.send(a),this.I=!1}catch(f){d6(T6(this,"Send error: "+f.message)),aBa(this,f)}};
g.k.Gz=function(){"undefined"!=typeof g.D1&&this.o&&(this.B="Timed out after "+this.G+"ms, aborting",this.F=8,T6(this,this.B),this.dispatchEvent("timeout"),this.abort(8))};
g.k.abort=function(a){this.o&&this.A&&(T6(this,"Aborting"),this.A=!1,this.C=!0,this.o.abort(),this.C=!1,this.F=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),R6(this))};
g.k.X=function(){this.o&&(this.A&&(this.A=!1,this.C=!0,this.o.abort(),this.C=!1),R6(this,!0));Q6.tc.X.call(this)};
g.k.pC=function(){this.ha()||(this.aa||this.I||this.C?cBa(this):this.SM())};
g.k.SM=function(){cBa(this)};
g.k.isActive=function(){return!!this.o};
g.k.getStatus=function(){try{return 2<S6(this)?this.o.status:-1}catch(a){return-1}};
g.k.getLastError=function(){return"string"===typeof this.B?this.B:String(this.B)};g.k=V6.prototype;g.k.Yk=null;g.k.Hm=null;g.k.oe=null;g.k.Ec=null;g.k.fu=null;g.k.Hp=null;g.k.hy=null;g.k.Xp=null;g.k.Bn=0;g.k.wK=0;g.k.Ld=null;g.k.ii=null;g.k.bh=null;g.k.pj=null;g.k.di=null;g.k.ts=null;g.k.pl=-1;g.k.mA=-1;g.k.vg=-1;g.k.Rk=0;g.k.Dk=0;g.k.lj=8;var b7=new g.rf;g.Ua(fBa,g.Re);g.Ua(gBa,g.Re);g.Ua(hBa,g.Re);g.k=V6.prototype;g.k.connect=function(a,b,c,d,e){F6(0);this.fu=b;this.Hm=c||{};d&&void 0!==e&&(this.Hm.OSID=d,this.Hm.OAID=e);this.F?(K6((0,g.x)(this.zy,this,a),100),lBa(this)):this.zy(a)};
g.k.zy=function(a){this.di=new WAa(this);this.di.gu=this.Yk;this.di.u=this.C;this.di.connect(a)};
g.k.Ez=function(){return 0==this.o};
g.k.BC=function(a){this.ii=null;oBa(this,a)};
g.k.AC=function(){this.bh=null;this.Ec=new B6(this,this.A,"rpc",this.G);this.Ec.Dj=this.Yk;this.Ec.iu=0;var a=this.hy.clone();$5(a,"RID","rpc");$5(a,"SID",this.A);$5(a,"CI",this.ts?"0":"1");$5(a,"AID",this.pl);W6(this,a);if(!g.pe||g.Ud(10))$5(a,"TYPE","xmlhttp"),C6(this.Ec,a,!0,this.Xp,!1);else{$5(a,"TYPE","html");var b=this.Ec,c=!!this.Xp;b.Tl=3;b.ai=a6(a.clone());SAa(b,c)}};
g.k.tC=function(a,b){if(0!=this.o&&(this.Ec==a||this.oe==a))if(this.vg=a.Tm,this.oe==a&&3==this.o)if(7<this.lj){try{var c=this.C.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.bh){if(this.Ec)if(this.Ec.Ol+3E3<this.oe.Ol)Y6(this),this.Ec.cancel(),this.Ec=null;else break a;$6(this);F6(19)}}else this.mA=c[1],0<this.mA-this.pl&&37500>c[2]&&this.ts&&0==this.Dk&&!this.pj&&(this.pj=K6((0,g.x)(this.WK,this),6E3));else a7(this,11)}else b!=OCa.PQ.o&&a7(this,11);else if(this.Ec==
a&&Y6(this),!g.mc(b)){c=this.C.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.pl=e[0];e=e[1];2==this.o?"c"==e[0]?(this.A=e[1],this.Xp=e[2],e=e[3],null!=e?this.lj=e:this.lj=6,this.o=3,this.Ld&&this.Ld.ty(),this.hy=N6(this,this.ho()?this.Xp:null,this.fu),pBa(this)):"stop"==e[0]&&a7(this,7):3==this.o&&("stop"==e[0]?a7(this,7):"noop"!=e[0]&&this.Ld&&this.Ld.sy(e),this.Dk=0)}}};
g.k.WK=function(){null!=this.pj&&(this.pj=null,this.Ec.cancel(),this.Ec=null,$6(this),F6(20))};
g.k.Yp=function(a){if(this.Ec==a){Y6(this);this.Ec=null;var b=2}else if(this.oe==a)this.oe=null,b=1;else return;this.vg=a.Tm;if(0!=this.o)if(a.eg)1==b?(b=(0,g.E)()-a.Ol,b7.dispatchEvent(new gBa(b7,a.jk?a.jk.length:0,b,this.Rk)),X6(this),this.B.length=0):pBa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.vg)){if(d=1==b)this.oe||this.ii||1==this.o||2<=this.Rk?d=!1:(this.ii=K6((0,g.x)(this.BC,this,a),qBa(this,this.Rk)),this.Rk++,d=!0);d=!(d||2==b&&$6(this))}if(d)switch(c){case 1:a7(this,
5);break;case 4:a7(this,10);break;case 3:a7(this,6);break;case 7:a7(this,12);break;default:a7(this,2)}}};
g.k.nG=function(a){if(!g.fb(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.k.gP=function(a){a?F6(2):(F6(1),rBa(this,8))};
g.k.At=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new Q6;a.Z=!1;return a};
g.k.isActive=function(){return!!this.Ld&&this.Ld.isActive(this)};
g.k.Vf=function(a){b7.dispatchEvent(new hBa(b7,a))};
g.k.ho=function(){return!(!g.pe||g.Ud(10))};
g.k=sBa.prototype;g.k.ty=function(){};
g.k.sy=function(){};
g.k.ry=function(){};
g.k.jt=function(){};
g.k.cz=function(){return{}};
g.k.isActive=function(){return!0};g.k=tBa.prototype;g.k.isEmpty=function(){return g.gb(this.o)&&g.gb(this.u)};
g.k.clear=function(){this.o=[];this.u=[]};
g.k.contains=function(a){return g.fb(this.o,a)||g.fb(this.u,a)};
g.k.remove=function(a){var b=this.o;var c=(0,g.Lua)(b,a);0<=c?(g.jb(b,c),b=!0):b=!1;return b||g.kb(this.u,a)};
g.k.Yd=function(){for(var a=[],b=this.o.length-1;0<=b;--b)a.push(this.o[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Ua(c7,g.A);g.k=c7.prototype;g.k.EN=function(){this.Od=Math.min(3E5,2*this.Od);this.A();this.u&&this.start()};
g.k.start=function(){var a=this.Od+15E3*Math.random();this.o.jb(a);this.u=(0,g.E)()+a};
g.k.stop=function(){this.o.stop();this.u=0};
g.k.isActive=function(){return this.o.isActive()};
g.k.reset=function(){this.o.stop();this.Od=5E3};g.Ua(d7,sBa);g.k=d7.prototype;g.k.subscribe=function(a,b,c){return this.A.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.A.unsubscribe(a,b,c)};
g.k.Li=function(a){return this.A.Ej(a)};
g.k.S=function(a,b){return this.A.S.apply(this.A,arguments)};
g.k.dispose=function(){this.Tc||(this.Tc=!0,g.Pe(this.A),wBa(this),g.Pe(this.u),this.u=null,this.R=function(){return""})};
g.k.ha=function(){return this.Tc};
g.k.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.M="";this.u.stop();this.C=a||null;this.B=b||0;a=this.N+"/test";b=this.N+"/bind";var d=new V6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.U),e=this.o;e&&(e.Ld=null);d.Ld=this;this.o=d;e7(this);e?this.o.connect(a,b,this.F,e.A,e.pl):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.k.sendMessage=function(a,b){var c={_sc:a};b&&g.Xb(c,b);this.u.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):f7(this)&&(e7(this),mBa(this.o,c))};
g.k.ty=function(){this.u.reset();this.C=null;this.B=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)mBa(this.o,a[b])}this.S("handlerOpened")};
g.k.ry=function(a){var b=2==a&&401==this.o.vg;4==a||b||this.u.start();this.S("handlerError",a)};
g.k.jt=function(a){if(!this.u.isActive())this.S("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.k.cz=function(){var a={v:2};this.M&&(a.gsessionid=this.M);0!=this.B&&(a.ui=""+this.B);0!=this.I&&(a.ui=""+this.I);this.C&&g.Xb(a,this.C);return a};
g.k.sy=function(a){"S"==a[0]?this.M=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),kBa(this.o)):this.S("handlerMessage",new uBa(a[0],a[1]))};
g.k.LO=function(){this.u.isActive();var a=this.o,b=0;a.Ec&&b++;a.oe&&b++;0==b&&this.connect(this.C,this.B)};g7.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g7.prototype.A=function(a,b){a(Error("Request error: "+b.status))};
g7.prototype.C=function(a){a(Error("request timed out"))};var EBa=(0,g.E)(),j7=null,m7=Array(50),l7=-1,n7=!1;g.Ua(o7,g.O);o7.prototype.Ne=function(){return this.screens};
o7.prototype.contains=function(a){return!!l6(this.screens,a)};
o7.prototype.get=function(a){return a?m6(this.screens,a):null};
o7.prototype.info=function(a){k7(this.F,a)};g.t(p7,g.O);g.k=p7.prototype;g.k.start=function(){!this.o&&isNaN(this.Ka)&&this.CE()};
g.k.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Ka)||(g.Oo(this.Ka),this.Ka=NaN)};
g.k.X=function(){this.stop();g.O.prototype.X.call(this)};
g.k.CE=function(){this.Ka=NaN;this.o=g.wq(h7(this.F,"/pairing/get_screen"),{method:"POST",Cb:{pairing_code:this.C},timeout:5E3,onSuccess:(0,g.x)(this.IP,this),onError:(0,g.x)(this.HP,this),Te:(0,g.x)(this.JP,this)})};
g.k.IP=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.A;c.name=this.B;this.S("pairingComplete",new g6(c))};
g.k.HP=function(a){this.o=null;a.status&&404==a.status?this.u>=QCa.length?this.S("pairingFailed",Error("DIAL polling timed out")):(a=QCa[this.u],this.Ka=g.Mo((0,g.x)(this.CE,this),a),this.u++):this.S("pairingFailed",Error("Server error "+a.status))};
g.k.JP=function(){this.o=null;this.S("pairingFailed",Error("Server not responding"))};
var QCa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ua(r7,o7);g.k=r7.prototype;g.k.start=function(){q7(this)&&this.S("screenChange");!g.gt("yt-remote-lounge-token-expiration")&&IBa(this);g.Oo(this.o);this.o=g.Mo((0,g.x)(this.start,this),1E4)};
g.k.add=function(a,b){q7(this);FBa(this,a);s7(this,!1);this.S("screenChange");b(a);a.token||IBa(this)};
g.k.remove=function(a,b){var c=q7(this);HBa(this,a)&&(s7(this,!1),c=!0);b(a);c&&this.S("screenChange")};
g.k.qs=function(a,b,c,d){var e=q7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,s7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.S("screenChange")};
g.k.X=function(){g.Oo(this.o);r7.tc.X.call(this)};
g.k.aH=function(a){q7(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}s7(this,!b);b&&k7(this.F,"Missed "+b+" lounge tokens.")};
g.k.ZG=function(a){k7(this.F,"Requesting lounge tokens failed: "+a)};g.t(u7,g.O);g.k=u7.prototype;g.k.start=function(){var a=parseInt(g.gt("yt-remote-fast-check-period")||"0",10);(this.B=(0,g.E)()-144E5<a?0:a)?w7(this):(this.B=(0,g.E)()+3E5,g.ft("yt-remote-fast-check-period",this.B),this.Zv())};
g.k.isEmpty=function(){return g.Rb(this.o)};
g.k.update=function(){t7("Updating availability on schedule.");var a=this.F(),b=g.Db(this.o,function(c,d){return c&&!!m6(a,d)},this);
v7(this,b)};
g.k.X=function(){g.Oo(this.A);this.A=NaN;this.u&&(this.u.abort(),this.u=null);g.O.prototype.X.call(this)};
g.k.Zv=function(){g.Oo(this.A);this.A=NaN;this.u&&this.u.abort();var a=LBa(this);if(c6(a)){var b=h7(this.C,"/pairing/get_screen_availability");this.u=i7(this.C,b,{lounge_token:g.Lb(a).join(",")},(0,g.x)(this.oN,this,a),(0,g.x)(this.nN,this))}else v7(this,{}),w7(this)};
g.k.oN=function(a,b){this.u=null;var c=g.Lb(LBa(this));if(g.zb(c,g.Lb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;v7(this,d);w7(this)}else this.pc("Changing Screen set during request."),this.Zv()};
g.k.nN=function(a){this.pc("Screen availability failed: "+a);this.u=null;w7(this)};
g.k.pc=function(a){k7("OnlineScreenService",a)};g.Ua(x7,o7);g.k=x7.prototype;g.k.start=function(){this.u.start();this.o.start();this.screens.length&&(this.S("screenChange"),this.o.isEmpty()||this.S("onlineScreenChange"))};
g.k.add=function(a,b,c){this.u.add(a,b,c)};
g.k.remove=function(a,b,c){this.u.remove(a,b,c);this.o.update()};
g.k.qs=function(a,b,c,d){this.u.contains(a)?this.u.qs(a,b,c,d):(a="Updating name of unknown screen: "+a.name,k7(this.F,a),d(Error(a)))};
g.k.Ne=function(a){return a?this.screens:g.nb(this.screens,(0,g.De)(this.A,function(b){return!this.contains(b)},this))};
g.k.DE=function(){return(0,g.De)(this.Ne(!0),function(a){return!!this.o.o[a.id]},this)};
g.k.EE=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new p7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(h){g.Pe(f);d(y7(this,h))},this));
f.subscribe("pairingFailed",function(h){g.Pe(f);e(h)});
f.start();return(0,g.x)(f.stop,f)};
g.k.LP=function(a,b,c,d){g.wq(h7(this.C,"/pairing/get_screen"),{method:"POST",Cb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var h=new g6(f.screen||{});if(!h.name||PBa(this,h.name)){a:{var l=h.name;for(var m=2,n=b(l,m);PBa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}h.name=l}c(y7(this,h))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
Te:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.k.X=function(){g.Pe(this.u);g.Pe(this.o);x7.tc.X.call(this)};
g.k.hH=function(){QBa(this);this.S("screenChange");this.o.update()};
x7.prototype.dispose=x7.prototype.dispose;g.Ua(A7,g.O);g.k=A7.prototype;g.k.getScreen=function(){return this.I};
g.k.sr=function(a){this.I=a;this.S("sessionScreen",this.I)};
g.k.Se=function(a){this.ha()||(a&&B7(this,""+a),this.I=null,this.S("sessionScreen",null))};
g.k.info=function(a){k7(this.U,a)};
g.k.GE=function(){return null};
g.k.lw=function(a){var b=this.o;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){B7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.X=function(){this.lw("");A7.tc.X.call(this)};g.t(C7,A7);g.k=C7.prototype;g.k.kw=function(a){if(this.u){if(this.u==a)return;B7(this,"Overriding cast sesison with new session object");this.u.removeUpdateListener(this.C);this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.u=a;this.u.addUpdateListener(this.C);this.u.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);SBa(this)};
g.k.ql=function(a){this.info("launchWithParams no-op for Cast: "+g.Sk(a))};
g.k.stop=function(){this.u?this.u.stop((0,g.x)(function(){this.Se()},this),(0,g.x)(function(){this.Se(Error("Failed to stop receiver app."))},this)):this.Se(Error("Stopping cast device witout session."))};
g.k.lw=function(){};
g.k.X=function(){this.info("disposeInternal");g.Oo(this.A);this.A=0;this.u&&(this.u.removeUpdateListener(this.C),this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.u=null;A7.prototype.X.call(this)};
g.k.dO=function(a,b){if(!this.ha())if(b){var c=y6(b);if(g.Pa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Sk(c));switch(d){case "mdxSessionStatus":RBa(this,c.screenId);break;default:B7(this,"Unknown youtube message: "+d)}}else B7(this,"Unable to parse message.")}else B7(this,"No data in message.")};
g.k.xz=function(a,b,c,d){OBa(this.M,this.o.label,a,this.o.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(B7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Mo((0,g.x)(this.xz,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.GE=function(){return this.u};
g.k.MP=function(a){this.ha()||a||(B7(this,"Cast session died."),this.Se())};g.t(D7,A7);g.k=D7.prototype;g.k.kw=function(a){this.A=a;this.A.addUpdateListener(this.R)};
g.k.ql=function(a){this.B=a;this.F()};
g.k.stop=function(){this.u();this.u=g.Ka;g.Oo(this.C);this.A?this.A.stop((0,g.x)(this.Se,this,null),(0,g.x)(this.Se,this,"Failed to stop DIAL device.")):this.Se()};
g.k.X=function(){this.u();this.u=g.Ka;g.Oo(this.C);this.A&&this.A.removeUpdateListener(this.R);this.A=null;A7.prototype.X.call(this)};
g.k.PP=function(a){this.ha()||a||(B7(this,"DIAL session died."),this.u(),this.u=g.Ka,this.Se())};
g.k.tu=function(a){this.N=k6();if(this.B){var b=new chrome.cast.DialLaunchResponse(!0,UBa(this));a(b);TBa(this)}else this.F=(0,g.x)(function(){g.Oo(this.C);this.F=g.Ka;this.C=NaN;var c=new chrome.cast.DialLaunchResponse(!0,UBa(this));a(c);TBa(this)},this),this.C=g.Mo((0,g.x)(function(){this.F()},this),100)};
g.k.xH=function(a,b,c){OBa(this.M,this.G.receiver.label,a,this.o.friendlyName,(0,g.x)(function(d){d&&d.token?(this.sr(d),b(new chrome.cast.DialLaunchResponse(!1))):this.tu(b,c)},this),(0,g.x)(function(d){B7(this,"Failed to get DIAL screen: "+d);
this.tu(b,c)},this))};g.t(E7,A7);E7.prototype.stop=function(){this.Se()};
E7.prototype.kw=function(){};
E7.prototype.ql=function(){g.Oo(this.u);this.u=NaN;var a=m6(this.M.Ne(),this.o.label);a?this.sr(a):this.Se(Error("No such screen"))};
E7.prototype.X=function(){g.Oo(this.u);this.u=NaN;A7.prototype.X.call(this)};g.t(F7,g.O);g.k=F7.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.G);this.I||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.XM,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.wC,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.rL,this);chrome.cast.initialize(c,(0,g.x)(function(){this.ha()||
(chrome.cast.addReceiverActionListener(this.B),BBa(),this.u.subscribe("onlineScreenChange",(0,g.x)(this.FE,this)),this.A=WBa(this),chrome.cast.setCustomReceivers(this.A,g.Ka,(0,g.x)(function(h){this.pc("Failed to set initial custom receivers: "+g.Sk(h))},this)),this.S("yt-remote-cast2-availability-change",H7(this)),b(!0))},this),(0,g.x)(function(h){this.pc("Failed to initialize API: "+g.Sk(h));
b(!1)},this))};
g.k.RO=function(a,b){G7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.getScreen();if(!a||c&&c.id!=a)G7("Unsetting old screen status: "+this.o.o.friendlyName),I7(this,null)}if(a&&b){if(!this.o){c=m6(this.u.Ne(),a);if(!c){G7("setConnectedScreenStatus: Unknown screen.");return}var d=VBa(this,c);d||(G7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.A.push(d),chrome.cast.setCustomReceivers(this.A,
g.Ka,(0,g.x)(function(e){this.pc("Failed to set initial custom receivers: "+g.Sk(e))},this)));
G7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);I7(this,new E7(this.u,d),!0)}this.o.lw(b)}else G7("setConnectedScreenStatus: no screen.")};
g.k.SO=function(a){this.ha()?this.pc("Setting connection data on disposed cast v2"):this.o?this.o.ql(a):this.pc("Setting connection data without a session")};
g.k.OP=function(){this.ha()?this.pc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),I7(this,null)):G7("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.wC,this),(0,g.x)(this.rN,this))};
g.k.X=function(){this.u.unsubscribe("onlineScreenChange",(0,g.x)(this.FE,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.B);var a=yBa,b=g.Ja("yt.mdx.remote.debug.handlers_");g.kb(b||[],a);g.Pe(this.o);g.O.prototype.X.call(this)};
g.k.pc=function(a){k7("Controller",a)};
g.k.yC=function(a,b){this.o==a&&(b||I7(this,null),this.S("yt-remote-cast2-session-change",b))};
g.k.TM=function(a,b){if(!this.ha())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),G7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.o.label!=a.label)G7("onReceiverAction_: Stopping active receiver: "+this.o.o.friendlyName),this.o.stop();else{G7("onReceiverAction_: Casting to active receiver.");this.o.getScreen()&&this.S("yt-remote-cast2-session-change",this.o.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:I7(this,
new E7(this.u,a));break;case chrome.cast.ReceiverType.DIAL:I7(this,new D7(this.u,a,this.F));break;case chrome.cast.ReceiverType.CAST:I7(this,new C7(this.u,a));break;default:this.pc("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.o.label==a.label?this.o.stop():this.pc("Stopping receiver w/o session: "+a.friendlyName)}else this.pc("onReceiverAction_ called without receiver.")};
g.k.rL=function(a){if(this.ha())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.pc("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.o:null;if(!c||c.label!=b.label)return this.pc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.getScreen())return G7("Reselecting dial screen."),
this.S("yt-remote-cast2-session-change",this.o.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.pc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);I7(this,new D7(this.u,b,this.F))}b=this.o;b.G=a;return b.G.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.xH,b,(b.G.extraData||{}).screenId||null)):new Promise((0,g.x)(b.tu,b))};
g.k.wC=function(a){if(!this.ha()){G7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)G7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),I7(this,new C7(this.u,b),!0);else{this.pc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.o,d=m6(this.u.Ne(),c.label);d&&h6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(G7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Pe(this.o),this.o=new C7(this.u,b),this.o.subscribe("sessionScreen",(0,g.x)(this.yC,this,this.o)),this.o.ql(null));this.o.kw(a)}}};
g.k.NP=function(){return this.o?this.o.GE():null};
g.k.rN=function(a){this.ha()||(this.pc("Failed to estabilish a session: "+g.Sk(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&I7(this,null))};
g.k.XM=function(a){G7("Receiver availability updated: "+a);if(!this.ha()){var b=H7(this);this.C=a==chrome.cast.ReceiverAvailability.AVAILABLE;H7(this)!=b&&this.S("yt-remote-cast2-availability-change",H7(this))}};
g.k.FE=function(){this.ha()||(this.A=WBa(this),G7("Updating custom receivers: "+g.Sk(this.A)),chrome.cast.setCustomReceivers(this.A,g.Ka,(0,g.x)(function(){this.pc("Failed to set custom receivers.")},this)),this.S("yt-remote-cast2-availability-change",H7(this)))};
F7.prototype.setLaunchParams=F7.prototype.SO;F7.prototype.setConnectedScreenStatus=F7.prototype.RO;F7.prototype.stopSession=F7.prototype.OP;F7.prototype.getCastSession=F7.prototype.NP;F7.prototype.requestSession=F7.prototype.requestSession;F7.prototype.init=F7.prototype.init;F7.prototype.dispose=F7.prototype.dispose;var O7=[];g.k=T7.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";U7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.wg=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.F=a.playerTimeAt,this.C=a.seekableStart,this.u=a.seekableEnd,this.I=a.duration,this.M=a.loadedTime,this.B=a.liveIngestionTime,this.A=!isNaN(this.B))};
g.k.sb=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.getDuration=function(){return this.A?this.I+V7(this):this.I};
g.k.clone=function(){return new T7(Z7(this))};g.t(a8,g.O);g.k=a8.prototype;g.k.play=function(){1==this.o?(this.u?this.u.play(null,g.Ka,g8(this,"play")):f8(this,"play"),e8(this,1,X7(b8(this))),this.S("remotePlayerChange")):c8(this,this.play)};
g.k.pause=function(){1==this.o?(this.u?this.u.pause(null,g.Ka,g8(this,"pause")):f8(this,"pause"),e8(this,2,X7(b8(this))),this.S("remotePlayerChange")):c8(this,this.pause)};
g.k.seekTo=function(a){if(1==this.o){if(this.u){var b=b8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.sb()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.Ka,g8(this,"seekTo",{newTime:a}))}else f8(this,"seekTo",{newTime:a});e8(this,3,a);this.S("remotePlayerChange")}else c8(this,g.Sa(this.seekTo,a))};
g.k.stop=function(){if(1==this.o){this.u?this.u.stop(null,g.Ka,g8(this,"stopVideo")):f8(this,"stopVideo");var a=b8(this);a.index=-1;a.videoId="";U7(a);d8(this,a);this.S("remotePlayerChange")}else c8(this,this.stop)};
g.k.setVolume=function(a,b){if(1==this.o){var c=b8(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.x)(function(){k7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.pc("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.x)(function(){k7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.pc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);f8(this,"setVolume",e)}c.muted=b;c.volume=a;d8(this,c)}else c8(this,g.Sa(this.setVolume,a,b))};
g.k.BE=function(a,b){if(1==this.o){var c=b8(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Sk(b.style),g.Xb(d,c.o));f8(this,"setSubtitlesTrack",d);d8(this,c)}else c8(this,g.Sa(this.BE,a,b))};
g.k.setAudioTrack=function(a,b){if(1==this.o){var c=b.getLanguageInfo().getId();f8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=b8(this);d.audioTrackId=c;d8(this,d)}else c8(this,g.Sa(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){var l=b8(this);c=c||0;var m={videoId:a,currentIndex:c};Y7(l,a,c);void 0!==b&&(W7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=h&&(m.locationInfo=g.Sk(h));f8(this,"setPlaylist",m);d||d8(this,l)};
g.k.yr=function(a,b){if(1==this.o){if(a&&b){var c=b8(this);Y7(c,a,b);d8(this,c)}f8(this,"previous")}else c8(this,g.Sa(this.yr,a,b))};
g.k.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=b8(this);Y7(c,a,b);d8(this,c)}f8(this,"next")}else c8(this,g.Sa(this.nextVideo,a,b))};
g.k.My=function(){1==this.o?f8(this,"dismissAutoplay"):c8(this,this.My)};
g.k.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.S("proxyStateChange",a,this.o)}g.O.prototype.dispose.call(this)};
g.k.X=function(){iCa(this);this.B=null;this.C.clear();$7(this,null);g.O.prototype.X.call(this)};
g.k.fx=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.S("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)b=a=this.C,g.gb(b.o)&&(b.o=b.u,b.o.reverse(),b.u=[]),a.o.pop().apply(this);else 3==a&&this.dispose()}};
g.k.QM=function(a,b){this.S(a,b)};
g.k.cL=function(a){if(!a)this.Fn(null),$7(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=b8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)k7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,d8(this,b)}};
g.k.Fn=function(a){k7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.I);if(this.u=a)this.u.addUpdateListener(this.I),jCa(this),this.S("remotePlayerChange")};
g.k.bL=function(a){a?(jCa(this),this.S("remotePlayerChange")):this.Fn(null)};
g.k.Fw=function(){f8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.kL=function(){var a=fCa();a&&$7(this,a)};
g.k.pc=function(a){k7("CP",a)};g.t(h8,g.O);g.k=h8.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,h=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==h&&(l.currentIndex=h);c&&(this.ib.listId=c);this.ib.videoId=d;this.ib.index=h||0;this.ib.state=3;W7(this.ib,m);this.B="UNSUPPORTED";i8("Connecting with setPlaylist and params: "+g.Sk(l));this.o.connect({method:"setPlaylist",
params:g.Sk(l)},a,wAa())}else i8("Connecting without params"),this.o.connect({},a,wAa());lCa(this)};
g.k.dispose=function(){this.ha()||(this.S("beforeDispose"),j8(this,3));g.O.prototype.dispose.call(this)};
g.k.X=function(){k8(this);m8(this);l8(this);g.Oo(this.G);this.G=NaN;g.Oo(this.I);this.I=NaN;this.A=null;g.jp(this.U);this.U.length=0;this.o.dispose();g.O.prototype.X.call(this);this.B=this.F=this.u=this.ib=this.o=null};
g.k.TG=function(){this.Mk(2)};
g.k.gL=function(){i8("Channel opened");this.R&&(this.R=!1,l8(this),this.N=g.Mo((0,g.x)(function(){i8("Timing out waiting for a screen.");this.Mk(1)},this),15E3));
AAa(vBa(this.o),this.T)};
g.k.dL=function(){i8("Channel closed");isNaN(this.C)?r6(!0):r6();this.dispose()};
g.k.eL=function(a){r6();isNaN(this.Om())?(i8("Channel error: "+a+" without reconnection"),this.dispose()):(this.R=!0,i8("Channel error: "+a+" with reconnection in "+this.Om()+" ms"),j8(this,2))};
g.k.fL=function(a){a.params?i8("Received: action="+a.action+", params="+g.Sk(a.params)):i8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=y6(a.params.devices);this.u=(0,g.Lc)(a,function(c){return new f6(c)});
a=!!g.cb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
oCa(this,a);break;case "loungeScreenDisconnected":g.lb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
oCa(this,!1);break;case "remoteConnected":var b=new f6(y6(a.params.device));g.cb(this.u,function(c){return b?c.id==b.id:!1})||gAa(this.u,b);
break;case "remoteDisconnected":b=new f6(y6(a.params.device));g.lb(this.u,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":qCa(this,a);break;case "nowPlaying":sCa(this,a);break;case "onStateChange":rCa(this,a);break;case "onAdStateChange":tCa(this,a);break;case "onVolumeChanged":uCa(this,a);break;case "onSubtitlesTrackChanged":pCa(this,a);break;case "nowAutoplaying":vCa(this,a);break;case "autoplayDismissed":this.S("autoplayDismissed");break;case "autoplayUpNext":this.F=a.params.videoId||null;this.S("autoplayUpNext",this.F);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.S("autoplayModeChange",this.B);"DISABLED"==this.B&&this.S("autoplayDismissed");break;case "onHasPreviousNextChanged":wCa(this,a);break;case "requestAssistedSignIn":this.S("assistedSignInRequested",a.params.authCode);break;default:i8("Unrecognized action: "+a.action)}};
g.k.HO=function(){if(this.A){var a=this.A;this.A=null;this.ib.videoId!=a&&n8(this,"getNowPlaying")}};
g.k.IG=function(){var a=3;this.ha()||(a=0,isNaN(this.Om())?f7(this.o)&&isNaN(this.C)&&(a=1):a=2);return a};
g.k.Mk=function(a){i8("Disconnecting with "+a);k8(this);this.S("beforeDisconnect",a);1==a&&r6();wBa(this.o,a);this.dispose()};
g.k.GG=function(){var a=this.ib;this.A&&(a=this.ib.clone(),Y7(a,this.A,a.index));return Z7(a)};
g.k.TO=function(a){var b=new T7(a);b.videoId&&b.videoId!=this.ib.videoId&&(this.A=b.videoId,g.Oo(this.G),this.G=g.Mo((0,g.x)(this.HO,this),5E3));var c=[];this.ib.listId==b.listId&&this.ib.videoId==b.videoId&&this.ib.index==b.index||c.push("remoteQueueChange");this.ib.playerState==b.playerState&&this.ib.volume==b.volume&&this.ib.muted==b.muted&&X7(this.ib)==X7(b)&&g.Sk(this.ib.o)==g.Sk(b.o)||c.push("remotePlayerChange");this.ib.reset(a);(0,g.y)(c,function(d){this.S(d)},this)};
g.k.vz=function(){var a=this.o.F.id,b=g.cb(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.Om=function(){var a=this.o;return a.u.isActive()?a.u.u-(0,g.E)():NaN};
g.k.vG=function(){return this.B||"UNSUPPORTED"};
g.k.wG=function(){return this.F||""};
g.k.GP=function(){if(!isNaN(this.Om())){var a=this.o.u;g.En(a.o);a.start()}};
g.k.PO=function(a,b){n8(this,a,b);nCa(this)};
g.k.AE=function(){var a=g.Eq("SID","")||"",b=g.Eq("SAPISID","")||"";if(!a&&!b)return"";a=g.Ag(g.hg(a),2);b=g.Ag(g.hg(b),2);return g.Ag(g.hg(a+","+b),2)};
h8.prototype.subscribe=h8.prototype.subscribe;h8.prototype.unsubscribeByKey=h8.prototype.Li;h8.prototype.getProxyState=h8.prototype.IG;h8.prototype.disconnect=h8.prototype.Mk;h8.prototype.getPlayerContextData=h8.prototype.GG;h8.prototype.setPlayerContextData=h8.prototype.TO;h8.prototype.getOtherConnectedRemoteId=h8.prototype.vz;h8.prototype.getReconnectTimeout=h8.prototype.Om;h8.prototype.getAutoplayMode=h8.prototype.vG;h8.prototype.getAutoplayVideoId=h8.prototype.wG;h8.prototype.reconnect=h8.prototype.GP;
h8.prototype.sendMessage=h8.prototype.PO;h8.prototype.getXsrfToken=h8.prototype.AE;g.t(o8,o7);g.k=o8.prototype;g.k.Ne=function(a){return this.Nd.$_gs(a)};
g.k.contains=function(a){return!!this.Nd.$_c(a)};
g.k.get=function(a){return this.Nd.$_g(a)};
g.k.start=function(){this.Nd.$_st()};
g.k.add=function(a,b,c){this.Nd.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Nd.$_r(a,b,c)};
g.k.qs=function(a,b,c,d){this.Nd.$_un(a,b,c,d)};
g.k.X=function(){for(var a=0,b=this.o.length;a<b;++a)this.Nd.$_ubk(this.o[a]);this.o.length=0;this.Nd=null;o7.prototype.X.call(this)};
g.k.KP=function(){this.S("screenChange")};
g.k.tM=function(){this.S("onlineScreenChange")};
x7.prototype.$_st=x7.prototype.start;x7.prototype.$_gspc=x7.prototype.LP;x7.prototype.$_gsppc=x7.prototype.EE;x7.prototype.$_c=x7.prototype.contains;x7.prototype.$_g=x7.prototype.get;x7.prototype.$_a=x7.prototype.add;x7.prototype.$_un=x7.prototype.qs;x7.prototype.$_r=x7.prototype.remove;x7.prototype.$_gs=x7.prototype.Ne;x7.prototype.$_gos=x7.prototype.DE;x7.prototype.$_s=x7.prototype.subscribe;x7.prototype.$_ubk=x7.prototype.Li;var H8=null,G8=!1,p8=null,q8=null,F8=null,u8=[];g.t(I8,g.A);g.k=I8.prototype;g.k.X=function(){g.A.prototype.X.call(this);this.o.stop();this.u.stop();this.G.stop();this.N();var a=this.ab;a.unsubscribe("proxyStateChange",this.sC,this);a.unsubscribe("remotePlayerChange",this.Mn,this);a.unsubscribe("remoteQueueChange",this.tr,this);a.unsubscribe("previousNextChange",this.oC,this);a.unsubscribe("nowAutoplaying",this.kC,this);a.unsubscribe("autoplayDismissed",this.KB,this);this.ab=this.module=null};
g.k.RA=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.ab.o)if(J8(this)){if(!b8(this.ab).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":b8(this.ab).sb()?this.ab.pause():this.ab.play();break;case "control_play":this.ab.play();break;case "control_pause":this.ab.pause();break;case "control_seek":this.F.BA(c[0],c[1]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.H.getCurrentTime();L8(this,0===c?void 0:c);break;case "control_seek":L8(this,c[0]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.aL=function(a){this.G.OG(a)};
g.k.qP=function(a){this.RA("control_subtitles_set_track",g.Rb(a)?null:a)};
g.k.MD=function(){var a=this.H.getOption("captions","track");g.Rb(a)||K8(this,a)};
g.k.Xb=function(a){this.module.Xb(a,this.H.getVideoData().lengthSeconds)};
g.k.aC=function(a){if(J8(this)){this.ab.unsubscribe("remotePlayerChange",this.Mn,this);var b=Math.round(a.volume);a=!!a.muted;var c=b8(this.ab);if(b!==c.volume||a!==c.muted)this.ab.setVolume(b,a),this.I.start();this.ab.subscribe("remotePlayerChange",this.Mn,this)}};
g.k.UL=function(){g.Rb(this.A)||ICa(this,this.A);this.B=!1};
g.k.sC=function(a,b){this.u.stop();2===b&&this.JD()};
g.k.Mn=function(){if(J8(this)){this.o.stop();var a=b8(this.ab);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.module.md=1;break;case 1082:case 1083:this.module.md=0;break;default:this.module.md=-1}switch(a.playerState){case 1081:case 1:this.Qc(new g.fG(8));this.ID();break;case 1085:case 3:this.Qc(new g.fG(9));break;case 1083:case 0:this.Qc(new g.fG(2));this.F.stop();this.Xb(this.H.getVideoData().lengthSeconds);break;case 1084:this.Qc(new g.fG(4));break;case 2:this.Qc(new g.fG(4));
this.Xb(X7(a));break;case -1:this.Qc(new g.fG(64));break;case -1E3:this.Qc(new g.fG(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=b8(this.ab).o;var b=this.A;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.A=a,ICa(this,a));a=b8(this.ab);-1===a.volume||Math.round(this.H.getVolume())===a.volume&&this.H.isMuted()===a.muted||this.I.isActive()||this.nE()}else HCa(this)};
g.k.oC=function(){this.H.S("mdxpreviousnextchange")};
g.k.tr=function(){J8(this)||HCa(this)};
g.k.kC=function(a){isNaN(a)||this.H.S("mdxnowautoplaying",a)};
g.k.KB=function(){this.H.S("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){J8(this)&&this.ab.setAudioTrack(this.H.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===b8(this.ab).playerState?L8(this,a):b&&this.ab.seekTo(a)};
g.k.nE=function(){if(J8(this)){var a=b8(this.ab);this.events.ob(this.M);a.muted?this.H.mute():this.H.unMute();this.H.setVolume(a.volume);this.M=this.events.L(this.H,"onVolumeChange",this.aC)}};
g.k.ID=function(){this.o.stop();if(!this.ab.ha()){var a=b8(this.ab);a.sb()&&this.Qc(new g.fG(8));this.Xb(X7(a));this.o.start()}};
g.k.JD=function(){this.u.stop();this.o.stop();var a=this.ab.B.getReconnectTimeout();2==this.ab.o&&!isNaN(a)&&this.u.start()};
g.k.Qc=function(a){this.u.stop();var b=this.C;if(!g.kG(b,a)){var c=g.T(a,2);c!==g.T(this.C,2)&&g.aU(this.H.app,c);this.C=a;KCa(this.module,b,a)}};g.t(M8,g.U);M8.prototype.Yb=function(){this.o.show()};
M8.prototype.Sa=function(){this.o.hide()};
M8.prototype.u=function(){g.vO("https://support.google.com/youtube/answer/7640706")};
M8.prototype.A=function(){e6("mdx-manual-pairing-popup-ok");this.Sa()};g.t(N8,g.U);N8.prototype.Yb=function(){this.o.show()};
N8.prototype.Sa=function(){this.o.hide()};
N8.prototype.u=function(){e6("mdx-privacy-popup-cancel");this.Sa()};
N8.prototype.A=function(){e6("mdx-privacy-popup-confirm");this.Sa()};g.t(O8,g.U);O8.prototype.u=function(a){JCa(this,a.state)};g.t(P8,g.JR);P8.prototype.B=function(){var a=this.H.getOption("remote","receivers");a&&1<a.length&&!this.H.getOption("remote","quickCast")?(this.Ti=g.Bb(a,this.o,this),g.LR(this,(0,g.Lc)(a,this.o)),a=this.H.getOption("remote","currentReceiver"),this.Ob(this.o(a)),this.enable(!0)):this.enable(!1)};
P8.prototype.o=function(a){return a.key};
P8.prototype.Tf=function(a){return"cast-selector-receiver"===a?"Cast...":this.Ti[a].name};
P8.prototype.zd=function(a){g.JR.prototype.zd.call(this,a);this.H.setOption("remote","currentReceiver",this.Ti[a]);this.Ma.Sa()};g.t(Q8,g.UN);g.k=Q8.prototype;
g.k.create=function(){BCa(g.uy(this.player.O()));this.subscriptions.push(g.To("yt-remote-before-disconnect",this.YK,this));this.subscriptions.push(g.To("yt-remote-connection-change",this.YM,this));this.subscriptions.push(g.To("yt-remote-receiver-availability-change",this.qC,this));this.subscriptions.push(g.To("yt-remote-auto-connect",this.WM,this));this.subscriptions.push(g.To("yt-remote-receiver-resumed",this.VM,this));this.subscriptions.push(g.To("mdx-privacy-popup-confirm",this.vO,this));this.subscriptions.push(g.To("mdx-privacy-popup-cancel",
this.uO,this));this.subscriptions.push(g.To("mdx-manual-pairing-popup-ok",this.PH,this));this.qC()};
g.k.load=function(){this.player.cancelPlayback();g.UN.prototype.load.call(this);this.og=new I8(this,this.player,this.ab);var a=(a=GCa())?a.currentTime:0;var b=E8()?new a8(z8(),void 0):null;0==a&&b&&(a=X7(b8(b)));0!==a&&this.Xb(a);KCa(this,this.Tb,this.Tb);g.hU(this.player.app,6)};
g.k.unload=function(){this.player.S("mdxautoplaycanceled");this.gi=this.Qf;g.Qe(this.og,this.ab);this.ab=this.og=null;g.UN.prototype.unload.call(this);g.hU(this.player.app,5);R8(this)};
g.k.X=function(){g.Uo(this.subscriptions);g.UN.prototype.X.call(this)};
g.k.Jg=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.og.RA.apply(this.og,[a].concat(g.la(c)))};
g.k.getAdState=function(){return this.md};
g.k.KG=function(){return this.loaded?this.og.suggestion:null};
g.k.wg=function(){return this.ab?b8(this.ab).wg:!1};
g.k.hasNext=function(){return this.ab?b8(this.ab).hasNext:!1};
g.k.Xb=function(a,b){this.nA=a||0;this.player.S("progresssync",a,b)};
g.k.getCurrentTime=function(){return this.nA};
g.k.getProgressState=function(){var a=b8(this.ab),b=this.player.getVideoData();return{allowSeeking:g.Q(this.player.O().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.ld():!a.isAdPlaying()&&this.player.ld(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.A?a.B+V7(a):a.B,isAtLiveHead:1>=(a.A?a.u+V7(a):a.u)-this.getCurrentTime(),loaded:a.M,seekableEnd:a.A?a.u+V7(a):a.u,seekableStart:0<a.C?a.C+
V7(a):a.C}};
g.k.nextVideo=function(){this.ab&&this.ab.nextVideo()};
g.k.yr=function(){this.ab&&this.ab.yr()};
g.k.YK=function(a){1===a&&(this.Mv=this.ab?b8(this.ab):null)};
g.k.YM=function(){var a=E8()?new a8(z8(),void 0):null;if(a){var b=this.gi;this.loaded&&this.unload();this.ab=a;this.Mv=null;b.key!==this.Qf.key&&(this.gi=b,this.load())}else g.Pe(this.ab),this.ab=null,this.loaded&&(this.unload(),(a=this.Mv)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,X7(a)));this.player.S("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.qC=function(){this.Ti=[this.Qf].concat(DCa());var a=A8()||this.Qf;S8(this,a);this.player.oa("onMdxReceiversChange")};
g.k.WM=function(){var a=A8();S8(this,a)};
g.k.VM=function(){this.gi=A8()};
g.k.vO=function(){this.Nn=!0;R8(this);G8=!1;H8&&C8(H8,1);H8=null};
g.k.uO=function(){this.Nn=!1;R8(this);S8(this,this.Qf);this.gi=this.Qf;G8=!1;H8=null;this.player.playVideo()};
g.k.PH=function(){this.Bq=!0;R8(this);g.ft("yt-remote-manual-pairing-warning-shown",!0,2592E3);G8=!1;H8&&C8(H8,1);H8=null};
g.k.hd=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Ti;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?R7():S8(this,b)),this.loaded?this.gi:this.Qf;case "quickCast":return 2===this.Ti.length&&"cast-selector-receiver"===this.Ti[1].key?(b&&R7(),!0):!1}};
g.k.Fw=function(){this.ab.Fw()};
g.k.dg=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.eO.remote=Q8;})(_yt_player);
